:fn-kran: pass:c,q[footnote:kran[[#kran-as-is]#Decided to leave the name of Krán as is# with the Hungarian https://en.wikipedia.org/wiki/%C3%81["_á_"] sound (i.e., "_a_" with an https://en.wikipedia.org/wiki/Acute_accent[acute accent]) instead of using a variant closer to English (such as "_Kraan_"); it sounds more exotic and can't see what could be gained from changing it.]]

:fn-kran-reuse: footnote:kran[]

:fn-krani: pass:c,q[footnote:[The first word of the original title, "_Kráni Krónika_" is a https://en.wikipedia.org/wiki/Demonym[demonym]; in Hungarian, the "_-i_" suffix is used to create such an adjective from the name of a place, and, coincidentally, https://en.wikipedia.org/wiki/Demonym#Suffixation[this suffix is also available in English]. This fact and my decision in <<kran-as-is,the footnote above>>  made it possible to keep using the Hungarian original.]]

:fn-krani-kronika: pass:c,q[footnote:[The literal translation of the original title, "_Kráni Krónika_", is "_A Chronicle from Krán_" - in this case, that is, because the "_-i_" "modifier" at the end of "_Krán_" can mean "_from Krán_" or "_of Kran_", depending of the context. Here, it is about a fictional historical account of a conflict between two parties *within the borders* of Krán, and not about the empire of Krán itself.]]

[[fn-kran,fn-kran]]
= Kráni{fn-kran}{fn-krani} Chronicle{fn-krani-kronika}
Raoul Renier

NOTE: This document is also rendered in https://m-a-g-u-s.github.io/krani-chornicle/[HTML].

// The git commit log should suffice for `revhistory` for now (https://tdg.docbook.org/tdg/5.2/revhistory.html)

// TODO https://stackoverflow.com/questions/75406048/how-to-mark-up-an-author-with-their-pen-name-pseudonym-in-docbook-5

// Sokféle hazug és téves szóbeszéd járja Ynev emberlakta vidékein a kráni fejvadász-klánokról.  Egyesek vérivó szörnyeknek vélik őket, akik emberi mivoltuk utolsó maradványait is rég maguk mögött hagyták már; mások azt hiszik róluk, csupa szoborszép, atlétatermetű harcost számlálnak, akik csupán megszokásból gonoszak, mert ezt diktálják hazájuk hagyományai. Rebesgetik, egyéb dolguk sincsen, mint hogy folyton beleártsák magukat a külvilágban folyó eseményekbe, kalandozókkal és koronás főkkel perlekedjenek, kifürkészhetetlen uraik akaratát követve. Mindezen következtetéseket általában a hírhedt Anat-Akhan történetéből vonják le, amely nevezetes árulását megelőzően a jelentéktelenebb határvidéki klánok közé tartozott.

:fn-verivo: pass:c,q[footnote:[Used "_blood-guzzling_" instead of "_bloodthristy_", because it is closer to the meaning of the Hungarian original that literally means "_blood-drinker_".]]

:fn-atleta: pass:c,q[footnote:[The literal translation of the original text's "_szoborszép, atlétatermetű harcos_" phrase is "_athletically-built, statue-beautiful warriors_". This could have been massaged to sound more natural, but I deemed the results too "crowded".]]

:fn-rebesget: pass:c,q[footnote:[The Hungarian "_rebesget_" is very close in meaning to "_rumor_", but it is kind of archaic so decided to use "_bruit_". (https://www.shakespeareswords.com/Public/GlossaryHeadword.aspx?headwordId=2246[See some of its uses by Shakespeare.])]]

:fn-nevezetes: pass:c,q[footnote:[Chose "_remarkable_" over "_notable_" and "_momentous_". "_Notable_" sounds more like "_worthy of mention_", but this doesn't give too much credit for this act (especially if you know the true nature of Krán). "_Momentous_" however alludes to a nigh fundamentally significant event, which would be overselling it.]]

// TODO Setting the paragraphs below in italics until the epigraph is a hack; this is an introduction that should be wrapped in a semantically meaningful element (such as `<preface role="introduction">`; valid only for documents with document type "book", but not sure what to use for `<article>`s...), and define representation rules for that element (e.g., via CSS).

[#introduction]
_Numerous mendacious and mistaken rumours abound around Krán{fn-kran-reuse}'s headhunter clans all over the human-settled lands of Ynev. Some envisage blood-guzzling{fn-verivo} monsters who long cast the last shred of their humanity; others believe them to be statuesque warriors{fn-atleta} who are evil mostly out of habit, as dictated by the customs of their homeland. They are bruited{fn-rebesget} of having nothing else to do but to meddle with the affairs of the outside world, to squabble with adventurers and crowned heads, all in accordance with the wills of their inscrutable masters. The aforementioned conclusions are mostly drawn from the history of the notorious Anat-Akhan, one of the more insignificant clans of the borderlands before their remarkable{fn-nevezetes} act of treason._

// Valójában a kráni fejvadászokat roppant kevéssé érdekli mindaz, ami a birodalom határain kívül történik, és szerfelett ritka közöttük az olyan, aki külvilági mércével mérve szépnek volna nevezhető. Ami pedig azt a vádat illeti, hogy vérivó szörnyetegek lennének - nos, nem azok.

_In truth, events beyond the realms of the empire are of little interest to the headhunters of Krán{fn-kran-reuse}, and hardly any of them can be labeled as attractive by the standards of the outside world. As for the accusation of being beasts thriving on blood - well, they aren't._

// Amint az az alábbi elbeszélésből is kiderül: rosszabbak annál...

_As the account below will illustrate: they are worse..._

'''

[.epigraph]
"Lo! here is he whom in childhood I dedicated to my altars. This is he that once I made my darling. Him I led astray, him I beguiled; and from heaven I stole away his young heart to mine. Through me did he become idolatrous; and through me it was, by languishing desires, that he worshipped the worm, and prayed to the wormy grave. Holy was the grave to him; lovely was its darkness; saintly its corruption. Him, this young idolater, I have seasoned for thee, dear gentle Sister of Sighs! Do thou take him now to thy heart, and season him for our dreadful sister. And thou,”⁠—turning to the Mater Tenebrarum, she said⁠—“wicked sister, that temptest and hatest, do thou take him from her. See that thy sceptre lie heavy on his head. Suffer not woman and her tenderness to sit near him in his darkness. Banish the frailties of hope; wither the relenting of love; scorch the fountains of tears; curse him as only thou canst curse. So shall he be accomplished in the furnace; so shall he see the things that ought not to be seen, sights that are abominable, and secrets that are unutterable. So shall he read elder truths, sad truths, grand truths, fearful truths. So shall he rise again before he dies. And so shall our commission be accomplished which from God we had⁠—to plague his heart until we had unfolded the capacities of his spirit."
-- pass:q[<personname>Thomas de Quincey</personname>], https://standardebooks.org/ebooks/thomas-de-quincey/suspiria-de-profundis/text/single-page[Suspiria de Profundis]

:fn-PLACEHOLDER: pass:c,q[footnote:[]]
:fn-PLACEHOLDER: pass:c,q[footnote:[]]
:fn-PLACEHOLDER: pass:c,q[footnote:[]]
:fn-PLACEHOLDER: pass:c,q[footnote:[]]

ORIGINAL Nézd, íme itt van ő, akit már gyermekkorában oltárom papjává fogadtam. Ő az, aki kedvencem lett.  Félrevezettem és elámítottam őt, elloptam az égtől fiatal szívét - a magam számára. Én tettem őt bálványimádóvá, én tettem, hogy epedő vágyakozással imádja a férgeket, a sír férgeit odalent. Szent lett számára a sír; édes a sötétje; szent a rothadás a mélyén. Édes, drága nővérem, Sóhajok Anyja, neked neveltem ezt az ifjú bálványimádót. Szorítsd hát a szívedre, s te neveld tovább rettenetes nővérünk szolgálatára. Te pedig, romlást hozó testvére, te, aki csábítasz s gyűlölködsz, vedd magadhoz őt középső nővérünktől.  Hatalmad pálcáját nyugtasd fején. Ne engedj asszonyt soha közelébe, ne hagyd, hogy női gyengédség enyhítse körülötte a sötétet. Űzd el zsenge reményeit, hervaszd el számára a részvétet, a szerelmet, szárítsd ki könnyei forrását, sújtsd őt olyan átokkal, amilyennel csak te sújthatod. Így égjen ki belőle minden salak, így láthassa majd meg, ami nem arra való, hogy lássák, iszonyatos látványokban legyen része, titkokban, melyekről nem ejthet szót a száj. Hadd ismerjen meg ősi igazságokat, szomorú igazságokat, hatalmas igazságokat, félelmetes igazságokat. Hadd legyen még halála előtt része a feltámadásban. Így teljesítsük Istentől kapott feladatunkat. Gyötörjük szívét szüntelenül, hogy lehetőségeinek legvégső határáig csigázzuk szellemét.

Thomas de Quincey: Suspiria de profundis

TRANSLATION "Lo! here is he, whom in childhood I dedicated to my altars. This is he that once I made my darling. Him I led astray, him I beguiled, and from heaven I stole away his young heart to mine. Through me did he become idolatrous; and through me it was, by languishing desires, that he worshipped the worm, and prayed to the wormy grave. Holy was the grave to him; lovely was its darkness; saintly its corruption. Him, this young idolator, I have seasoned for thee, dear gentle Sister of Sighs! Do thou take him now to thy heart, and season him for our dreadful sister. And thou,"−turning to the Mater Tenebrarum, she said,−"wicked sister, that temptest and hatest, do thou take him from her. See that thy sceptre lie heavy on his head. Suffer not woman and her tenderness to sit near him in his darkness. Banish the frailties of hope, wither the relenting of love, scorch the fountains of tears, curse him as only thou canst curse. So shall he be accomplished in the furnace, so shall he see the things that ought not to be seen, sights that are abominable, and secrets that are unutterable. So shall he read elder truths, sad truths, grand truths, fearful truths. So shall he rise again before he dies. And so shall our commission be accomplished which from God we had,−to plague his heart until we had unfolded the capacities of his spirit."

Thomas de Quincey: Suspiria de profundis

NOTE Well, the "original" is actually the Hungarian translation of the English original, and the "translated" version is copied verbatim from the book. https://en.wikipedia.org/wiki/Suspiria_de_Profundis

QUESTION "−" <- What is this characther? Vim's `ga` command says
```text
<−> 8722, Hex 2212, Oct 21022, Digr -2
```
but I also would like to know what its literary purpose is, and how to use it properly.


START_PARAGRAPH

ORIGINAL Hideg szél süvített a láthatáron feketéllő bércek felől, ólomszín fellegeket kergetett az alacsony égbolton, s hűvösen szemerkélő esővel terítette be a rendház kőcsupasz udvarát.

TRANSLATION Cold wind skirled from the tenebrous crags on the horizon, rushing leaden clouds over the low-hanging heavens and covering the stone-bare courtyard of the chapterhouse with frigid drizzle.

NOTE (skirl) This was the closest to "süvít", and even though it is usually translated using "howl", I think "skirl" fits better here. Another option was "scream", but it sounded too "cheap".

NOTE (low-hanging heavens) This is a mirror translation of "alacsony égbolt", meaning that dark (usually storm) clouds seem ominously close to the observer. Surprisingly, this is a valid English phrase, used in many places. "Low-hanging" is usually used with "cloud(s)", but the latter needed to be mentioned already. (As for "leaden clouds", just do a quick google search, and the results will probably conform to your expectations to what the phrase evokes.)

NOTE (frigid) Simply didn't like to see "chilly" here, and all the other synonyms sounded less menacing.

NOTE (stone-bare) No such English adjective. It's a mirror-translation of "kőcsupasz", but I liked how it conveyed the empty (except for Vyergas), unwelcoming, stone-covered yard with no vegetation other than whatever could find a grip in the cracks.

ORIGINAL Vyergas egymaga állt a hatszögletűre csiszolt bazaltlapokon, tekintete a roppant kapuszárnyakat egybereteszelő gerendavason pihent. Byzonbőr csizmáján és durva daróctunikáján kívül csupán egy dísztelen, sötét köpönyeget viselt; a csuklya árnyékadó szövetét mélyen a homlokába húzta. A körülötte szitáló nedvesség átjárta öltözékét, nyirkos ujjakkal cirógatta végig a testét, egész a csontjáig hatolt. A rúnákkal vésett ezüstpók, mely nyolc vékony lábnyúlvánnyal gyökerezett üres szemgödrében, hidegnek és halottnak érzett; nyilalló sajgás állott tőle a bal arcába. Lehunyta jobb szemét - a másikat, az épet -, és mélyet lélegzett a csípős, tufaszagú levegőből. Vendégeink a kapu előtt várakoznak, vert visszhangot elméjében a comtur szava.

TRANSLATION Vyergas stood alone on the hexagon-cut basalt slabs, resting his eyes on the iron beam latched across the immense gates.

NOTE The phrase "latched across" may not be used proper, albeit sounds cool.

NOTE (beam) Supposedly, the correct term is ["draw bar"](https://forum.wordreference.com/threads/wooden-bolt.2594632/#post-13083864), but there is [a solid architectural difference between "bar" and "beam"](https://www.quora.com/What-is-the-difference-between-a-beam-and-a-bar) (see [this image](https://i.ytimg.com/vi/jURuwHdliYs/mqdefault.jpg) for help) - and "beam" sounded more awesome.

unadorned

END_PARAGRAPH

START_PARAGRAPH

Van idejük. Várhatnak.

END_PARAGRAPH

START_PARAGRAPH

Vyergas rövid tűnődés után hátravetette fejéről a kámzsát. Ez a tartomány nem szűkölködött olyan szerzetekben, akik jobbnak látták óvó lepel mögé rejteni vonásaikat; odakint, a barbár külvilágban talán riadalmat keltenének ezzel, itt azonban senki nem törődött velük. Vyergasnak nem volt szüksége a csuklya árnyékára hozzá, hogy félelmetes látványt nyújtson; darabos arcát forradások rútították, roppant állkapcsán acélszürke bozótként burjánzott az elvadult szakáll, a sajgó ezüstpók hátborzongató kontrasztot alkotott sárgán villogó jobb szemével.

END_PARAGRAPH

START_PARAGRAPH

Következő lépésként megoldotta a köpönyeg övét, és kétfelé csapta szárnyait. Azt akarta, hogy az érkezők lássák: nincs nála fegyver. Ezzel nem békés szándékát kívánta kimutatni; az ő mesterségében a békés szándék vétkes gyöngeség volt, vállalása kudarc, büntetése halál. Vyergas számára saját testvérein és nővérein kívül a világon mindenki ellenségnek számított; legfeljebb egyesekkel hamarabb kerül sor az összecsapásra, mint másokkal. Nem; ahogy mozdult, ahogy állt, ahogy viselte magát, azzal egészen más
céljai voltak.

END_PARAGRAPH

START_PARAGRAPH

Aki elég vakmerő ahhoz, hogy egymaga, fegyvertelenül, minden tiszteletadást mellőzve fogadja a Ly'Shematenel ház fiúörökösének látogatását, az vagy nagyon biztos lehet a dolgában; vagy nagyon ostoba. Vyergast utoljára tizenkét éves korában nézték ostobának, Rah Gul városában; a végzetes hibát egy tagbaszakadt, közismerten ferdehajlamú selyemfiú követte el. Utóbb rádöbbent tévedésére, ám ekkor már késő volt; a melléig sem érő rabszolgasuhanc, akit éjszakai szórakozásra szemelt ki magának, puszta kézzel tépte le mindkét heréjét. Vyergas tehát jó okkal feltételezhette, hogy a rendház vendégei nem együgyűséget, hanem öntudatos magabiztosságot fognak sejdíteni az arcátlanul merész fogadtatás mögött. Márpedig az efféle önbizalomnak többnyire olyan alapja van, amit jobb nem bolygatni, nehogy váratlan kellemetlenség kerekedjen belőle.

END_PARAGRAPH

START_PARAGRAPH

A zömök, szakállas férfi természetesen nem volt sem magányos, sem fegyvertelen, bármit is sugallt a látszat. A belső udvart körülvevő bazaltbástyák lőrései mögött felajzott íjú saggitorok rejtőztek, ferdén vágott szemük figyelmét a legapróbb változás, az árnyékok mégoly csekély átrendeződése sem kerülte el.  A kövezeten meggyűlő esővíz olajos ízét állábaikat nyújtogatva kóstolgatták a tócsák alján lapuló bannarák; csak a rend méregmesterének parancsoló igéjére vártak, hogy kiemelkedjenek rejtekhelyükről, s a betolakodókra vessék magukat. A Vyergas védelmére kirendelt három messor légies alakja az étkezőház első ablaksorának magasságában lebegett; ha úgy hozza a szükség, bármikor anyagiasulhatnak, s munkára foghatják páros pengéiket.

END_PARAGRAPH

START_PARAGRAPH

A comtur elegendőnek ítélt ennyi óvintézkedést, hiszen a rend - legalábbis pillanatnyilag - a barátai között tartotta számon a Ly'Shematenel házat.

END_PARAGRAPH

START_PARAGRAPH

Fáznak és éhesek. Csekély türelmű népség, bármilyen is a hírük; kezdenek dühösek lenni.

END_PARAGRAPH

START_PARAGRAPH

Vyergas sötéten elmosolyodott a comtur szavaira. Egyáltalán nem kedvelte a Hét Völgy és a Hét Domb Házait, bár a Birodalom kiismerhetetlenül kusza politikája időről időre szövetségbe kényszerítette velük a rendet. Egyszer, még sequator korában, követségbe küldték hozzájuk; sohasem feledte el a megaláztatásokat, melyek akkor a Könnyűléptű Nép részéről érték. S a vidék is, ahol szállásaikat tartották; túl fülledt volt Vyergas ízlésének, túl eleven. Önkéntelenül megborzongott, valahányszor a századéves feketetölgyek ágairól lógó nyirkos mohaleplek végigsúrolták a vállát, fejét; s bár nem mutatta, mindig észrevette a vendéglátói arcán átsuhanó gúnymosolyt. Most kurta hálaimát küldött a Kosfejes Úrhoz, amiért visszaadhatja nekik a kölcsönt; az ő fajtáját a Birodalom nem megbocsátásra, hanem megtorlásra nevelte.

END_PARAGRAPH

START_PARAGRAPH

Három órája váratod már őket odakint, dörrent tudatába a comtur szellemhangja. Elég legyen!

END_PARAGRAPH

START_PARAGRAPH

A zömök férfi összerezzent, engedelmesen meghajtotta fejét. Ra urdath san uthmor ahen; aggun hara'het shaka'thorr, küldte gondolatban comturja felé az ősi -kiengesztelő formulát. Vérem és velőm a tiéd; tégy vele belátásod szerint!

END_PARAGRAPH

START_PARAGRAPH

Válasz nem jött; tehát hibája ellenére érdemesnek találtatott rá, hogy tovább éljen. Vyergas hálás volt ezért a mesterének; nem mintha egy pillanatig is habozott volna, ha utasítást kap tőle a szertartásos torokmetszésre, de égette a kíváncsiság, vajon mi vehette rá a Könnyűléptű Népet, hogy feladják gőgös elzárkózásukat. Ezen a kérdésen tűnődött immáron harmadik órája; s mert gondolatait abban a kényelmes, nyugodt iramban öltötte egymásba, amelyet szántóvető őseitől kapott örökül, a vélhető választól még mindig messze járt. Időre volt szüksége, legalább egy kevésre még. Nem baj. Megoldható.

END_PARAGRAPH

START_PARAGRAPH

Teleszívta tüdejét a bazaltköves udvar hűs levegőjével. A szemerkélő eső mindent átható illatába más, haloványabb, nehezen meghatározható szagok keveredtek. Vyergas gondosan szétválogatta és osztályozta őket. Füst. Tufa. Veríték. Ázott bőr.: Spórákat vedlő nyirokmoha. Az étkezőház homlokzata felől áporodott, hideg rothadás.

END_PARAGRAPH

START_PARAGRAPH

Az idő folyása lomha-fáradttá vált, elbizonytalanodott. A levegőben porló esősziporkák álomszerű lassúsággal lebegtek a bazaltlapok felé. Tompa; elnyújtott, pincemély gongszó vert kongó ekhókat Vyergas fülében: a szíve dobbanása.

END_PARAGRAPH

START_PARAGRAPH

Elégedetten tért vissza gondolataihoz.

END_PARAGRAPH
END_SECTION

START_SECTION
START_PARAGRAPH

Nem túl gyakran fordult elő, hogy a Könnyűléptű Nép szófukar, zárkózott harcosai - ellenségeik, akik többnyire korai halált haltak, Ranagol erdészeinek és lovászainak csúfolták őket - kívülállók segítségét kérjék ügyes-bajos dolgaikban. Ha nehézségeik támadtak, általában maguk is elboldogultak velük; a Szabad Rendeket mélységesen lenézték, kérészéletű korcsok bárgyú szervezkedésének tartották, s büszkeségük még akkor sem engedte meg nekik az idegenekkel való szövetkezést, ha az életük forgott kockán.

END_PARAGRAPH

START_PARAGRAPH

Vyergas egyetlen olyan okot tudott elképzelni, ami esetleg rábírhatja a Ly'Shematenel házat, hogy az ő támogatásukat keresse: a Könnyűléptű Népnek az Ősök egyikével támadt viszálya. Öregségtől megrokkant, köszvény-sorvasztotta mentora szerint - húsz esztendeje sírjában pihen már - ez a két faj már évtízezredekkel azelőtt gyilkos háborúkat vívott egymással, hogy Krán földjét először emberi láb illette volna. Az Ősök - okította a növendékeket a reszketeg aggastyán, aki valaha, sötétebb és véresebb időkben, életek kioltója és sebek osztogatója volt -, igen, az Ősök vénebbek a Tizenhármaknál, talán még magánál a Kosfejes Úrnál is; ami pedig a Hét Völgy és a Hét Domb Házait illeti, ők csaknem egykorúak velük. A végzet különös fintora, hogy végül, annyi öldöklés és gyűlölet után, a két esküdt ellenség egyazon táborba kényszerült. Igaz, rebesgetik, hogy valahol a Birodalmon kívül a Könnyűléptű Népnek élnek olyan rokonai is, akik nem ismerik el a Tizenhármak főségét, és elutasítják a Kosfejes Úr kegyeit; ez azonban minden bizonnyal üres szóbeszéd, hiszen a legostobább nayan is tudja; hogy a Birodalom határain túl mindenütt a legsötétebb káosz és barbárság uralkodik. Vyergas úgy hallotta, már a Külső Tartományok is épp elég vadak és civilizálatlanok. Saját tapasztalatból nem meríthetett; sokfelé megfordult már vadászatai során, rendbéli testvérei világlátott embernek tartották, ám Fray-Grimonarnál messzebb sohasem vetődött - és se teste, se lelke nem kívánta még egyszer átélni az ott tapasztaltakat.

END_PARAGRAPH

START_PARAGRAPH

Az Ősök... Ha a Ly'Shematenel ház valóban velük akaszkodott össze, gazdagon meg kell adnia a rendnek a segítség árát, vérben és vasban, fában és fémben, húsban és halálban. Vyergas nem volt bolond, nyitott szemmel járt a világban. A Birodalmat elvben a Tizenhármak kormányozzák, a Kosfejes Úr földre szállott helytartóiként: ők nevezik ki a tartományok élére a consularokat; ők hajtják be atyjuk rendelésére az évszakonkénti haláladót; ők hirdetik ki s igazítják a változó időkhöz a hitszegést s a becstelenséget büntető vértörvényeket; ők veszik fel a harcot a határokon túlról olykor-olykor betörő barbár hordákkal; és utána persze ők vezetnek megtorló hadjáratokat a külvilági vadak primitív törzsei ellen. Rangjukat, előjogaikat senki nem vitatja; csakhogy; amint azt az öreg mentor mondotta volt, az Ősök vénebbek náluk. Amikor a Tizenhármak megérkeztek Kránba, őket már itt találták. Egyesek közülük fejet hajtottak és behódoltak; mások ellenszegültek a Kosfejes Úr akaratának, s istenkáromló vakmerőségükért elnyerték méltó büntetésüket: Olyanok is akadtak azonban - s hozzá nem is kevesen -, akik tudomást sem vettek a Tizenhármak jöveteléről, a Birodalom megalapításáról. A Kosfejes Úr szent szózatát megértették és lelkükbe fogadták, hívéül szegődtek és véráldozattal tisztelegtek neki; gyermekeivel azonban nem törődtek, mert legalább olyan hatalmasok voltak, mint ők, ha ugyan nem hatalmasabbak. Ranagol Égi Honában otthonra lelnek majd ezek az Ősök is, mert vallják és hirdetik az egy igaz hitet; ám földi birodalmán kívül maradtak, megőrizték saját törvényeiket, szokásaikat, s mindenben a maguk akarata vezérli őket. Viselt dolgaikba még a Tizenhármak is óvakodnak beleszólni, a consularok parancsa pedig annyit számít csupán nekik, mint szélviharnak az ellenébe szegülő szalmaszál.

END_PARAGRAPH

START_PARAGRAPH

Meglehet, hogy a Könnyűléptű Népnek e hatalmak valamelyikével támadt összetűzése; vagy ami
még valószínűbb, felújítottak egy ezredévek óta lappangó viszályt. A Ly'Shematenel ház ereje persze nem
mérhető az Ősökéhez, ám az a törzsök, amiből az ő fajtájuk sarjadt; nem annyira vén még, hajtásai
frissebbek és számosabbak. Ők sokan vannak, s társakat és szövetségeseket kereshetnek maguknak a
Birodalom többi alattvalója között; az Ősök ezzel szemben magányos remeték, szinte minden
kapcsolatukat elvesztették a halandó világgal. Konokul kapaszkodnak az életbe, noha rég belefáradtak
már; lelkük sötétbe borult és megkeseredett a végtelenbe nyúló korszakok során. Ráadásul ősrégi
sérelmek és vérbosszúk osztják meg őket, még a Birodalom alapítását megelőző időkből. Gyilkos
háborúkat viselnek egymás ellen, akárcsak a Szabad Rendek, a Káosz-szekták vagy a Könnyűléptű Nép
nemesi házai; csak éppen bennük túlságosan mélyen fészkel a gyűlölet fekélye, egyetlen percre sem
képesek megfeledkezni róla, hogy szövetségre lépjenek valami külső veszedelemmel szemben. Így aztán
számuk évszázadról évszázadra apad; idővel mind kirostálódik majd az ocsú, s csupán a legkülönbek és
legnemesebbek maradnak meg közülük, az egyetlen igaz istenség, minden szférák és síkok fejedelme, a
Kosfejes Nagyúr akarata szerint.
Ki lehet az vajon, aki ellen á Ly'Shematenel ház szövetségeseket toboroz? Vyergas a homlokát
ráncolta, ahogy megpróbálta felidézni magában mindazt, amit az Ősök nagyjairól és vezéreiről tanult.
Lelki szeme előtt megképzett a bazalttal kövezett refektórium, ahol növendék korában az ősz mentor
hajnalokba nyúló előadásait hallgatta. Tisztán látta a hajlott hátú, köszvényes öregembert, amint botjára
támaszkodva fel-alá sétál a félhomályos teremben; lépteiben még föl-fölrémlik néhány futó pillanatra a
hajdanvolt fürgeség emlékezete. Baloldalán a zöld foszforral felvázolt pentagramma, amit a
növendékeknek egyelőre tilalmas öt lépésnél jobban megközelíteni, kézlevágás terhe mellett; jobboldalán
a kosfejes oltárkő, amin mindennap pontban Éjközépkor könyörgő emberáldozatot mutatnak be a
Hatalmas Ranagolnak, hogy világosítsa meg a választott ifjak elméjét, s keményítse meg szívüket az
esendőség gonosz kísértésével szemben. Az ötvenedik évét taposó aggastyán eleven legenda volt
számukra, az Árnyfivérekkel és az Ahan 'NataKhannal vívott győztes háborúk bálványozott hőse.
Reszketeg, el-elcsukló hangon beszélt; alig három hónapja volt már hátra akkor az életből. Ám szavaiban
mégis a hatalom delejes dallama vibrált, ahogy sorra néven nevezte az Ősök legfélelmetesebbjeit. A
Csontlovagot, Káosz-Metha kegyeltjét, aki élettel büntet és halállal kegyelmez; a Vakon Látót, aki a
külvilágban vándorol, s egy kései és korcs istenség ivadékának adja ki magát; a Könnytelen Öreget,
Sramsass-Daqkín fejedelmét, akinek oltára a Feneketlen Kút, s varázserővel ruházza föl mindazon apák
gyermekeit, akik öngyilkosok lesznek a tiszteletére; a Leples Asszonyt, akit a Kosfejes Úr párjául
választott egy időre, s ő Krilehort és Uroyahaast szülte neki; a Suttogót, aki százezer éve alszik a hegyek
gyökerénél, s álmában a sötétség szellemével beszélget; a Sápadt Angyalt, aki jótétáldásával ajándékozza
meg a halvaszületett kisdedeket; a Ködbenézőt, aki elorozza a halandók lelkét, s helyette lidérc-szívet
fuvall a kebelükbe; az Akasztott Királyt; a Fekete Forrás őrét, akinek hideg cirógatása meddővé
szikkasztja a nőket, magtalanná a férfiakat; az Opálhajóst, aki az óidőkben lebűvölte az égről a harmadik
holdat; a Lánggal Égő Szüzet; akinek mosolya szerelemre gyújtja a démonok szívét; csókjától pedig
mennyei gyönyörök közepette szenvednek ki minden nép s faj hímjei; a Fények Kioltóját, akit Ranagol
maga mellé emelt az Égi Honba, s azóta Káosz-Buulzaab néven hódolnak neki...
Vyergas sokat tudott az Ősökről, lényegesen többet, mint Kránban a közemberek. Ennek persze jó
oka volt, hiszen a tudás hatalom; s drágán megszerzett hatalmát senki nem osztja meg szívesen másokkal.
Ámde Vyergas maga is az Ősök sokadízigleni ivadéka volt; persze nem azoké, akiknek a nevét áhítattal
ízlelgette annak idején a refektórium félhomályában, hanem egy náluknál csekélyebb, rég feledésbe
merült vérvonalé. Családfáját - akárcsak a Birodalom legtöbb közrendűnek született alattvalója - ő sem
tudta három nemzedéknél messzebbre visszavezetni; az emlékezet gyarló jószág, s a szolgasorban
sínylődő milliók leszármazását senki nem véli érdemesnek számon tartani. Pedig ez a fáradság is
kifizetődik olykor; Vyergas például egyszerű szántóvetők gyermeke volt, a kilencedik vagy a tizedik,
pontosan már ő maga sem emlékezett rá. Hosszú éveken keresztül tengődött szüleivel és testvéreivel az
éhhalál szélén; arcuk verejtékével öntözték a rossz, savanyú földet, hogy kicsikarják belőle azt a kevéske
termést, ami - a helytartói dézsma lerovása után - olykor elegendő volt a sok éhes száj táplálására, ám
legtöbbször nem. A testvérei közül egyesek éhen pusztultak, másokat kisorsoltak a birodalmi haláladóba;
az apjának lobot kapott a tüdeje egy különösen hideg, esős őszi aratáskor; az anyját a gyermekágyi láz
vitte el, miután megszülte legfiatalabb húgát, egy vízfejű, idióta kislányt, aki maga is csak három napot
élt. Aztán a család maradéka odaveszett egy helyi klánháborúban, amely csaknem az egész tartományt
romlásba döntötte; a zűrzavaron úrrá lenni nem tudó consularnak, miután méltatlannak bizonyult a
Kosfejes Úr bizalmára, a Tizenhármak kegyesen engedélyezték az önkéntes máglyahalált.
Vyergas azonban életben maradt, mert vad volt és szívós, akár a hegyi görény. Kilencévesen
gyilkolt először, a Mal Vatchlak mocsarakban bujdokolva, élelemért; kannibállá később, a győztes klán
fogolytáborában vált, ugyanezen okból. Innen egy kőfejtőbe került, ahol csakhamar kiemelték a többiek
közül, mert bestiális dührohamában átharapta az egyik felvigyázó torkát, aki kétszerte nagyobb volt nála.
Rah Gul városában egy gazdag lanista - független vállalkozó, aki hivatásos viadorokból álló
rabszolgaistállót tart fenn - ígéretes növendéket látott a vad suhancban, s jelentős összeget fektetett
megvásárlásába és fegyveres kiképzésébe. Vyergas azonban sohasem lépett az aréna porondjára; az újonc
viadorokat ugyanis nemcsak a fizetőközönség kiváltságosai szemrevételezték, hanem más, sokkal
céltudatosabb személyek is, akiket csöppet sem érdekeltek a tétösszegek és az esélyarányok. Káosz-Vulak
havának egy kellemesen langyos estéjén alacsony, mosolygós, keskeny vállú idegen kereste föl házában a
lanistát, és felmutatott neki egy bizonyos pecsétet. A házigazda elkövette azt a hibát, hogy pénzt és
kárpótlást emlegetett; másnap holtan találták a vízipipa-szobájában, a segítségére siető öt testőr-viadorral
együtt. Vyergas virradatra már félnapi járóföldre volt Rah Gultól, és nem is látta viszont a várost, csak
tizennyolc esztendővel később, egyetlen kurta éjszakára. Ekkor már morteli rangot viselt, s rövidre fogta
látogatását; csupán néhány percre tért be egy túlságosan beszédes démonidéző palotájába, aki úgy vélte,
elég hatalmas hozzá, hogy eleressze a füle mellett egy tekintélyes szervezet jószándékú figyelmeztetéseit.
Származásának titka őt magát lepte meg leginkább; álmában sem jutott volna eszébe a gondolat,
hogy valamikor rég, a múlt homályba vesző messzeségében, akadt valaki az ősei között, aki ahhoz ugyan
eléggé emberi volt, hogy életképes utódot nemzzen egy halandó asszonynak, ahhoz azonban már túlságosan idegen, hogy kései leszármazottai a szó szűkebb értelmében vett embernek legyenek tekinthetők. A
Vyergashoz hasonlók legtöbbje részben vagy egészben anyai ágról örökölte az ősi vért, ezért képességeik
csekélyebbek voltak, hatalmuk korlátozottabb. Az ő esetében azonban úgy tűnt, a titkos örökség
megszakítatlanul szállt apáról fiúra, kisiklások és elágazások nélkül, csaknem háromszáz nemzedéken át.
Az asszonyoknak mindvégig csak a befogadó s a továbbadó szerepe jutott; egyetlenegyszer sem fordult
elő, hogy ne legyen a családban legalább egy fiúgyermek, aki töretlenül továbbviszi az ősi vérvonalat.
Páratlan véletlen volt ez, már-már a csodával határos; ha védettebb, rendezettebb életet él, a
tartományokat járó fürkészek hamarabb felfigyelnek rá, s minden bizonnyal háború tört volna ki
birtoklásáért a vadásztestvériségek között. A mosolygós, keskeny vállú férfi, aki elrabolta Rah Gulból, a
Fekete Özvegy Rend - ősi nevükön a Khat'ul'Naathum - szerződéses toborzója volt; még csak nem is
teljés jogú testvér, ám ahhoz bőven elegendő, hogy elbánjon a lanistával és öt viadorával. Mindezt persze
Vyergas csupán jóval később tudta meg; a bizalmat, a beavatást előbb ki kellett érdemelnie, a rend titkos
nevét pedig -melyet kizárólag bizonyos ősrégi rítusok elvégzése után, a legnagyobb elővigyázatosság
mellett volt szabad fennhangon kiejteni - csak tíz év múlva árulták el neki.
Kezdetben hitte is, nem is, amit a származásáról mondtak neki. Gyorsan és fájdalmasan tanulta meg,
hogy a teljes rangú testvérek szavát nem vonhatja kétségbe; ám a néma kételkedés jogát nem vehették el
tőle, az ott fészkelt benne kiirthatatlanul, a kegyetlen, küzdelmes gyermekévek hagyatékaként. Végül a
kézzelfogható bizonyítékok győzték meg fokról fokra, apródonként. Sikerült megtanulnia az Ősök
nyelvét, bár csak a legromlottabb, alsóbbrendű dialektust, és azt is iszonyú gyötrelmek árán.
Növendéktársainak zöme még eddig sem jutott; a szavak égették a torkukat, marták a nyelvüket, görcsbe
rántották a beleiket.
A bölcsebbek hamar belátták, hogy hiába is próbálkoznának, és idejében felhagytak a hasztalan
küszködéssel. Másoknak későn jött a felismerés: ezek borzalmas kínok között pusztultak el. A
legtöbbjükkel szívroham végzett, de akadtak páran, akiknek az agyukban pattantak meg az erek. Annak a
lánynak, aki először osztotta meg az ágyát Vyergasszal, egy szép napon orrán-száján dőlni kezdett a vér,
és a rend boncmesterének minden tudománya kevésnek bizonyult az elállításához.
Harminckét újoncból öten birkóztak meg a nyelvvel; tizennégyen belehaltak, a többi feladta. A vén
mentor elégedett volt az eredménnyel; rosszabb arányra számított. Valamennyi növendékének az ereiben
folyt egy kevés az Ősök véréből, ám csak ebben az ötben elég sűrűn ahhoz, hogy keserves munkával
újratanulják, amit távoli elődeik elfelejtettek. A beszéd persze nekik is fájt; Vyergas a kínok kínját állta ki
minden egyes szó kiejtésekor, s a teljes mondatokig sohasem jutott el. Mégis folyton-folyvást gyötörte,
űzte, hajtotta magát, olykor végkimerülésig vagy éppen ájulásig. Mért az Ősök nyelvében pusztító, zabolátlan erők rejlettek, a világ sarjúkorának szunnyadó energiái. Hatalomigéi ellen nem volt védekezés, szökőárként sodorták el a mentális gátakat, pálcikaként roppantották össze a mágikus védműveket. Menekülésre, netán szembeszegülésre csak azok gondolhattak, akik maguk is az Ősökig vezethették vissza a
származásukat.
Ezért szomjazta Vyergas oly csillapíthatatlan mohósággal az elfeledett tudományt. Sihederkora
keserű leckéiből korán megtanulta, hogy az egyetlen egyetemleges érték a hatalom, mivel minden
körülményék között magában hordozza saját önigazolását. A Kosfejes Úr tanítása volt ez, képmutatástól
mentes, bölcsen belátó. Vyergasnak, a bujdosónak, a rabszolgának, az arénába szánt viadornak sem
papokra, sem szent könyvekre nem volt szüksége hozzá, hogy elfogadja és magáévá tegye.
Ötük közül ő volt a legjobb, s ezt kezdettől fogva éreztette a másik néggyel. Társai hígabb vért
örököltek messzi elődeiktől, többet kínlódtak az Ősi Nyelv szavaival, keményebben megszenvedtek
minden egyes hatalomigéért. Egyikük meg is rekedt a vásári szemfényvesztők szintjén, olcsó
bűvészmutatványokból állt az egész tudománya; egy másik túlerőltette magát az első küldetésén, s
bevérzett a tüdeje, mielőtt végezhetett volna a kijelölt személlyel. Az új mentor számára szörnyű
csalódást jelentett a kudarca; nevét kihúzták a rend évkönyveiből, fegyvereit összetörve a Sel sebes
vizébe dobták, emlékezetét örök időkre eltörölték.
Így hát végül hárman maradtak, akik becsülettel letudták sequatorként az előírásos tíz évet, majd
felvételt nyertek a rend következő fokozatába, a rettegett hírű mortelek kiváltságos sorai közé.
Megbízatás megbízatást követett; szövetségek köttettek; ármányok szövődtek; az árulás mételyét is
megtapasztalták néhányszor, egy ízben a renden belülről nyújtotta ki feléjük mérgező csápjait. Az idősebb
testvérek sorra kidőltek mellőlük - kivel fegyver végzett, kivel méreg, kivel a tulajdon mágiája -, vagy
előreléptek a legrangosabb kasztba, a comturokéba. Végigharcoltak három vadászháborút, kettőt
megnyertek, egyet elvesztettek. Boszorkányszövetségekkel, Káosz-szektákkal, titkos méregkeverő
társaságokkal viszálykodtak, s a Kosfejes Úr gyakrabban mosolygott rájuk, mint ellenségeikre.
Meggyilkoltak temérdek birodalmi hivatalnokot és két consulart; felprédáltak néhány tartományt;
magukra vonták, majd másra terelték a félelmetes Shien-Gorr klán haragját. Ahogy erejükből tellett,
igyekeztek Ranagol tanításai szerint élni; s ha meg is botlottak olykor, nem váltak szégyenére istenüknek.
Vyergas túlélte hajdani növendéktársait - egyikük a Holdralépőkkel vívott háborúban esett el, a
másikkal egy bannara-mester eleven mérge végzett -, s idővel ő lett a rangidős a mortelek között. Az évek
felette sem múltak el nyomtalanul; haja, szakálla megszürkült, viharvert arcán megszaporodtak a ráncok,
szívét egyre jobban megviselték a nap mint nap szedett ajzószerek. A szemét az Ősök Tudománya miatt
vesztette el; az egyik vadászháborúban egy magafajtával került szembe, fáradtan és sebes torokkal, míg a
másik friss volt és kipihent. Nem maradt más választása: hogy elháríthassa az ellenséges hatalomigét, a
végsőkig ki kellett zsigerelnie szervezete rejtett tartalékait. Ám ezt a sérülését nem szégyellte,, épp
ellenkezőleg: a maga mogorva módján büszke volt rá. Az ezüstpók, amit a rend boncmestere az arcába
ültetett, az Ősök kezétől származó talizmán volt, bűvös hatalmú ereklye. Amikor meggyökerezett lábaival
az eleven húsban, lassan ölő nyálkamérget bocsátott gazdája testszöveteibe, amely minden közönséges
halandóval hetek alatt menthetetlenül végzett volna. Vyergas belázasodott, és ágynak esett; néhány nap
múlva azonban felépült a sorvasztó kórságból, s szervezete nem vetette ki a rúnadíszes talizmánt, nem
látott benne fertőzőgócot, mérgező fekélyt. Ékesszóló bizonyíték volt ez, hogy Vyergas ereiben a hosszú
évtizedek alatt sem hígult meg az ősi vér, még most is ugyanolyan sűrűn és szilajon lüktet, mint hajdan,
ifjúkorában.
Itt az ideje; hogy ismét próbát tegyen vele, gondolta tűnődve, s hagyta kiröppenni elméje
szorításából az ólomlábon vánszorgó pillanatokat.
A béklyójából szabaduló idő úgy zúdult vissza a számára kijelölt mederbe, mint a harsogó-zúgó
hegyi folyók a tavaszi olvadáskor. Az esőcseppek tízezernyi gyorsan tovaenyésző -tűszúrással söpörtek
végig az udvar fekete kövezetén. Valahonnan a távolból mennydörgés robajlott.
Vyergas lassan felemelte a fejét; arcában jobbfelől sárga láng lobbant, balfelől ezüstfény szikrázott.
A zömök férfi megfontolt mozdulattal kiegyenesedett, felemás tekintetét a kapura szegezte. Aztán
elmormolt egy kurta szót, mely hólyagheges rozsdaként marta végig a torkát, s hullámokat vetett a rejtett
síkokon. Az emberderéknyi gerendavas csengve kettétörött, acélsorjával vegyes szikrák röpködtek a levegőben. A kapuszárnyak kísérteties némasággal kitárulták, fölfedvén az odakint várakozók előtt a bazaltlapokkal kövezett udvart, a koponyadíszes kávájú kutat, az étkezőházat a homlokzatára szegezett trófeákkal, s a hatszögletű öregtornyot, a comtur szálláshelyét; melyet magányos lakója immár nem hagyhat el
soha.
Vyergas birokra kelt a zsigereibe hasító hirtelen fájdalommal, s farkasmódra elvigyorodott. Talán
felelőtlenség volt tőle; hogy mágiával nyitotta ki a rendház kapuját; de a gerendavasat nem lesz nehéz
pótolni, és tudta jól, mennyire irtózik a Könnyűléptű Nép az
Ősök Tudományától. Azok lévén, akik, nincsen védelmük ellene; bármilyen dölyfösek hát
egyébként, a hatalomigék szavára elbizonytalanodnak és megfélemlednek. A comtur hallgatása néma
helyeslést jelentett; ezek szerint ő sem bánja, ha ráijesztenek kissé a jövevényekre.
A magányosan álló alak közönyös maszkba rendezte vonásait, csak befelé üvöltött kínjában,
hangtalanul és észrevétlenül. Szíve vadul, rendszertelenül kalapált, ki-kihagyta az ütemeket. Az Ősök
Tudománya nem embereknek való; torkot tép, tüdőt marcangol, beleket szaggat. Vyergas egyszer már
túlerőltette magát a hatalomigékkel; akkor száradt ki a bal szeme. Körülbelül még tíz éve van hátra, aztán
olyanná lesz, mint a comtur; utána még egy-két évre számíthat, míg a Kosfejes Úr a színe elé nem
szólítja. Ez összesen negyvenhárom esztendőt jelentett, lényegesen többet, mint amennyit Kránban az
emberek zöme megér - de Vyergas tudta, hogy nem fog ilyen sokáig élni. Erőszakos halála lesz, az Ősök
egyike végez majd vele; ezt egy kóbor yecharr jósolta meg neki, Káosz-Huvarhg őrült prófétája, aki
jövendölésekkel fizetett a rend szolgálataiért.
Ne fürkésszük a jövőt, tartják a bölcsek; mit tenni s látni fogunk, mindig a jelenben gyökerezik.
Vyergas kivetette gondolatai közül a jósigéket, amiket a yecharr nyálfröcskös ajkáról hallott egykoron; s
figyelmét a kapun befelé poroszkáló lovasokra fordította.
Tizenhárman voltak, a békés követjáráskor szokásos számban, s tartásukon, szemük villanásán
látszott, hogy valamennyien elsőrangú harcosok. Kurta lovasíjuk nemeztokját köpönyegük szárnyával
takarták, nehogy a szemerkélő esőtől megereszkedjen az ideg. Hátukra vetve hosszúkás tegez, benne
harci színekkel feltollazott nyílvesszők; egyik kezük a kantárszárat tartotta, a másik könnyedén pihent a
nyeregkápán vagy az ívesen hajló hiequar markolatán. Hosszú, selymes hajukat szénköves homlokpánttal
fogatták hátra; néhányan közülük szoros varkocsba kötötték, mások halott ellenségek fejéről lemetszett
trófeatincseket fontak belé. Finom vonású arcukon megannyi tarka tetoválás: rőt sárkánykígyók, ezüstkék
oroszlánok, azúr griffmadarak. Porosak és csapzottak voltak mind, zöld-arany tunikájuk esővíztől ázottan
tapadt hátukra, mellkasukra; ám ha valóban bosszankodtak a hosszas várakozás miatt, ahogy a comtur
mondotta, arcizmuk rándulásával sem adták jelét.
A legelöl lovagló karcsú férfi még fiatalnak számított, ha a Könnyűléptű Nép mércéjével mérjük az
éveket; legfeljebb háromannyi telet láthatott, mint Vyergas. Tunikája fölött gyöngyökkel gazdagon kivarrott zekét viselt, puhára cserzett emberbőrből; nyilván finom sértésnek szánta, a kérészéletűek iránt érzett megvetését mutatta ki vele. A színpompás tetoválások az arcán halott ellenfelekről, győztes csatákról
regéltek; amott az ágaskodó kobra harcban elragadott vezéri zászlót jelentett, mellette a törött kard
húszévi gyilkos viszályt lezáró diadalt. Vyergas úgy olvasott ezekben az ábrákban, akár a nyitott
könyvben. A Középső Tartományok családjai közül több mint három tucatnak ismerte a titkos
krónikásjeleit. Csak egy képet nem tudott hová tenni a látogató homlokán: a lángoló szívet, amit fekete
vasbilincs zárt körül. Nemrég készíthették, még gyulladt pírral égett körülötte a bőr.
Az elf megállította előtte a lovát, és lenézett rá a nyereg magasából.
- Líthas, fakóvérű! - köszöntötte csengő, dallamos hangon. Jégkék szeme rezzenetlen maradt; a
Könnyűléptű Nép a fagyökerek alatt tenyésző férgeket nevezte fakóvérűeknek; a tenyérnyi, vak ászkákat,
a gerinc nélkül gyűrűző ázalagokat.
Vyergas úgy döntött, elengedi a füle mellett a sértést.
- Kalíthas! - morogta kurtán, és oldalt hajtotta szakállas fejét. A húsában gyökerező ezüstpókon
keresztül tisztán látta a lovas körül vibráló asztrálaurákat. Bíbor gőg; sárszínű undor; rőtvörös harag; és
igen valahol mélyen, titkosan a félelem szürkén szitáló hamuja.
- Aurri Ly'Shematenel vagyok, az Ötödik Domb Házából - jelentette be az elf azt, ami az arcát
díszítő tetoválásokból úgyis nyilvánvaló volt már Vyergas számára. - Elsőszülött és zászlóhordozó. Azért
jöttem, hogy kardokat fogadjak, comtur.
- Primortel - helyesbített a zömök férfi.
Az elf ajkára keskeny mosoly ült ki; kérdőn felvonta fél szemöldökét.
- Gyilkos?
- A jobbak közül való.
Csend támadt, csak a hűvös eső szemerkélt tovább, halk szóval, fáradhatatlanul. Aurri, az
elsőszülött hátranézett a kísérőire, rosszallón megcsóválta fejét, majd visszafordult. A mosoly közben
egyetlen pillanatra sem hervadt le az arcáról.
- Nem lesz ez így jó - mondta végül. - A gazdával van beszédem, nem a csahos kutyájával.
Vyergas egykedvűen vállat vont.
- A comtur az én szememmel lát, az én fülemmel hall, az én számmal szól. Ha mégis találkozni
kívánsz vele, kövess; de nem lesz benne sok örömed.
- Örülni odahaza szoktam - felelte az elf. - Yrch-tanyákon megelégszem a puszta szemlélődéssel.
Megint egy sértés, ugyanolyan finom szövésű, mint az előző. Az yrch szó az elf nyelv egyik ősi dialektusában harcost jelentett; manapság azonban már csak a Tizenhármak szolgáinak legmocskosabbjait és legalantasabbjait, a Külső Tartományok gyepűit őrző orkokat illették ezzel a névvel.
Vyergas ezúttal viszonozta Aurri mosolyát. Hegyesre köszörült ragadozófogai voltak, az alvást
távoztató shugaru-dió folytonos rágása szalmasárgára festette őket; négy szemfogába méregcsatornákat
fúrt a rend boncmestere.
- A szemlélődés hasznos foglalatosság; ha sokat gyakorolja valaki; idővel megtanul féket vetni a
nyelvére mások otthonában.
Hosszú csontú ujjak rebbentek közelebb a derékszíjakon lógó hiequarok markolatához. Egy hátasló
felhorkant; fújtatni kezdett. A szemgödörben sajgó ezüstpók rőtvörösen lobbanó lángokat látott az elf
alakja körül; alóluk kivillant a másik szín, a szürke, a ködként párálló félelem. Szívdobbanásnyi időbe telt
csupán, s semmivé sápadtmind a kettő; elnyomta őket az egész aurán eluralkodó, sáfránysárga undor.
- Követlek - mondta Aurri szárazon; már nem mosolygott. - A harcosaim itt maradnak, hisz baráti
hajlékban járunk, ahol senki nem oly ostoba, hogy fegyverrel fenyegetőzzék.
Vyergas gúnyosan meghajolt; s invitáló mozdulatot tett az öregtorony sötéten ásító kaputorka felé.
- Nincs mitől félniük, nemes elsőszülött - biztosította a látogatót negédes hangon. - De azért, ha a
helyükben lennék, a lovakat nem itatnám meg a kútból.
Az elf nem méltatta válaszra; átlendítette lábát hátasa farán, szarvasbőr csizmatalpa alól legyezőben
fröccsent föl az olajos esővíz. Kísérői közelebb húzódtak egymáshoz, körkörös alakzatot vettek fel,
mintha véletlenül verődnének össze. Egyikük elkapta a vezérük által feléje lökött kantárszárat; bal kezét
eltakarta a zöld-arany köpönyeg, Vyergas gyakorlott fülének figyelmét azonban nem kerülte el a halk
pendülés, ahogy hüvelykujjával lopva ellenőrizte az íjhúr feszességét.
- Mehetünk - jelentette ki Aurri hűvösen.
A primortel szolgálatkészen megindult előtte az öregtorony felé; közben nem mulasztott el a
dísztelenzömök étkezőházra bökni, melynek szögletes homlokzatán ernyedt, bordahíjas alakok áztak az
esőben, rég halott kínok görcsös emlékeibe merevedve.
- Csak a legvitézebb ellenségeink részesülnek abban a megtiszteltetésben, hogy szállásunk
tekintélyét emelhetik, s eledelül szolgálhatnak Káosz-Huvarhg szent madarainak - mondta. - Ősi
hagyományunk ez; lehűti a forrófejűek vérét, s épülésére van a heves fiataloknak.
Aurri megfontoltan bólintott; finoman ízelt ujjai az emberbőr zekére varrott gyöngyfonatokkal
babráltak.
- Mi az Ötödik Domb legvénebb feketetölgyeire szoktuk akasztani azokat a békebontókat, akik elég
balgák hozzá, hogy haragra gerjesszék népünket felelte. - Tanulságos látvány, primortel; meg kellene
tekintened egyszer.
A bélletes kapuzat visszhangos árnyékíve rájuk borult, magába nyelte őket. Vyergas kitapintotta a
titkos falifülke hármas nyitópeckét, s gyors mozdulattal lenyomta előbb kétszer az első, majd egyszer a
harmadik fogantyút. Benyúlt a rejtekhelyre, gyantás végű fáklyát vett elő a mélyéről, aztán
visszakattintotta a zárólapot.
- Ne fáradj a fénnyel; én elboldogulok anélkül is, neked meg úgysincs szükséged rá, hisz jól ismered
az utat - mondta az elf udvariasan. - Elvégre rended elöljárója vagy, bizalmi ember; mesterednek nyilván
nincsenek titkai előtted.
A primortel megnyalta szája szélét, s mély levegőt vett, mintha víz alá bukni készülődne. A szónak,
amit rekedten kiharákolt a tüdejéből, érdes éle volt, felsértette a fekete torony bazaltfalait. Garatjában
mintha durva kőzúzalék csikorgott volna; száját maró rozsdaíz öntötte el, máját-beleit ezerfelé rángó
acélhorgok szaggatták. A fájdalom szörnyűséges volt, sokkalta gyötrelmesebb, mint várta. A fáklya
sisteregve lobbant lángra, gyantaillatú szikrasziporkák záporoztak szerteszét. Táncoló, vörhenyes
fényívek keltek életre a boltozat sötétjében, részegen imbolyogtak a zárókövek körül, fürge-alaktalan
árnyékokat riasztottak föl a Kosfejes Nagyúr angyalainak bazaltba vésett domboralakjain.
A kín csípős könnyein keresztül Vyergas látta, hogy az elf hátrál egy lépést, bal karját tetovált arca
elé kapja; másik kezével a fegyverét markolta meg, a levélformán haj ló hiequar félig már kicsusszant
hüvelyéből.
Az ezüstpók baljósan megvillant; a primortel arcának azon az oldalán rég elsorvadtak mára
könnyzacskók, a varázsszem csak a homlokáról lecsorgó verejtéktől párásodott be kissé, ám ez nem
zavarta működését. Hamuszürke ködfátylak bomlottak ki szárnyak gyanánt Aurri alakja körül, félelme
szinte tapinthatóan áradt szét a levegőben; de nem volt eléggé őszinte, eléggé húsbavágó. Nem esett
pánikba, csak megrémült - és ez azt jelenti, hogy nem teljesen kiszolgáltatott, valami titkos védelemben
bizakodik az Ősök Tudománya ellen.
Elég legyen, primortel! - csattant fel élesen a comtur kísértethangja Vyergas koponyájában. A
zömök férfi összerezzent, kis híján elejtette a fáklyát. Ne pazarold kisded játékokra az erődet!
Az elf bámulatraméltó gyorsasággal lett úrrá félelmén. Aurája vibráló hullámokat vetett, szürkéről
lüktető vérvörösre váltott. Az undor sárszínéből alig maradt valami; épp csak a kisugárzása legszélén
derengett a sárgás árnyalat, háttérbe szorulva, elfeledetten. A szíve s a homloka körül azonban újfajta,
eleddig nem látott szín jelent meg: felhőként gomolygó, sűrű feketeség, mely szerteágazó erekben szövi
be a rőten parázsló lepkeszárnyakat, s egyre csak terjed tovább, akár a sebzett végtagon elburjánzó üszök.
A gyűlölet.
Vyergas mélyet, reszketeget sóhajtott, s az üres szemgödrében nyilalló ezüstpók elé emelte szabad
kezét, rövid időre kirekesztvén tudatából az asztrálvilág képeit. Amikor megszólalt, hangja rekedten
bugyborékolt, kis híján hörgésbe fúlt; hiába igyekezett, nem tudta belecsempészni azt az epés gúnyt, amit
szeretett volna.
- Ugyan már, nemes elsőszülött... mire véljem ezt az ijedelmet?... Hiszen nem történt semmi, csak...
világot gyújtottam...
Aurri visszalökte a kardját a hüvelyébe. Ahogy előrelépett, szeme jégkék szikrákat szórt; keskeny
arca halálsápadt volt, csak a vasbilincsbe tetovált, lángoló szívet övezte égő pír a homlokán.
- Attól tartok, nem sok hasznát vesszük a magadfélének, primortel, ha már a puszta tűzcsiholás is
ilyen nagy fáradságodba kerül - mondta szenvtelenül. - Talán jobb lenne másfelé kereskednem, az
Árnyfivérek vagy a Könnyek Testvérisége háza táján.
Vyergas leeresztette a bal kezét; az ujjai reszkettek. Az elf asztrálaurája koromfekete volt, akár az
éjszaka bársonya; a harag lángvörös csíkjai pókhálóként szőtték át meg át.
Valami folyékony, sós ízt érzett a torkában. Nagyot nyelt; hogy kitisztítsa kissé, és vasakarattal
fojtotta el a hullámokban rátörő émelygést.
- Az Árnyfivérek Káosz-Vulak híveivel háborúznak, senkit sem tudnak nélkülözni - felelte
határozottan. Elméje egyik eldugott zugában egy titkos mantrát ismételgetett kitartón, amit éppen ilyen
esetekre tartogatott; eddig még csak egyszer kellett használnia, amikor elvesztette a szemét. - A Könnyek
Testvériségének vadászai pedig még mindig nem tértek magukhoz a szörnyű csapásból, amit rokonaitok,
az Aiy'Umasyrass ház mért rájuk. - Érezte, hogy tagjaiba kezd visszatérni az erő, tekintetébe a tűz. Csak
valami nedves, szúró fájdalom maradt a gyomra mélyén; és tudta, hogy ettől már nem fog szabadulni
soha többé. - A Hét Domb és a Hét Völgy vidékén mi vagyunk az egyetlen olyan rend; amit
pillanatnyilag nem kötnek le más ügyek; és valami azt súgja nekem, nemes elsőszülött, túl sürgetős a te
gondod ahhoz, semhogy a szomszédos tartományokban kereshetnél rá megoldást.
Aurri szinte oda sem figyelt a szavaira; új onnan feltámadt érdeklődéssel nézegette, mintha most
látná először, vagy valami szokatlant, megdöbbentőt fedezett volna fel rajta.
- Mondd csak, fakóvérű - kérdezte kíváncsian -, mióta hódol a fajtátok annak az ocsmány
szokásnak, hogy életben hagyják a megcsonkultakat? Úgy értem - tette hozzá bocsánatkérő mosollyal, s a
gonoszul csillogó ezüstpókra mutatott Vyergas bal arcában -, milyen érzés úgy élni, hogy tudod
magadról: nem vagy teljes értékű ember?
Harag lobbanta primortel szívében, de csak egy kurta pillanatra. Ma egyszer már elvesztette az
önuralmát egy ostoba civódás hevében, és drága árat fizetett érte; másodszor nem fog előfordulni.
Gúnyolódjék csak az elf, ahogy kedve tartja; ha a Kosfejes Úrnak is úgy tetszik, már nem kell sokáig
elviselnie a fullánkos nyelvét. A Könnyűléptű Néppel sokkal tanácsosabb távolról ápolni a barátságot.
Rezzenetlenül viszonozta a jégkék szempár tekintetét, és értetlenül vállat vont.
- Fogalmam sincs, mire célzol ezzel, nemes elsőszülött - válaszolta. - Egyszerű fakóvérű vagyok én,
bizalmi ember, de azért csahos kutya, ahogy magad is mondottad. A cifra elf beszédhez nem értek; csak
azt tudom, hogy odafent a toronyban miránk várakozik a mester, és bizonyára kezd türelmetlenkedni már.
Aurri bólogatott, és hátrasimított az arcából egy aranyszín tincset, amely az iménti zűrzavarban
kiszabadult a szénköves diadém szorításából, s előrehullott a homlokába. Ahogy ujjai végigszántottak
sápadt-sima bőrén, nyomukban mérget köpött a kobra, szikrát vetett a törött kard, dobbanva feszült a
vasbilincsnek a lángoló szív.
A fáklyafény csalóka játéka, persze.
- Ne vesztegessük hát tovább az időnket, fakóvérű! - Az elf mosolya bántóan éles volt, mintha
borotvával metszették volna keskeny arcába, alig valamivel á csúcsba futó áll fölött. - Te az enyémet, én a
tiédet, ketten együttesen pedig a mesteredét.
Vyergas magasba emelte a szövétneket, és megindult a bazaltfalak árnyékában rejtőző csigalépcső
felé; a sötétség nyúlós fátylakra szakadozva szétrebbent előtte, majd nesztelenül összezárult a nyomában
lépkedő Aurri mögött. Ennek a csatának ő volt a vesztese; ám ugyanolyan tévedhetetlen bizonyossággal
tudta, hogy lesz még alkalma visszavágni, mint ahogyan annak idején Káosz-Huvarhg bomlott agyú
prófétája jósolta meg neki a trófeák s a kudarcok eljövendő hosszú sorát, az út végén a gyötrelmes-rút
halállal.
A comtur vak volt, néma és teljesen mozgásképtelen. Hatalmasra puffadt, fakórózsaszín testén
vastag hurkákban lógtak az ernyedt hájredők. Valahol azon a tájon, ahol a vállának kellett volna lennie,
két elsatnyult, csecsemőnyi kar csüngött ki tehetetlenül a petyhüdt ráncokba gyűrődő bőrlebernyegek
közül, ám az ujjak mind hiányoztak róluk. A lábaiból még ennyi sem maradt, azok teljesen elsorvadtak;
helyükön csak egy-egy-szürkés, öklömnyi csonk éktelenkedett.
A rendház ura rég elvesztette az arcvonásait. Feje formátlan húsdudorrá fejlődött vissza; tarajos
szegélyű daganatok sarjadtak rajta esztelen tobzódásban, körbenőtték a szájat, a szemgödröket és azt a
gennyes tályogot, amely valaha az orra lehetett. Az egész rákosan burjánzó hájtömeg egy drága
selymekkel körülfüggönyözött baldachinos ágyon hevert; alul nedvedző fekélyek nyíltak rajta a
felfekvéstől, felül tenyérnyi foltokban hámlott róla a kiszáradt, pikkelyes bőr. Időről időre kocsonyás
remegés futott rajta végig, egy ütemre ocsmányul szortyogó lélegzetvételével.
A félhomályos toronyszobában elviselhetetlen bűz terjengett, bár a hat sarokban éjjel-nappal égtek
az illatos füstölők, s a falak tövébe üvegszám locsolták a rózsavizet. A comtur-t cukrozott vérrel táplálták,
az orrába vezetett csöveken keresztül, a salakanyagok azonban csak a bőre pórusain tudtak távozni, mivel
az alsó testnyílásai mind benőttek. A szolgák ugyan óránként megmosdatták, ám a folyamatosan szivárgó
mocsok percek alatt újra összerondított mindent körülötte.
Az elf vonásaira egy pillanatra kiült a borzadály, amikor Vyergas kinyitotta neki a hatszoros
vasalással ellátott ajtót, és előzékenyen betessékelte a toronyszobába, égő fáklyáját magasba emelve.
Olyan hirtelen torpant meg a küszöbön, hogy kis híján orra bukott; hosszúkás arca még a szokásosnál is
sápadtabbnak tűnt, a remekmívű tetoválások élénk színekben virítottak rajta.
A primortel besiklott mellette a helyiségbe, fáklyáját egy sárkánykarmot formázó falikarba szúrta;
aztán a mennyezetes ágyhoz lépett, és széles mozdulattal széthúzta a függönyöket. Közben az ezüstpókkal
lopva hátranézett; Aurri alakja körül sárgán lobogó asztrálaura lángolt, melybe itt-ott a döbbenet fehér
foszlányai keveredtek. Olyan erős volt a fénye, hogy már-már vakított. Vyergas önkéntelenül hunyorogni
próbált; jutalma szúró fájdalom lett, ahogy a szemgödrében horgonyzó fémlábak a húsába hasítottak.
Mindjárt rosszul lesz nekem a fickó, gondolta elégedetten.
A comturt egyenletes azúrkék kisugárzás vette körül, mint mindig: a kiegyensúlyozottság, a higgadt
nyugalom színe.
Kizökkentettük a lelki egyensúlyából, és ez előnyünkre szolgál, üzente szavak nélkül a
primortelének: Rögtön ide kellett volna hoznod; fölösleges volt ostoba játszadozásokba bonyolódni vele.
Tudhatnád, hogy az effélével vívott szópárbajban csak vesztes lehetsz.
Raka kha'sthass, comtur, felelte Vyergas némán. Várom büntetésemet.
Ezzel visszafordult bejárat irányába, könnyed mozdulattal az ágyon heverő ormótlan testre mutatott,
és alig észrevehetően megbiccentette a fejét.
- Nemes elsőszülött, hadd ismertesselek össze Fra Bezak al Thauggal, rendházunk vezérlő
comturjával, akit a te néped Syros lamaranthnak, a Suttogó Pengék Urának nevez!
Aurri nagyot nyelt, és keze fejével lesimította a homlokán gyöngyöző verítéket. Látszott rajta; hogy
mélységesen megrendítette a látvány, de igyekszik úrrá lenni háborgó érzésein:
- Azt akarod mondani, hogy ez a... hogy ez itt... hogy valamikor emberi lény volt?
- Még most is az, nemes elsőszülött - felelte a primortel készségesen. - Mivel látni kívántad, a színe
elé vezettelek: Nyelve ugyan nincs már, de az én számon keresztül szólani tud hozzád.
- Értem. - A sárga lobogás megfakult kissé Aurri körül, a szélein kezdett visszahúzódni. A
Könnyűléptű Nép gyermekei mindennél többre értékelik a testi szépséget és tökéletességet; amivel a
toronyszobában szembesült, borzalmas és undorító lehetett a számára, ám lassan sikerült felülkerekednie
a megrázkódtatáson. - Kérlek, tolmácsold Syros Iamaranthnak az Ötödik Domb Háza üdvözletét, és az én
személyes jókívánságaimat. Minden vágyunk, hogy minél előbb felépüljön a... betegségéből, és ismét
felövezhesse derekára nemes kardjait, melyeknek dicsőséges nevét köszönheti.
Két hét böjt a nyirokcellában, kenyéren és vízen, naponta háromszori önostorozással, szólalt meg a
comtur szellemhangja. Mit fecseg itt összevissza ez a Könnyűléptű?
- Tévedésben leledzel, nemes elsőszülött! Fra Bezak csak beszélni nem tud, a te szavaidat
tökéletesen érti, nincs...
Hurgai san athaknai, comtur. Hallom és engedelmeskedem.
- ...szüksége az én közvetítésemre. Ami az állapotát illeti, az nem betegség, hanem általános testi
leépülés. Visszafordíthatatlan folyamat, amely néhány éven belül mindenképpen halálhoz vezet. Ez a
jelenlegi helyzet úgy állt elő; hogy Fra Bezak...
Most viszont nagyszerűen csinálod, primortel.
- ...ifjabb korában magához vette az Ősök néhány talizmánját; hogy közérthetőbben fogalmazzak,
részben lenyelte, részben más módon fogadta a testébe őket. Ezek a talizmánok bizonyos fokú védelmet
nyújtanak a hatalomigékkel szemben, és egyéb üdvös képességekkel is felruházzák hordozóikat,
mindazonáltal.:.
Igyekszem; mester. A torony tövében bevérzett a gyomrom; adósa vagyok ennek a tetovált pávának.
- ...különféle káros mellékhatásaik is vannak. Ezek a mellékhatások elfojthatók, amennyiben és
ameddig hordozójuk rendelkezik az ehhez szükséges energiákkal. Mint bizonyára tudomással bírsz róla,
Fra Bezak és jómagam az Ősökig vezetjük vissza a leszármazásunkat, így hát a te népeddel ellentétben...
Túlzásba azért ne vidd! Nem szükséges magunkra vadítanunk.
- ...képesek vagyunk használni az ilyen talizmánokat. Ahogy azonban öregedni kezdünk, az Ősöktől
öröklött erők is apadásnak indulnak, s amikor már nem bírjuk féken tartani a testünkbe ágyazott
talizmánokat, óhatatlanul jelentkeznek az imént említett mellékhatások. Ez történt Fra Bezak esetében; de
mint arra nemrégiben éles szemmel felfigyeltél...
Máris befejezem, comtur. Shaka'thorr.
- ...az én arcomba is egy hasonló talizmán van beültetve. Becslésem szerint az első tünetek mintegy
hatnyolc év múlva fognak kiütközni rajtam, s ezt követően némiképp hasonló, de nem egészen
ugyanolyan elváltozásokon fogok átesni, mint Fra Bezak. A leépülés viszonylag gyors lefolyású, a
beálltától számított egy-két éven belül megtérünk a Kosfejes Nagyúr kebelére. Kielégítettem a
kíváncsiságodat, nemes elsőszülött
Aurri Ly'Shematenel reszkető inakkal állt a küszöbön, és görcsösen markolta az ajtólap egyik
vasalását. Sekély, sebes kortyokban nyeldekelte a levegőt, tetovált arca verítékben úszott. Szemlátomást a
hányingerrel küszködött.
A Könnyűléptű Nép csak két dologtól undorodik jobban a betegségeknél és a testi csonkulásoknál:
az egyik a korai halál emlegetése, a másik az Ősök és a tudományuk.
Vyergas gondterhelt képet vágott, és közelebb lépett a bejárathoz. Ha tehette volna, rúnadíszes
pókszeme most mohón tágra nyílik az elégtétel kárörömétől; az elf nyúlánk alakja körül sáfrányszín
lángok tomboltak és örvénylettek, akár az üstökösök uszálya, vagy a napkorong széléről felszökő
tűzkitörések.
- Talán megbotlott ez a balga nyelvem, vagy rosszul fűztem valahol a szavakat? - kérdezte
aggodalmasan. - Nem tagadom, megesik olykor velem az ilyesmi, hiszen csak egyszerű csahos kutya
vagyok, nem olyan míves beszédű szónok, mint amilyeneket az Ötödik Domb Háza küld követségbe
hozzánk. - Szakállas arca hirtelen felderült, mintha nagyszerű mentőötlete támadt volna, amivel sebtében
orvosolhatná az egész kínos helyzetet. - Ha valamit nem értettél tisztán, nemes elsőszülött, örömest
elismétlem még egyszer!
Az elf lassan ráemelte jégkéken szikrázó tekintetét; a körülötte kavargó sáfránysárga aurán rohamos
gyorsasággal kezdett átütni a fekete erezet.
- Ne fáradj, primortel! - mondta fáradtan; hangja ezúttal rekedtesen, megviselten csengett, a régi
dallamosságnak nyoma sem volt benne. - Minden szavadat tisztán hallottam. - Kihúzta magát, eleresztette
az ajtó vasalását. - A lekötelezetteddé tettél. Égek a vágytól, hogy mielőbb méltóképpen viszonozhassam
a kedvességedet...
Vyergas szélesen rámosolygott, gondosan ügyelve rá, hogy minél többet mutasson hegyesre
köszörült, hibátlan fogsorából.
Egymással szemben ült a vadász és az elf, a bazaltból kifaragott; hatszögletű asztaltömb két
átellenes oldalán. A kettejüket elválasztó távolságot a tükörsimára csiszolt kőlap közepén tizenhárom ágú,
kovácsoltvas gyertyatartó felezte meg. Mindegyik gyertya a vörös más-más árnyalatában csillogott, attól
függően, hogy miféle lény vérével festették meg a viaszt az öntőmesterek. A kanócukon táncoló
lángnyelvek kámfor- és gyantaillatot árasztva keltek birokra a sötétséggel, ám csak az asztaltömb
közvetlen közeléből sikerült elűzniük. A helyiség többi része homályba burkolózott; csupán a hosszan
neszező visszhangokból lehetett sejteni, hogy hatalmas és boltozatos, s nyirkos hűvöséből, hogy valahol a
föld alatt húzódhat.
A két férfi némán nézte egymást, félórája immár; a jégkék szempár rezzenetlenül egybekapcsolódott
a sárga-ezüsttel. Mindketten ugyanazt olvasták ki a másik tekintetéből: a hosszúra nyújtott, fájdalmas
halál ígéretét. Egyenrangú felek voltak: egyikük a Könnyűléptű Nép hatalmas nemesi házának
elsőszülöttje és örököse; másikuk egy nagyhírű Szabad Rend gyilkoskasztjának rangidőse és elöljárója. A
Kosfejes Nagyúr akarata munkált bennük, az oltott gyűlölséget a szívükbe, az hintette el közöttük a
viszály magvait: Egyelőre nem voltak a maguk urai, nem cselekedhettek saját belátásuk szerint. A házuk
s rendjük által kijelölt feladatnak végére kell járniuk, mert a hűség kötelme előbbrevaló a személyes
vágyaknál. Ám mindketten úgy érezték, nem sokáig bírnának élni egy olyan világban, amit a másikkal
kell megosztaniuk; el voltak hát szánva rá, hogy mihelyt kölcsönösen bevégzik küldetésüket,
megpróbálnak változtatni e tarthatatlan állapoton.
A hosszú hallgatást végül Aurri törte meg. Hátradőlt az ülőhelyül szolgáló bazaltkoloncon, s
emberbőr zekéjének elejébe nyúlt. Mozdulata óvatos volt, hangsúlyosan lassú; nem szerette volna, ha
félreértenék, s a háta mögött kavargó sötétség páros pengéket fiadzana.
Jókora, viaszosvászon tasakot vett elő, melynek tartalma száraz hangon zizegett az ujjai alatt. Az
asztalra tette, s egy csuklómozdulattal átcsúsztatta a tükörsima kőlapon a primortel elé.
- Nem tudom, hogy valóban a comturoddal beszélek-e rajtad keresztül, de nem is érdekel - mondta.
Csak az a fontos, hogy elvállaljátok és teljesítsétek a megbízatást. A zacskóban lidércfű van, egy kisebb
helytartóság megnyomorítására is elegendő.
A lidércfű messze tartományokban rettegett növényféle volt, a jóval gyakoribb édesdohány rokona.
Aki belélegezte a füstjét, azt napokig szörnyű rémálmok gyötörték, oly kitartóan és következetesen, hogy
hamarosan az alvásnak még a gondolatától is megirtózott. Ez önmagában még nem lett volna baj, hiszen a
hatás ritkán tartott tovább egy hétnél; csakhogy már egyetlen szippantás elegendő volt az édeskés füstből,
hogy az áldozatban gyógyíthatatlan függőség alakuljon ki. Az ilyen szerencsétleneket ellenállhatatlan
vágy fűtötte a lidércfű kábító aromája iránt, bármit megtettek, hogy hozzájuthassanak; közben persze
tisztában voltak vele; hogy milyen hatással van rájuk a mákony, hogy minden egyes éteri elragadtatásban
töltött percért álmatlan éjszakákkal, vérfagyasztó víziókkal kell fizetniük. Hamarosan beesett szemű, sorvadásig sovány vázakká váltak; leginkább űzött tekintetükről, kezük folytonos reszketéséről lehetett felismerni őket.
A lidércfű a legkeményebb férfit is hónapok leforgása alatt szánalmas emberronccsá silányította;
akik a rabjává váltak, előbb-utóbb megtébolyodtak vagy végeztek magukkal. A Szabad Rendek kínzó- és
vallatószerei között igen előkelő helyet foglalt el; olykor, ha a megbízó ragaszkodott a különösképp
kegyetlen halálhoz, gyilkosságot is követtek el vele. Hozzájutni azonban nem volt könnyű, mert kizárólag
a Hét Domb és a Hét Völgy bizonyos eldugott csalitosaiban termett, s - az elfek nemesi házai féltékenyen
őrizték e tilalmas helyeket.
A tasakot a Ly'Shematenelek sisakos-tölgyfalombos pecsétje zárta le. Vyergas egy ujjmozdulattal
feltörte, a vörös viaszdarabkákat lesöpörte a földre, aztán széthajtogatta a vásznat. Kis halom szárított,
kékesszürke fűféle hevert előtte; tömött kalászaikból magvak peregtek szét az asztalon. A primortel
felcsippentette az egyiket, szétmorzsolta a körmei között, és megszagolta. Jellegzetes, édeskés-olajos illat
csapta meg az orrát. A lidércfű aromája csak akkor veszélyes, ha elégetik; olyankor viszont egyetlen
csipetnyi elegendő belőle egy egész serpenyőre való füstölőszerbe.
Nem hamisítvány? - kérdezte fejében a comtur szellemhangja. Mesterével csak látásán és hallásán
osztozott; a többi érzékszervére nem terjedt ki a láthatatlan mentálfonál hatalma.
- Elsőrangú minőség - mondta Vyergas fennhangon, és újra betakarta a szárított fűköteget a
vászonnal, előzőleg gondosan visszasöpörve a kiszóródott magvakat. Aztán a szemközt ülő elfre emelte
felemás tekintetét. - Hálával fogadjuk a bőkezű adományt. Mit kíván tőlünk cserébe a Ly'Shematenel
ház?
Aurri vállat vont.
- Valakinek a halálát.
- Fölteszem, az illető fontos és előkelő személy lehet, különben aligha érne ennyit az élete. - A primortel az asztalra könyökölt, vaskos ujjai hegyét könnyedén egymásnak érintette. - Azonfelül minden
bizonnyal hatalmas is, különben a közrendű vértestvériségek egyikét kerestétek volna meg, nem a Fekete
Özvegy Rendjét. Mi drágán számítjuk a szolgálatainkat, viszont elsőrangú szakértők vagyunk. - Kérdőn
félrehajtotta szakállas fejét. - Most a comtur szól a számmal: megtudhatnánk az áldozat nevét?
- Sestian Ly'Shematenel - vágta rá habozás nélkül az elf. - A nemzőatyám.
Vyergasnak komoly erőfeszítésébe került, hogy ne mutassa ki meglepetését, s a mentálfonál röpke
rándulásából érezte, hogy a hír még a comturt is kizökkentette kissé a nyugalmából. Nem mintha a
Könnyűléptű Nép nemesi házai nem ismerték volna a belviszályokat, a rokoni ármányt, a fiak
cselszövését az apák ellen; ilyen hosszú életű fajnál, ahol az elsőszülötteknek évszázadokig kell várniuk,
míg elfoglalhatják jogos örökségüket, ez nem is igen lehetne másképp. Ám az efféle intrikák és
fondorlatok mindig szigorúan megmaradtak a családkeretein belül; ritkán szivárgott ki róluk hír a
kívülállók fülébe, az meg egyenesen példa nélkül állt, hogy az egyik érintett fél a Hét Domb s a Hét
Völgy határain túl keressen segítséget.
Tisztázd a felállást! - küldte utasítását a comtur a szellemfonálon. Egy tasakra való gaz nem éri
meg, hogy belekeveredjünk miatta a Könnyűléptű Nép belviszályaiba.
- Azt hittem, az, Ötödik Domb Házának hivatalos megbízottjával tárgyalok, aki családjának zászlaja
alatt érkezett rendházunkba, s valamennyi testvérének nyelvével szól - mondta Vyergas lassan,
megfontoltan. - Ha magánemberként fordulsz hozzánk, nemes elsőszülött, más alapokra kell
áthelyeznünk a megbeszélésünket.
- Hivatalos követ vagyok, teljes körű jogokkal, amint azt a zászló és a pecsét tanúsítja - felelte
Aurri. - Atyám nem tagja többé az Ötödik Domb Házának, elvetette magától a Ly'Shematenel nevet. A
nemzetségfők tanácsa kimondta rá a khurnisst. Szülőanyám özvegynek tekinti magát; nagykorúságomig,
amíg be nem töltöm a századik életévemet, ő fogja gyakorolni a nevemben a hercegi jogokat.
Húzd egy kicsit az időt, primortel! Mintha rémlene valami régi eset... Gondolkodnom kell!
Vyergas mindkét tenyerét az asztal kőlapjára fektette, és elmosolyodott.
- Sajnálatos, hogy ilyen kései sarj vagy, nemes elsőszülött. Persze ha emlékezetem nem csal, valaha
voltak bátyáid, sőt egy nővéred is.
- Kalahoráink úgy látták jónak, hogy korán visszaszólítsák őket az örök körforgásba - felélte az elf
kurtán. - De azt hittem, az atyám ügyéről beszélünk, nem rég elfeledett vadászbalesetekről.
- Ó igen, ~ az atyád. Hírneves vitéz, haditetteiről messzi tartományokban is áhítattal regélnek. Úgy
tudom, tagja valamelyik lovagrendeteknek is...
- A Quirrtha Khinnek, de már csak volt. Ha bevégzitek a megbízatásotokat, a fegyverzetét vissza
kell szolgáltatnotok a Néma Nagymesternek. Tudom, hogy a hagyományos kontraktus szerint a trófea felszerelése a vadászt illeti meg; természetesen kész vagyok méltányos kárpótlást felejánlani érte.
Kiközösítették, jelentkezett Vyergas tudatában a comtur. De valami nincs rendjén. Ezt az ítéletet
csak a hercegnek áll jogában kimondani, a nemzetségfők egyhangú támogatásával.
- Bizonyára meg tudunk egyezni egy mindkét fél számára elfogadható összegben, ámbátor
ismereteim szerint a Könnyűléptű Nép lovagi páncéljai nem tartoznak a csekély értékű holmik közé -
bólintott a primortel, s összefonta ujjait az asztallapon. - Csak egyet árulj el nekem, nemes elsőszülött,
mert igencsak furdalja oldalamat a kíváncsiság! Az elméje borult-e el nagybecsű atyádnak, vagy démoni
szellemek költöztek belé, hogy önmagát sújtotta kitaszító szózattal a nemzetségfők tanácsa előtt?
Aurri Ly'Shematenel hallgatott. Ha meg is lepődött, nem rendült meg túlságosabban; mintha
számított volna valami ilyesmire. A rúnákkal vésett pók nyugodt azúrkéknek látta asztrális auráját, a
gyűlölet feketén lüktető alapszíne fölött.
- Szóval valóban a comturod nyelve vagy - szólalt meg végül higgadtan, már-már egykedvűen. - Ezt
magadtól nem tudhattad: Emlékeztünk rád még sequator korodból, és azért választottuk ezt a rendházatokat, mert sejtettük, hogy veled tárgyalunk majd. Téged rászedhettelek volna; de Syros Iamaranthot
soha.
- A Suttogó Pengék Ura, igaz? - kérdezte Vyergas. - Azok a pengék a Könnyűléptű Népből is
ejtettek trófeákat. Amikor még megvoltak a szemei, Fra Bezak sok mindent látott velük; és jól ismeri a
szokásaitokat.
- Nagy kár, hogy még életben találtam - értett egyet az elf. - Nemigen tartottuk valószínűnek, hiszen
a ti mércétekkel mérve nagyon öreg lehet már: ha j ól számolom az éveket, az ifjabbik húgommal
egyidős.
- Azt említettem, hogy néha a Könnyűléptű Nép vérével tápláljuk? Leginkább akkor ízlik neki, ha
cukorral és porrá tört shugaru-dióval fűszerezzük. Sajnos, mostanság egyre ritkábban jutunk hozzá.
- Nem az á fajta portéka, amit ingyen mérnének mosolyodott el hűvösen Aurri: Asztrális
kisugárzásán enyhe pír derengett, a szélén sárgás árnyalatokkal; de másodszorra már nem dőlt be
ugyanannak a cselvetésnek.
Fékezd magad, primortel! - intette alárendeltjét a néma kísértethang: Az adósságodat behajtottad; a
bosszúd várhat még. Ez a Könnyűléptű kíváncsivá tett.
Vyergas felsóhajtott, megcsóválta a fejét.
Shaka'thorr, comtur.
- Eddigi megbeszélésünket természetesen semmisnek tekintem - mondta. - Rendünk elutasítja az
Ötödik Domb Háza által kínált kontraktust, és visszaszolgáltatja az átvett értékeket - bökött a lidércfüves
tasakra. -Amennyiben azonban bővebb felvilágosításra érdemesítesz minket, nemes elsőszülött, az esetleg
alapját képezheti egy újabb tárgyalásnak.
Az elf gondolkodóba esett, a lehetőségeit mérlegelte. Egy percig ha töprengett tán, aztán döntésre
jutott.
- Rendben - bólintott, s az asztallap fölé hajolt. A csiszolt bazaltkő visszatükrözte gyertyafényben
fürdő vonásait. - Figyelmezz jól a szavamra, primortel, mert semmit nem fogok kétszer mondani! És ne
szólj közbe, hacsak nem Syros Iamaranth beszél az ajkaddal; nincs kedvem meddő magyarázkodásra
fecsérelni a drága időmet.
Vyergas néma főhajtással jelezte, hogy elfogadja a feltételeket. Az elf ajkáról fakadó sértéseket
egészen megszokta már, éppoly kevéssé zavarták, mint a sötétség vagy a halál. Ráadásul elég józan volt
ahhoz, hogy belássa szavai igazát. Az ő szerepe az elkövetkezendő percekben csupán arra fog szorítkozni,
hogy közvetítse comturjának Aurri magyarázatát. Ha közbeszólna, kérdésekkel okvetlenkedne, azzal csak
megzavarná a dolgok folyását, csalódást okozna mesterének, ingerültté tenné látogatójukat.
Másrészt viszont annak sincs sok értelme, hogy ostobán bólogatva hallgassa végig az egész
hosszadalmasnak ígérkező szónoklatot. A lényegét úgysem értené meg, ahhoz nem ismeri eléggé a
Könnyűléptű Nép hátborzongató gyönyörökkel teljes világát. Akkor már jobban teszi, ha hasznosan tölti
a rendelkezésére álló időt, és alaposan körbejárja gondolatban azt a kérdést, amely még a kapuboltozat
fáklyaláng-szaggatta homályában merült fel benne először, mikor a gyomrát elöntötte a sós ízzel terhes,
folyékony fájdalom.
Kényelmesen elhelyezkedett a bazaltkoloncon, kezét a térdére fektette, s egyenletes, mély
kortyokban szedte a levegőt. Ép szeme lassan lecsukódott, s a földalatti terem feloldódott körülötte a
sötétségben. Valahonnan messziről hallotta, hogy Aurri belefog a mondandójába, ám a szavait nem
értette, nem is figyelt rájuk.
Tarka gondolatfüzérek szökkentek szárba a homlokcsontja mögött, kényes virágok gyanánt
bontogatták szirmaikat, s ő a maga megfontolt, körültekintő módján nekilátott, hogy csokorba szedje
őket.
- Nem vagyok olyan ostoba, hogy hazugul a házam meghatalmazott követének adjam ki magam, és
kérészéletűekkel szövetkezzek hercegatyám ellen - kezdte Aurri. - Ha ezt hitted, tévedtél. A zászló, a pecsét
valódi; és igazat szóltam akkor is, amikor azt mondottam, hogy Sestian Ly'Shematenel már nem fia
népemnek, kitaszíttatott testvérei közül...
A primortel harmadik szeme előtt az idő hömpölygő folyamából kiragadva lebegett az a kristályos
pillanat, amikor Aurri ráemelte szikrázó tekintetét a kapuzat bélletes íve alatt; s az arcán végigcsapó
fáklyafény életet lehelt a bőrére tetovált hadikrónika képalakjaiba. Sziszegő kobrafej feszítetté szét mintás
csuklyáját; törött kard pengecsonkja villant fenyegetőn; béklyóba vert szív lövellt vörhenyes lángkoszorút
vasbörtönéből. Az elf megriadt ugyan az Ősök Tudományától - a fajtája zsigereibe ivódott félelmet ő sem
vetkezhette le -, de gyorsan magához tért, talán túlságosan is gyorsan:
Vyergas a Khat'ul'Naathum legtisztább vérű neveltje volt az utóbbi félezer évben. Félelmetes
hírnévnek örvendett a Szabad Rendek köreiben; hét tartományra innen nem akadt egyetlenegy vádász
sem, akinek a leszármazása az övéhez fogható lett volna. Mások rég ronccsá sorvadtak annyi idő alatt,
amennyit ő a harcmezőkön töltött; hajdani növendéktársai mind elhullottak vagy elaggottak mellőle, ő
azonban még most is ereje teljében járt. Harmincesztendős létére még voltak sötét szálak a hajában, s nem
szorult mankóra, kampókézre; csupán a fél szemét vesztette el. Túlélte a mérget váladékozó rúnapók
beültetését is, ami a legtöbb vele egykorú vadásznak kétségkívül a biztos halált jelentette volna.
Ma este mégis megnyomorította magát egy tűzgyújtó hatalomigével, amely távolról sem tartozott az
általa ismert legerősebbek közé, s eddig sohasem okozott neki nagyobb fájdalmat, mint egy közönséges
késszúrás. Az eset Aurri Ly'Shemanetel jelenlétében történt; és rögtön ezután látni vélte, amint az elf
arcán életre kelnek a tetovált krónikásjelek.
A fények játéka? Fájdalom szülte káprázat? Meglehet.
De a primortel többek között azért ért meg ilyen tiszteletreméltó kort, mert sohasem hitt a véletlen
egybeesésekben.
- Hosszú történet ez, s attól tartok, próbára fogja tenni a magadfélék szűkre szabott türelmét. Mégis
a legelején kezdem, mert gyökerei az óidőkbe nyúlnak vissza, és a gyökerek ismerete nélkül hiába
vizsgálgatnánk a faág friss hajtásait.
- Tudnod kell, hogy az Ötödik Domb Házának hercegi családja áldott magból származik. A hős,
akinek az ágyékából vérvonalunk fakad, olyan régen élt, hogy azt a ti gyarló elmétek felfogni sem képes.
Mi azonban emlékezünk ezekre az időkre, s nem csupán regéinkben és legendáinkban. Olykor, ha
magányosan elmélkedem egy rönkszentélyben, vagy a Tisztulás Ünnepén a szent lángokba révedek,
szertefoszlik körülöttem a világ, s elmosódott képek ködlenek fel a szemem előtt, távoli hangok ekhóját
véli hallani fülem. Beszélhetnék róluk, de nem teszem, mert úgysem értenéd. A te kései fajtádnak
nincsenek szavai ezekre a dolgokra, hisz akkor még az égiek gondolataiban sem léteztetek...
A Könnyűléptű Nép titkos krónikásjelei általában nem a viselőjükre utaltak, hanem az általa
legyőzött ellenfelekre, bár akadtak elszórt kivételek. Szimbolikájuk szövevényes volt és átláthatatlan; az
emberi elme nemigen tudta követni a szeszélyesen csapongó képzettársításokat. Vyergas ismerte, de nem
értette őket, valahogy úgy, ahogy az írástudatlan vésnök, aki a kezébe nyomott mintáról másolja át a
pénzveretre a betűk rovátkáit. Csaknem ötezer különféle képet raktározott el az emlékezetében, a
hozzájuk tartozó olvasattal együtt; ám arról például fogalma sem volt, hogy miért jelent az ágaskodó
királykobra csatában zsákmányolt hadizászlót, vagy a törött kard kerek húszesztendős háborúskodást.
- Ebben a letűnt korban élt a mi ősatyánk, kinek szeme még látta az Elveszett Hold fényét, mielőtt az
átkos emlékezetű Opálhajós örökre kioltotta volna. Magasztos lény volt, égi küldött, kalahora. Ez megintcsak olyan szó, amelynek nem találni mását a ti nyelvetekben. Megkísérlem körülírni neked, de ne engem
hibáztass, ha nem járok sikerrel; beszédetek barbár és bárdolatlan, ajkam csak nehezen hajlik rá,
hasztalan keresgéli a hiányzó szavakat.
- Próbáld meg elképzelni, hogy a Tizenhármak egyike nem a Birodalom alapításakor szállott alá a
világba, hanem ,a messzi ősidőkben, amikor a Kosfejes Úr még nem vetette reánk a tekintetét, s nem
nyilatkoztatta ki akaratát első prófétáinak! Tudom, hogy az alantas és csekély értelmű fajok számára ez
eretnekségnek hangzik; bizonyára magad is istenkáromlónak véled szavaimat. Hisz kit szolgálna ez a
mennyei sarj, kinek a nevében hajtaná uralma alá a teremtett lényeket, kihez intézne tisztelgő
véráldozatokat, ha egyszer a Kosfejes Úr még nem kívánja megajándékozni kegyelmével az anyagi
síkot?...
Külön-külön Vyergasnak nem okozott volna gondot a lángoló szív és a vasbilincs értelmezése sem.
Nem tartoztak ugyan a gyakori ábrák közé - sőt, az utóbbi a ritkánál is ritkábbnak számított -, de azért
ismerte a jelentésüket. A lángoló szívet például olyankor tetováltatták magukra a Könnyűléptű Nép
harcosai, ha valami régi családi ereklyét szereztek vissza ellenségeiktől, távoli őseik hagyatékát, amely az
idők során valahogy avatatlan kezekbe került. Ez nem feltétlenül jelentett anyagi természetű dolgokat; a
fogalomkörbe beletartozott a szellemi örökség, az elveszett tudás is. A primortel Aurri arcán látta először
ezt a krónikásjelet, ám az oculisok kémjelentései szerint a Hét Domb és a Hét Völgy vidékén több elf is
viselt hasonlót; a Néma Nagymester, a Quirrtha Khinn lovagrend elöljárója egyenesen kettőt.
- Ne fáradj a töprenkedéssel, emberfia; hajlékod vendégszerető ugyan, szívesen időznék benne
hosszasabban, ám a te életedet kurtábbra szabták az enyémnél, nem kívánhatom hát, hogy órákat áldozz
rám belőle. Inkább megválaszolom a kérdést magam. Ha az égi küldött korábban érkezne Ranagol
korszakánál, más urakat ajándékozna meg hódolatával: a legkevésbé gyöngéket és esendőket a hamis
istenségek közül. Szolgálata persze csak addig tartana, amíg a Kosfejes Úr rá nem mosolyog a világra.
Ekkor vagy hűséges marad, és meghal; vagy pedig az igaz hithez pártol, és üdvözül.
- Ezeket a koránjött Tizenhármakat hívjuk mi kalahoráknak, primortel; és közülük az egyik volt az
én ősatyám...
A vasbilinccsel már korántsem volt ilyen egyszerű a helyzet. Ez az ábra a Könnyűléptű Nép
bonyolult szimbólumnyelvének egyik legrejtélyesebb motívuma volt, megfejtésének regényes története
bővelkedett vérben, halálban, váratlan fordulatokban. Mentorok egymást követő nemzedékei veselkedtek
neki újra meg újra az értelmezésének, egyik ingatag elméletet a másik után állítva fel. A magyarázatok
némelyikét szinte azonnal megcáfolták, mások évtizedekig tartották magukat, hosszú távon azonban
mindegyikről bebizonyosodott, hogy téves. Hiába örvendett a Fekete Özvegy Rend tudós-kasztja kiváló
hírnévnek a Birodalom legtekintélyesebb egyetemi köreiben, ezzel a problémával sokáig nem tudtak
megbirkózni, megrekedtek a puszta találgatás szintjén. Többre már csak azért sem juthattak, mert nem
volt miből kiindulniuk:
- Hatalmas harcos volt a kalahora, legderekabb s legvitézebb az előkelők köpött. Hadba vezette
népünket az Ősök ellen, s győzelmet győzelemre halmozott; tekintete üstökösként lángolt, és sújtó
kardjával szemben senki nem állhatott meg. A Fekete Tudomány nem árthatott neki; mert az elfeledett
isten, akinek hódolattal adózott, átlényegítette őt s a vérébe költözött; megóvta minden rontó igétől.
Amikor az Ősök látták, hogy erővel le nem bírhatják, a földmély sötétjébe menekültek előle; kilenc nagy
fejedelmük vezetésével. Ő azonban esküvel fogadta, hogy oda is követi őket, s amikor visszatér, kilenc
trófea fog a derékövén függeni...
A vasbilincs jelének hosszú időn keresztül mindössze egyetlen példánya volt ismeretes, egy
elfbőrből preparált színpadi álarcon, ami hatszáz évig hevert a Khat'ul'Naathum titkos kincstárában, míg
véletlenül felfigyelt rá valaki. A rendi krónika tanúsága szerint Káosz-Abbog egyik vándor
zsigerelőszektájától került oda, tucatnyi más kétes értékű limlommal együtt, valami jelentéktelen
kontraktus értelmében. Hogy ők honnan szerezték, az nem szerepelt a feljegyzésekben; maguktól a
zsigerelőktől pedig már nem lehetett megérdeklődni, mivel az esemény után néhány évvel kiirtotta őket
egy rivális Káosz-szekta. A váratlan felfedezés mindenesetre nagy izgalomba hozta a mentorokat, mivel
az ősrégi, repedezett maszkon négy ismeretlen krónikásjelet találtak, azonfelül további kettőt a
legritkábbak közül: a vörös unikornist és a gyermekkirályt. Az első csak azokat a harcosokat illette meg,
akik páros viadalban arattak győzelmet az Ősök egyik rangos vezére fölött; a második haláljel volt, annak
bizonyságára, hogy viselője beteljesített egy vérbosszút, amelynek eredete a Birodalom alapítását
megelőző korokra nyúlik vissza. A legnagyobb megdöbbenést azonban a lelet színe okozta; soha senki
nem hallott ugyanis még olyasmiről, hogy a Könnyű léptű Nép asszonyai fekete bőrű gyermekeket hoztak
volna a világra.
- Egymaga szállt alá az Ősök miazmás hajlékába, íjjal-karddal felfegyverkezve, harcra s halálra
készen. Nemcsak hadvezér volt, vadász és nyomolvasó is, s tudománya a földalatti csarnokokban sem
hagyta cserben. Nyolc fejedelmet kutatott fel, hiába bújtak előle a legeldugottabb zugokba; nyolcszor
talált célba sebes nyílvesszeje, .nyolcszor fakasztott vért tévedhetetlen pengéje. Nagy riadalom támadt az
Ősök honában; gyászos sirámoktól visszhangzotta földmély, félelem fészkelte be magát a hűvös-hideg
sötétbe. Vezéreik hulltával a közrendű harcosokat olyan rettegés kerítette hatalmába, hogy fegyvereiket
eldobálva menekültek a felszínre a hős elől. A Könnyűléptű Nép azonban odafent várta őket, s vérét vette
valamennyiüknek, hiába könyörögtek sírva kegyelemért...
A rend mentorai évszázadokon át tanulmányozták a négy ismeretlen krónikásjelet, s bár az
eredmény nem jött könnyedén, konok eltökéltségük idővel átsegítette őket az akadályokon. Az egyiknek
az olvasatát a Dai'Hyllassien ház árulta el nekik, egy hajmeresztően kockázatos kontraktusért cserébe,
amely végül három tapasztalt mortel életébe került. A másik magyarázatára az Árnyfivérek titkos
szimbólumjegyzékében bukkantak rá, miután győzelmet arattak az ellenük viselt vadászháborúban, és
felprédálták központi rendházukat. A harmadikat csak úgy tudták megfejteni, hogy a tudós-kaszt
elöljárója áldozati felajánlást tett a Kosfejes Úrnak, s miután jósálmában megvilágosodott előtte a jel
értelme, rituális öngyilkosságot követett el a könyvesház oltárán. A mentorok mind több fejezetét
ismerték meg a titokzatos, fekete bőrű elf életének; és amit megtudtak, az egyre kevésbé tetszett nekik.
Az első tetoválása nemzőatyjukat megfojtó fiúk jele volt, de nem a járomcsonton, a bűnbélyeg helyén,
hanem közvetlenül az orrnyereg fölött, ahová a legdicsőbbnek tartott hőstettek kerülnek. A második a
háznélküliséget szimbolizáló wul-madarat ábrázolta, rendkívül archaikus stílusban: a farokpikkelyek
állása és az aranyszínű szempár a családi véráldozatnak egy oly ősi és visszataszító formájára utalt, amit
manapság már Káosz-Khakht legelvetemültebb szektái sem gyakorolnak. A harmadik krónikásjel egyszerűen annyit jelentett: "sárkányölő".
Ám a negyedik - a vasbilincs - továbbra is konokul őrizte titkát, még hosszú-hosszú ideig.
- Az Ősök kilencedik fejedelme Sycasra Zahtar volt, a ti nyelveteken a Bíbor Hadúr. Őt tartották a
legkülönbnek s legravaszabbnak mind közül. Amikor hírét vette a kalahora közeledtének, sietve
visszavonult a legmélyebb csarnokokba, és süket fülekkel fogadta a vérrokonaitól érkező segélykéréseket.
Gyávának vélhetnéd; pedig nem volt az, csak okos és számító. Türelemmel kivárta a Nyolcak bukását;
harcoltak és meghaltak, a kalahora győzött, ám közben ő is gyengébbé vált, hatalma megapadt, védelme
megtépáztatott. Ketten maradtak végül, és Sycassa Zahtar nem rejtőzködött többé: Pompázatos harci
díszben vonult ki ellenfele elé: lávafolyamok fénye ragyogott rőt szemében, homlokát vörösen izzó diadém
övezte, páncélozott markában bíbor lángokat okádott Sharab Shaktor, a Csatabárdok Atyja. A hős nem
riadt vissza a látványtól, hisz nem ismerte a félelmet; ám az elfeledett isten, aki a szívében-vérében
lüktetett, kevesebb volt nála, bár többnek hitte magát...
A krónikásjel másodpéldányára csaknem négyszáz ével később bukkant rá egy fiatal vadász, aki
elszakadt társaitól a Káosz-Samambrag híveivel vívott háborúban, és a Rőt Vidékre vetődött. A
nyomában sziszegő Kígyóhajúak, a szekta eszelős gyilkosai, ismerősek voltak errefelé. A vadász, akinek
ez volt az első csatája, leszámolt már az életével; ám a Khat'ul'Naathum ősi hagyományaihoz híven
szilárdan eltökélte, hogy ahány ellenséget csak bír, magával ránt a pusztulásba. Amikor leshelyét keresett
a vörös hegyekben, megindult a lába alatt a föld, s egy beomló kürtőn át alázuhant a mélybe. Üvegfalú
barlangban találta magát, amelynek bejáratát belülről falazták be hajdan. Leghátsó traktusában rozsdaszín
obeliszkek magasodtak, barbár rúnákkal ékesen, s tövükben egy néma alak feküdt.
A Kígyóhajúak utolérték, és könnyűszerrel végezhettek volna vele - mégsem cselekedték meg.
Sziszegő gyászénekbe kezdtek a kürtőszáj körül, majd letépték egyik társuk fejét, s engesztelő
áldozatként a mélybe hajították. A viperafürtös fej a vadász lába elé hullott; véreres szemekkel, fogát
csattogva méregette, s szörnyű átkokat szórt rá a szekta titkos harci nyelvén, míg végül, hosszú órák
múlva elcsendesült. Ekkor a Kígyóhajúak befejezték panaszos gyászéneküket, magára hagyták a
csapdában rekedt prédát, és hazatértek Káosz-Samambrag fertőszentélyeibe.
- Összecsapott hát végül a kalahora és az Ős; kő roskadt, föld rendült tusájuk nyomán, s félve
menekült közelükből a sötétség. Olvadt láva ömlött a Bíbor Hadúr sebeiből, s mikor busa feje meghasadt,
lángförgeteg süvített elő a törött diadém alól. Felbődült, féltérdre hullott, s a sziklák lángokat virágzottak
körülötte. A kalahora ekkor győzelmet vehetett volna rajta, ha nincs Sharab Shaktor; ám a Csatabárdok
Atyja megváltotta gazdája életét, forró hamuvá porladt a markában, s ami ereje csak volt, átsugárzotta
belé. Fölállott a Hadúr, és elüvöltötte magát rettenetes fájdalmában; oly nagy volt bánata s keserűsége,
hogy ordítása az egek magasáig szárnyalt, s mindenki szörnyethalt, aki csak hallotta. Számosak az Ősök,
s számosak rontó igéik is; ám mind közül ez volt a valaha kiejtett leghatalmasabb...
A vadász ifjú létére okosan és megfontoltan viselkedett. Körülnézett a barlangban, de nem
kapkodott, nem vesztette el a fejét. Ügyelt rá, hogy tekintete messze elkerülje a vörös kövekbe vágott
rúnasorokat; az alattuk heverő tetemet alaposan szemügyre vette ugyan, ám attól óvakodott, hogy a
kezével illesse. Fiatal, tetovált homlokú elf volt; talán kétszáz, talán kétezer éve fekhetett itt, a korát nem
lehetett megbecsülni. A barlangban nem voltak dögevők, és az alsó kürtőkből felszálló kénes
kipárolgások teljesen kiszárították a karcsú testet. Mindkét karja darabokra volt törve, ujjai helyén
otromba csonkok éktelenkedtek.
A csapdába esett vadász sejtette, hogy valami nagyon fontosat talált, de a felszínre nem tudott
kijutni. A régi bejáratot hármas rétegben egymásra halmozott kőtömbök torlaszolták el; a kürtő bordáinak
üvegélei csontig hasogatták a kezét, és a mászókampó sem lelt rajtuk fogást: Ha csak a saját életéről lett
volna szó, a vadász belenyugszik a Kosfejes Úr akaratába, és elmetszi torkát a sequorával; ám akkor a
rend sohasem tudná meg, miféle titkokat rejteget az üvegbarlang.
Letelepedett hát a kristályokat sarjadó kőpadlatra, hátát a pengékkel redőzött sziklafalnak vetette;
mély lélegzetet vett, lehunyta szemét, és segélykérő hívást bocsátott útra a rejtett síkokon. Aztán
lehajtotta a fejét, és megkezdte a hosszú várakozást.
- Az elfeledett isten megrémült az iszonyú hangtól, s hű hívét cserbenhagyva menekülni próbált. A
kalahora szívében kilobbanta fény, lelke éjbe borult; ám az utolsó pillanatban szellemujjaival a gyáva
isten után kapott, megragadta keményen, és magával rántotta a sötétségbe. A szörnyűséges bűvige
elemésztette Sycassa Zahtart is; roppant teste megroskadt, magába omlott, izzó lávatóvá olvadt szét. Így
végezték ők hárman, hatalmasok...
Három hétbe tellett, amíg az oculisok rátaláltak elveszett testvérükre. A Rőt Vidék messze esett a
rend bevett vadászmezőitől, és Káosz-Samambrag hatalma mélyem fészkelt ezen a tájon. A felderítők
Kígyóhajúakkal és Rozsdaevőkkel csatáztak, s messorokat kellett kirendelni a védelmükre a központi
házakból, különben elvéreztek volna mindannyian. A háború mérlege hol erre, hol amarra billent: a szekta
fanatikusai mérget köpködve hadakoztak, s az ostromlott tartományokban a rend keservesen nélkülözte a
Rőt Vidékre küldött kardokat.
Ezenközben az ifjú vadász türelmesen várt. Amíg képes volt rá, hosszan elmélkedett a Kosfejes Úr
akaratáról; később, lázbetegen, a halott elf szellemével társalkodott éjszakánként. Amikor megéhezett,
fogta a viperafürtös fejet, melyet üldözői hajítottak utána, és csupasz fogaival marcangolta lé róla a húst.
Amikor megszomjazott; előbb a halott Kígyóhajú szemét nyelte le; majd lyukat vágott a koponyájába, és
kiszürcsölte belőle az agyvelőt.
Mikor az oculisok kihúzták az üvegbarlangból, már félrebeszélt, alig volt több fekélyes váznál. De
életben maradt;` és később, az évek szaporodtával, hírneves vadász, rettegett harcos vált belőle.
- Ősatyám szelleme mind a mai napig a sötétséget járja. Népem bosszúállója ő; elégtételt vesz a
rajtunk esett sérelmekért. Gondolatai nincsenek, mert elméje halott, megölte a Bíbor Hadúr gyászigéje;
ám néha felnevet, s ilyenkor nagy dolgok történnek a világban. Ő az egyetlen kalahora, akit a
Könnyűléptű Nép mindkét ága tisztel: mi, az Igazak, akik részesültünk a Kosfejes Úr kegyelmében, és az
Elveszettek, akik puhányokká sorvadtak a külvilágban. A neve Mallior, az Éjben Kacagó...
Ha az ifjú vadász merő önzésből és élnivágyásból cselekedett volna, amikor segélykérő hívással
fordult a háborújukat vívó Fekete Özvegyekhez, csúf halált hal rögtön a megmentése után. Mert a Rőt
Vidékre küldött felderítőket maga a primoculis vezette, Ősök ivadéka, legelőbbrevaló a rend éles szemű
nyargalói között. És túl sok derék emberét látta elhullani az úton, semhogy irgalmas szívvel legyen
haláluk okozójához, ha kiderülne, hogy hiába ontották érte a vérüket.
Amikor kiemelték a sorvadt emberroncsot a kürtőből, a primoculis odalépett hozzá, és torkon
ragadta. Az ifjú vadász felnyögött; sárga genny szivárgott a feldagadt ajkát szabdaló repedésekből. A
primoculis azonban tisztára söpörte lázban égő elméjét egy durva hatalomigével, s nem eresztetté el addig
a nyakát, amíg sorra-rendre ki nem faggatta a barlang titkairól.
Amint végzett; félrelökte az alig-eleven testet a várakozó boncmester kezébe, és intett nyargalóinak.
Hármas acélheveder került a dereka köré; emberei magasra emelték, majd óvatosan leeresztették a kürtőszáj sötétjébe.
A primoculis nagyerejű hatalomigékkel vértezte föl magát, mielőtt körülkémlelt volna odalent.
Bölcsen tette: az üvegbarlang mélyén ezernyi álcában leselkedett a halál. A bannara-mesterek legádázabb
mérgei hűs forrásvíznek tetszettek ahhoz az ocsmány miazmához képest, amely a rőtvörös obeliszkeken
vicsorgó rúnákból gőzölgött. És az-ifjú vadásznak nem lett volna ideje segítséget kérni, ha akár egy ujjal
is hozzáér a barlang hallgataglakójához.
A primoculis úgy döntött, hogy életben maradhat.
- Amikor a kalahora elsőszülött fia hírt kapott róla, hogy mi történt atyjával, nagy keserűség támadt
az ő szívében. Fölállott a harcosok gyűlésében, s ádáz szavakat szólt a hamis istenről; aki cserbenhagyta
Malliort. Az ilyen isten nem méltó a Könnyűléptű Nép hódolatára, mondta: el kell hát taszítani, s újat
keresni helyette. A hűtlenség s a gyávaság éppúgy bűn az égiek, mint a halandók között. Az ő szeme
kinyílott az igazságra, ám a többi vezérek vakok maradtak, s borzadva hallgatták beszédét: Káromlónak,
vértagadónak nevezték, s kitaszították maguk közül..:
A fiatal elf, akit múmiává aszaltak a földmély kénes kigőzölgései, saját akaratából jött a barlangba
annak idején. Első dolga az volt, hogy hatalmas köveket vonszoljon á bejárathoz, és izomszakasztó
munkával egymásra halmozza őket. Három rétegben húzta fel a vaskos sziklatorlaszt; ráncos tenyerén
még most, ennyi év múlva is kivehető volt az üveges élszegélyek marása.
Miután befalazta magát, sorra egymás után leharapta és lenyelte mind a tíz ujját. Ezt követően
odament a fal egyik fűrészes kiszögelléséhez, s előbb a bál, majd a jobb karját törte szilánkokra rajta.
Mikor már biztosra vehette, hogy képtelen kiszabadulni magaválasztotta sírboltjából, lefeküdt az egyik
vörös obeliszk alá; belélegezte a mérgező párákat, és meghalt.
Sárgára száradt homlokán egyetlen krónikásjel mosolygott fakó-haloványan: a vasbilincs.
- Az elsőszülött ekkor megátkozta a hamis isteneket, s felvette a Ly'Shematenel nevet, ami a mi
nyelvünkön annyit tesz: Tettekkel Emlékező. Ezután maga köré gyűjtötte a Könnyűléptű Népből azokat,
akik hasonlatosan gondolkodtak hozzá: sokan voltak ilyenek, főleg az ifjabb harcosok között. Odahagyták
tévelygő testvéreiket, és folytatták a háborút az Ősök ellen, ádázabbul és kérlelhetetlenebbül, mint
amazok; haldokló hőseik az ellenséges tetemek között heverve gyakran véltek távoli kacajt hallani az
éjszakából. Sokáig keresték azt az istent, aki méltó a szolgálatukra, de csak hazug szellemeket és
szánalmas árnyakat találtak. Végül úgy döntöttek, hogy az istenük még nem nyilvánult meg; és
beköszöntött a Várakozás Kora, mely hosszú-hosszú ideig tartott, egészen a Kosfejes Úr e jöveteléig...
A boncmester hínárzöld penészt talált a múmia koponyájában, a démoni megszállottság biztos jelét.
Könnyű volt elképzelni az ifjú elfet, ahogy a homloka mögött suttogó gonosz hang az őrületbe kergeti;
ahogy zilált hajjal, lázban égő szemekkel az üvegbarlangba menekül előle; ahogy tébolyult módszerességgel megtervezi és előkészíti saját iszonyú halálát.
Ám akkor mit keres az arcán a vasbilincs jele; ráadásul a homlokára tetoválva, ahová a dicső
haditettek emlékei kerülnek?
Ha démon száll meg valakit, általában komoly céljai vannak vele, tervei messzebbre mutatnak a
kisstílű pusztításnál. Vérbosszú; lélekorzás; egész népek, fajok romlásba döntése. S mivel a művelet elég
nagy fáradságába kerül, gondosan őrködik választott bábjának épsége fölött, legalábbis amíg így diktálja
érdeke.
Csakhogy a démonok szerfölött ritkán vannak tisztában a halandók testi szükségleteivel. Azt tudják
róluk, hogy a tűz és a testüket átjáró vas megöli őket; azt viszont nem mindig, hogy időnként enniükinniuk kell, s idegen környezetben elsorvadnak.
Mit tenne egy elszánt lélek, ha démoni igába kényszerülne, s világos perceiben kétségbeejtő
bizonyossággal tudná, hogy a szörny a népe, nemzetsége, családja elveszejtésére akarja felhasználni őt?
Tőrrel vagy méreggel nem lehetne öngyilkos; a démon felismerné a veszélyt, és megakadályozná. De ha
elvonulna valami titkos helyre; ha gondoskodna róla, hogy soha többé ne juthasson ki onnan; ha önkéntes
éh- és szomjhalálra ítélné magát...
A primoculis szűkszavú beszámolóját tanulmányozva a rend mentorai gyanítani kezdték, hogy a
törékeny ifjú, akit az üvegbarlangba zárva találtak, a Könnyűléptű Nép legnagyobb hősei közé tartozott.
- A Ly'Shematenel ház nem sokáig maradt egyedül. Ahogy teltek az évek, más családok, más
nemzetségek csatlakoztak hozzánk: valamennyien megcsömörlöttek a hamis istenektől, akik egyre
gyengébbekké és erőtlenebbekké váltak, s mind gyakrabban fordították el arcukat híveiktől. Így
gyarapodott az Igazak száma, és így indult apadásnak az Elveszetteké. Minket harcra és halálra neveltek
atyáink, s Mallior példája arra tanított, hogy vesztünkben is magunkkal rántsuk bukásunk okozóit.
Belőlük azonban lassan kivesztek az ősi erények; sorvadó isteneiket követvén elgyávultak és elpuhultak,
feladták az Ősökkel vívott háborút, s örök gyalázatukra a rejtőzködésben kerestek menedéket. Ekkor
átkunkkal sújtottuk őket, vérünk árulóit; méltatlanokká váltak rá, hogy megosszuk velük a világot.
Ilyeténképpen idéztek gyávaságukkal az Elveszettek pusztulást a saját fejükre; mert immáron nemcsak az
Ősök öldösték őket, hanem mi magunk is, valahányszor a szemünk elé merészkedtek. Hanyatló nemzetség
az övék, ha itt-ott még el is tengődnek szánalmas búvóhelyeiken; még egy ezredév, s mára fák és a füvek
sem fognak emlékezni rájuk...
Újabb évszázadok elmúltával a köszvényes hátú agg; Vyergas félelmetes nevelője, imigyen foglalta
össze növendékeinek a vasbilincs-szimbólum jelentését:
"Sötét erő, ártó hatalom, amely kiterjeszti befolyását a jel viselőjére, s egy időre akarata eszközévé
alázza; ő azonban szembeszáll vele, s-ádáz harcokban győzelmet nyer rajta, akár a tulajdon élete árán is."
A tetszetős okfejtésben csupán, egyetlen hiba maradt, amit a mentorok minden igyekezetük dacára
sem voltak képesek kiküszöbölni. A primoculis a maga gyakorlatias észjárásával már annak idején
rámutatott; a tudós-kaszt vénei azonban nem tudtak mit kezdeni vele, így hát jobb híján félretették.
Mert ha a törött karokkal haldokló elf végső diadalának csak a néma üvegfalak s a rőt köveken
vicsorgó rúnák voltak tanúi - akkor ki tetoválta a homlokára a dicsőségét megörökítő jelet?
- Idővel aztán hírt kaptunk a lángszemű prófétákról, akik ősi ellenségeink földjeit járják, és egy új
isten szavát prédikálják. Ez az isten, mondották a hírek, nem a megbocsátást tanítja, hanem a megtorlást;
nem az alázatot, hanem a büszkeséget; nem a behódolást, hanem a hatalom igazát. Hallottuk azt is, hogy
a régi istenek hívei sók helyütt fegyvert fogtak a próféták ellen, azok pedig tűzzel sújtottak le rájuk, és
megölték őket. Kedvünkre valók voltak ezek a hírek; lóra kaptunk hát, és elindultunk megkeresni a
prófétákat. Először Rayvanhurral találkoztunk, és mind a mai napig őt tarjuk legnagyobb becsben a
Tizenhármak közül. Mert az ő ajkáról nyilatkozott meg nekünk az igazság; ő mosolygott ránk elsőként
Ranagol mosolyával. Mi pedig elfogadtuk a Kosfejes Úr tanítását, és friss vérrel hódoltunk neki, az
Elveszettek vérével; tudtuk, hogy végre megleltük azt az istent, akit Mallior szégyen nélkül szolgálhatott
volna, ha később születik...
Vyergas eddig acélistrángra fogva hajtotta előre gondolatait a kijelölt úton. Most szabadjára engedte
őket, hadd kalandozzanak tetszésük szerint. Érezte, hogy tud valamit a Könnyűléptű Népről, ami
közelebb viszi a megoldáshoz, újabb mozaikkövet illeszt a nagy összképbe. Hogy mi ez a valami, arról
fogalma sem volt; bizonytalan sejtésre, homályos megérzésre támaszkodhatott csupán. Mindenképpen a
nyomára kell jutnia, ha tovább akar lépni a holtpontról; és tapasztalata azt súgta neki, hogy a makacsul
erőltetett összpontosítás ilyenkor többet árt, mint használ.
A tetoválómesterek. Különös figurák voltak, általános nagyrabecsülés övezte őket, előkelő helyet
foglaltak el a Könnyűléptű Nép társadalmában. Tevékenységük nem merült ki a krónikásjelek
elkészítésében: diplomaták voltak, ügyes kezű méregkeverők, s noha igen messze álltak a szokványos
értelemben vett papoktól, ők vezették az egyik helyi bálvány tiszteletére rendezett titkos szertartásokat is.
Temérdek ostoba szóbeszéd járta róluk: hogy parancsolnak a szellemeknek, hogy szóra bírják a holtakat,
és átkukkal sújtják házuk ellenségeit. De mesélték azt is, hogy már új szülött korukban megmutatkozik
rajtuk az elhivatottság, mert testüket tetőtől talpig alaktalan, vörhenyes foltok borítják. És Vyergas a saját
szemével látott sequator korában egy ilyen tetoválómestert a Harmadik Völgyben, az Aiy'Umasyrass ház
szállásán. Büszke tartású, szálas elf volt, zölddel szegett köntösben és babérkoszorúval a homlokán; az
ifjú vadász mégis csodálkozott, miért nem taszítják ki maguk közül a többiek, mert sápadt bőre úgy nézett
ki, mintha leforrázták volna.
Aztán ott voltak a Holdleányok, akik két anyajeggyel a testükön jöttek a világra: egy kékkel és egy
vörössel. Saját testvériségbe tömörültek, bár a házukat nem tagadták meg, s az összetartás elég gyenge
lábakon állt közöttük: Nyíltan vallott céljuk, melyet olykor évszázadokon át hajszoltak hasztalan, az volt,
hogy megkeressék magukon a láthatatlan harmadik jelet, az Elveszett Hold mását. Hagyományaik szerint
ezen az egy ponton - a stigmán - teljesen érzéketlenek voltak a fájdalomra. Így hát vékony ezüst tűket
hordtak maguknál, aprólékos gonddal feltérképezték a testüket, és mindennap ellenőrzés alá vettek egy
tenyérnyi felületet; míg el nem szédültek a vérveszteségtől. Ha a végére jutottak, kezdték az egészet
elölről, abban a szilárd meggyőződésben, hogy valahol hibáztak, és elvétették a tűheggyel a stigmát. Az
idősebb Holdleányokat onnan lehetett felismerni, hogy tetőtől talpig vékonyra varasodott hegszövet
borította őket.
Olykor azonban egyik-másik Holdleánynak nyoma veszett, és a Könnyűléptű Nép soha többé nem
hallott róluk. Nővéreik úgy vélekedtek, hogy ezek a lányokasszonyok meglelték magukon az Elveszett
Hold jelét, és felvételt nyertek a testvériség második, titkos fokozatába, amely a felszín alatt finom szálú
pókhálóként szövi be az egész Birodalmat, s vezérek és koronás fők sorsa felől határoz. És a rend
feljegyzéseiben valóban szó esett sebhelyes elf nőkről, akik nem viselik egyetlen ismert házjeleit sem;
ellenségeiket tűzzel emésztik el, s az ujjaikból lövellő láng mindig három holdsarlót perzsel az áldozatok
testébe.
Hogy volt-e közük e titokzatos alakoknak az eltűnt Holdleányokhoz, azt senki sem tudta. Ám
bizonyos tiltott krónikákban azt olvasták a mentorok, hogy miután elkövette rettenetes tettét, a
Könnyűléptű Nép csapdába csalta az Opálhajóst. Nem ölték meg, csak bebörtönözték - vagy mert nem
állott hatalmukban, vagy azért, mert rá akarták bírni, hogy fordítsa visszájára szörnyű mágiáját, s bűvölje
vissza az égre az Elveszett Holdat. Az Opálhajós rabtartói arcába köpött, és leperzselte a fejüket. A
Könnyűléptű Nép nagyjai ekkor egy ősrégi eredetű boszorkányrendet bíztak meg az őrzésével, s
feladatukul szabták, hogy szüntelen kínzásokkal gyötörjék, egyetlen perc nyugalmat sem hagyván neki,
amíg ki nem leheli fekete lelkét, vagy kötélnek nem áll.
Ezt a boszorkányrendet emlegették a krónikák a Három Hold Szövetségeként.
- Ha harcban közelít hozzá a halál; és elég forró vágy ég a szívében, hogy ne vesszen
bosszulatlanul, a Könnyűléptű Nép bármelyik gyermeke meghallhatja Mallior kacaját, még az Elveszettek
is. Nekünk azonban, akik a Ly'Shematenel házból származunk, néha máskor is a fülünkbe cseng, hiszen
rokoni hang, az ősatyánké. Ritkán történik ez meg, s mi nem örülünk neki. Mert sötét ára az, amikor egy
Ly'Shematenel, akinek még nem telt le a kiszabott ideje, meghalja álmában Mallior nevetését. Amikor
felébred, nem lesz önmaga többé: lénye feloldódik népünk emlékeiben, az ősi gyűlöletben, a
keserűségben, a halál sóvárgásában. Umahtar lesz belőle: nyelvétől megrabolt szörnyeteg, akit
átlényegített a kalahora szelleme, s nem gondol többé rokonnal, családdal, jövővel, csak a pusztítás
önemésztő vágya vezérli...
A tetoválómesterek és a Holdleányok történetében csak egyvalami volt fontos Vyergas számára:
hogy a Könnyűléptű Nép gyermekei között akadnak olyanok, akik születésüktől fogva magukon viselik
sorsuk bélyegét. Aligha lenne vakmerőség feltételezni, hogy léteznek más sorsjelek is a vörös foltokon és
a holdszeplőkön kívül.
A primortel szíve hevesebben kezdett dobogni, lélegzete felgyorsult. Úgy érezte, valami nagy
titoknak jutott a nyomára, ami eddig a rend legtudósabb mentorai előtt is rejtve maradott.
Mi van akkor, ha ilyen sorsjel a vasbéklyó, s talán a lángokkal övezett szív is? Ha nincs szükség
hozzájuk tűre és festékre, hanem maguktól jelennek meg viselőjük arcán? Az üvegbarlang néma
strázsájára gondolt; a fekete bőrű elfre, akinek lenyúzott arcából valaki színpadi maszkot készített; Aurri
Ly'Shematenelre, aki ármányosan ellene fordította az Ősök Tudományát. Mi van akkor, ha a titokzatos
ábrák nem haditetteik emlékét őrzik, hanem épp ellenkezőleg, előre kijelölték számukra azt az utat, amin
járniuk rendeltetett?
Mi van akkor, ha a Könnyűléptű Nép csupán azért találta ki a krónikatetoválás egész művészetét,
hogy elleplezze a kívülállók elől az árulkodó sorsjeleket?
- Az Ősökkel vívott háborúnk még nem ért véget, és nem is fog addig, amíg az írmagjukat is ki nem
irtottuk a világból. Ne hidd, hogy a Fekete Tudományuk megmenti őket: vénségükre ostobákká lettek,
egymásellen acsarognak és letűnt korok emlékén merengenek, miközben mi lassanként végzünk velük.
Számon tarjuk a belviszályaikat, és ha valaki meggyengül közülük, azonnal lecsapunk rá. Az utóbbi
századévben négy trófeát szereztünk; te talán siralmasan kevésnek véled, mi azonban türelmes nép
vagyunk...
Lángoló szív vasbilincsbe zárva. Két egybefűzött ősi jel. Értelmezésük színleg ellentmond
egymásnak: ám ez az ellentmondás csak látszólagos.
A tűzbe vetett szív: veszendőbe ment tudás, amit a hős visszaszerzett. A vasbéklyó: sötét erő, amely
megszállja a hőst, s egész népét romlásba dönti. A megoldás csodálatosan egyszerű, mint mindig, ha
utólag tekintünk vissza rá.
A két fogalom egy és ugyanaz. Az elveszett tudás a démoni erő; az fenyegeti pusztulással a
Könnyűléptű Népet, s rajtuk kívül még számosan másokat.
- Az úmahtarokból viszont hiányzik a türelem; őket az Éjben Kacagó őrülete fűti. Úgy akarnak
háborúzni, mint az óidőkben: fellobogózott seregek élén, égi hajókkal, diadaljelvények alatt. Nem
magyarázhatjuk meg nekik, hogy harcosaink száma ezredannyira apadt; hogy mágiánk hatalma
megcsappant, s védtelenné váltunk a Fekete Tudománnyal szemben; hogy újfajok tűntek fel azóta,
megannyi új ellenség, akikkel mind számolnunk kell. Nem magyarázhatjuk meg nekik, mert gondolataik
halottak, csak az ősi gyűlölség vezérli őket...
Mi lehet az a tudás, ami ilyen pusztító hatással lehet a Birodalom népeire? Mi lehet az, amit a
Könnyűléptűek bírtak hajdanán, ám később elvesztettek, s hiába kutatnak utána azóta is? Mit hallgat el a
rend elől Aurri Ly'Shematenel?
A válasz megintcsak nevetségesen kézenfekvő, gondolta Vyergas, s harmadik szeme előtt lassan
egybefüggő képpé rendeződtek a mozaikkövek. A Könnyűléptű Nép a hajdanvolt korokban nyíltan
háborúzott az Ősökkel, évszázadokon át dacolt velük, nem omlott vérsalakká a hatalomigék tüzében.
Ennek csak egy magyarázata lehet: valaha nekik is megvolt a maguk titkos tudománya, amit
szembeszegezhettek az Ősökével. Mágia, ám minden más halandó mágiánál hatalmasabb. Volt idő,
amikor még elf ajkakon is kéltek hatalomigék.
Hogy miként s mikor feledték el a tudományukat, azt csak ők maguk árulhatták volna el, de ez nem
számított. A fontos csak az volt; hogy az Ötödik Dombon kísértő árnyék támadt a múltból, egy őrjöngő
bálvány, aki új életre kelt az ágyékából fakadó sarjak vérében és velejében. És ez a bálvány magával
hozta az ezredévek sötétjéből az elveszett tudást.
- Van fogalmad arról, emberfia, hogy mi történne a Birodalommal, ha a Leples Asszony levetné a
fátylát, az Akasztott Király odahagyná a Fekete Forrást, és a Suttogó felébredne a hegyek gyökerénél?
Ha a Fakó Vizek Pásztora és a Csontlovag félretenné az ősi ellenségeskedést, és emlékezetükbe idéznék
valaha volt barátságukat? Ha a Lánggal Égő Szűz újra szerelemre gyúlna, és a Vakon Látó visszanyerné
a szeme világát? Ha Káosz-Raddaq és Káosz-Buulzaab elfordulnának híveiktől, bevégezni egy
elfeledettnek hitt háborút, amelynek megvívását esküvel fogadták egykoron? A Tizenhármak nem
állíthatnák meg őket; ahhoz még az ó hatalmuk is kevés...
Vyergas beszélte az elfek nyelvét, bár nem olyan folyékonyan, mint a toronyszobájában haldokló
comtur, vagy hajdanvolt mentora, a köszvényes csontú agg. Most szavakat rakott egymás után, ábrándos
kedvvel, szinte játszadozva.
Úmahí - őstudás. Gonosz szó, sötét felhangokkal terhes. Ne keresd, ami elveszett! - sugallja.
Atar vagy ator - megszállott, aszerint, hogy hím vagy nőnemű személyről van szó. Ahol ez a
megkülönböztetés nem bír nagyobb jelentőséggel, ott általános érvénnyel a hímneműalakot használják.
Ebből igazán nem nehéz összetételt gyártani. Úmahtar - az őstudás megszállottja. Lángoló szív
vasbéklyóba verve...
A sorsod a homlokodra van írva, elsőszülött, gondolta Vyergas.
- Keserű epe a lelkem, de ki kell mondanom: az Ősök ellen csak az ármányban és a cselvetésben
bizakodhatunk. Lassan ölő méregként pusztítjuk el őket: kihasználjuk a belviszályaikat, rajtaütünk a
gyengéken, elaltatjuk az erősek éberségét. Amíg ártalmatlan férgeknek hisznek minket, egy hajdan-büszke
nép ronccsá tiport maradékainak, nem törődnek velünk; és nem törődnek azzal a három-négy testvérükkel
sem, akiknek minden évszázadban nyoma vész. Ám egy úmahtar mindezt megváltoztatná. Az Ősök
emlékezete hosszú: nem felejtették el még Malliort és a Kilencek bukását...
A primortel ajka néma fohászt mormolt. Nem a Kosfejes Urat kereste imáival, s nem is valamelyik
sötét angyalát a Káosz-szekták urai közül. Rég porrá lett halandók előtt rótta le tiszteletét, akik mind hozzájárultak az elszórt tudásmorzsák összegyűjtögetéséhez, noha nem volt - nem lehetett - fogalmuk róla,
micsoda szolgálatot tesznek ezzel a rendnek majdanán. Nélkülük nem rendezhette volna ragyogón
csillámló táblaképpé a szanaszét heverő mozaikköveket; nem, fejthette volna vissza a bilincsbe vert szív
talányát, nem lelte volna meg a Könnyűléptű Nép titkaihoz vezető ösvényeket.
Köszönöm, testvér! - mondta az ismeretlen notatornak, aki elfogadta Káosz-Abbog zsigerelőinek
kezéből a kontraktusért ajánlott értéktelen kacatokat. Megszorította a három mortel kezét, akik öngyilkos
küldetésben az életüket áldozták egy tetovált ábra magyarázatáért. Átölelte a reszketegmentort, aki
jósálomért fohászkodott Ranagol nagyúrhoz, majd elmetszette torkát a kosfejes oltáron. Hosszan nézett
szemébe az ifjú vadásznak aki három hétig sorvadt az üvegbarlang mélyén, de nem adta magát az enyhet
ígérő halál kezére, mert tudta jól, hogy vele pusztulna titka is. Biztosította róla a kérges szívű primoculist,
hogy nyargalói nem hullatták hiába vérüket a Rőt Vidéken. Legvégül köszvényes mesterének alakja
bontakozott ki a sűrűn gomolygó szellemködből; s amint fejet hajtott előtte, a szeme sarkából látni vélte,
hogy a félelmetes aggastyán elmosolyodik.
Amikor aztán végére ért a tiszteletadásnak, harmadik szemét az ég magasára emelte, és büszkén
megnyitotta magát a Kosfejes Úr előtt.
Vyergas vagyok, primortel a Fekete Özvegyek között. Ajka mozdulatlan maradt, szavai mégis
messzire visszhangoztak, szivárványhullámokat vetettek a titkos síkokon. Szolgád a földön és majdan az
Égi Honban, nagyúr. Törvényeid értelmében nem feledheted el többé a nevemet; s mert vadász vagyok, a
harcosok jogán igényt tartok a trófeámra!
- Eleget beszéltem. Ha ennyi szó kevés volt, több sem volna elegendő. Azt hiszem, érted már, mi
történt hercegatyámmal, amikor álmában meghallotta Mallior kacaját. Nem mi taszítottuk ki házunkból.:
ő emelkedett fölénk, mint minden úmahtar. Az Ötödik Domb tilalmas hely lett számára, és a Könnyűléptű
Nép minden szülötte messzire menekül a tekintete elől. Fürkészeink szerint akiknél nincs jobb a világon,
sem a Birodalomban, sem azon kívül - a Belső Tartományokba indult, Sramsass-Dakqín és HnumthorOrre felé, ahol az Ősök nagyjai honolnak. Magára maradt; de az Éjben Kacagó akarata munkál benne,
és ha nincs más választása, egyedül fogja kirobbantani a háborút. Mi nem onthatjuk vérét, hiszen
kalahoránk kelt új életre benne, akire istenkáromlás lenne fegyvert emelnünk. Ám valakinek utána kell
erednie, akár a Tiltott Határokon túlra is; mert ha nem hal meg mielőbb, olyan förgeteg szakad a
Birodalomra, amit talán a Kosfejes Úr maga sem fékezhet meg többé...
Vyergas felsóhajtott, a bazaltkőből csiszolt asztallapra dőlt; megtámasztotta rajta magát a
könyökével. Fáradtság sajgott a csontjaiban. Homlokát nyúlós veríték áztatta, tüdejébe zihálva tódult a
levegő; úgy érezte, mintha az imént nyert volna győzelmet egy vérre menő viadalban. Bizonyos
értelemben igaza volt. _
Hirtelen rádöbbent, hogy az elf a válaszára vár, immáron percek óta, a fajtájára jellemző
türelemmel. Felnézett hát, de halandó szemét nem nyitotta ki. Tíz hosszú szívdobbanásig gyönyörködött a
rúnákkal vésett ezüstpókon keresztül a karcsú alakot körbenyaldosó azúr lángnyelvekben.
Ügyesen forgott a nyelved, úmahtar, gondolta elismerően. Hazug szó alig hagyta el az ajkadat, s
csak azt hallgattad el előlünk, amit muszáj volt. Nem vagy te őrült, soha nem is voltál; a kalahorád talán
igen, de a halandó éned megőrizte a józan eszét. Meg sem fordult a fejedben, hogy nyílt háborút hirdess
az Ősök ellen. Néped épsége mindennél fontosabb; így hát a piszkos munkát inkább másokkal végezteted
el. Hány Szabad Rendet uszítottál már a nemlétező préda után, úmahtar? Hány vértestvériségnek fizettél
Sestian herceg fejéért, aki bizonyára békében ül a palotájában, s minden parancsodnak vakon
engedelmeskedik, mióta megjelent az arcodon a sorsjel? Vajon elegendően vannak ahhoz, hogy a Belső
Tartományok felbolyduljanak a vadászcsapatok léptei nyomán?
Sárga láng lobbant Vyergas arcában, ahogy kinyitotta jobb szemét; az asztrálvilág képei
elmosódtak, belefakultak a háttérbe.
Nem, nem hiszem; különben nem jöttél volna el hozzánk. Tudtad jól, hogy a környező
tartományokban mi vagyunk a legjobbak, s itt vállalod a legnagyobb kockázatot. Mégsem haboztál, mert
égető szükséged van minden vadászcsapatra. Rengeteg halandó lábnak kell ahhoz a Belső Tartományok
földjét tapodnia, hogy az Ősök fölneszeljenek rá lomha álmukból. Grandiózus terv, de nem
kivitelezhetetlen. Ha ezer vagy tízezer vadász kelne át egyszerre a határokon, az Ősök bizonyára azt
hinnék, hogy hadat üzentünk nekik.
A szakállas primortel feltámaszkodott, roppanva kiegyenesítette derekát.
Velünk akartad megvívatni a mocskos háborúdat, úmahtar. Pontosabban az első csatáját, hisz
tisztában vagy vele, hogy az Ősök haragja napok alatt elsöpörné valamennyi Szabad Rendet. Utána kik
következtek volna? A Káosz-szekták, a hegyi törzsek vagy a démonidézők titkos klánjai? Megkörnyékezted
már a vezetőiket, úmahtar?
Aurri egyenesen a szemébe nézett. Jégkék tekintete hidegen égetett, akár a húsba hasító acél.
Türelmem fogytán, primortel - mondta nyugodtan.
- Mi a válaszotok?
Comtur?
A préda a tiéd, Fra Vyergas. A mester ritkán szólította nevükön alárendeltjeit; az elismerés jele volt
ez tőle: Öld meg!
Shaka'thorr.
Salak csikorgott Vyergas torkában, folyékony parázs marta hólyagosra nyelvét. A hatalomige
dörögve süvített át a levegőn, egyenest az asztal túloldalán ülő elf felé; az útját álló gyertyatartó fémes
reccsenéssel szilánkokra hullott, az önálló életre kelő lángok ijedt szentjánosbogarak gyanánt rebbentek
szerteszét. Aurri felhördült, s hanyatt zuhant a bazaltkoloncról, mintha villámcsapás sújtotta volna mellbe.
Estében még látszott, ahogy homlokári megvonaglik a bilincsbe vert szív, vörhenysárga tűz gyúl a
béklyótagok között.
A primortel felpattant, két kezét messzire tartotta magától. Tenyerébe égetve egy-egy rúnajel
vöröslött; másukat egy sequor s egy mara-sequor viselte markolatán, melyek most kétszáz lépésre
pihentek innen, fekete selyembe csavarva, az alvócellájában. Elvakkantott egy szót, s nyomban megérezte
markában az ismerős súlyt; jel simult jelhez, ahogy kurta ujjai összezárultak a semmiből nála termő
vadászpengék keresztvasa alatt.
A kanóc nélkül röpködő gyertyalángok hullámos barázdákat szántottak a sötétség bársonyára.
Vyergas baloldalán áttetsző kontúrokba simult a levegő; a halovány körvonalak lélegzettel és szívveréssel
teltek meg, ahogy a kísérő messorok egyike átlépett a testetlen szellemek síkjáról az anyag világába. Ő
volt a leggyorsabb, de két társa sem késlekedett soká; éterből acéllá változó pengék villantak a primortel
előtt, a jobboldalán.
Aurri arca bukkant föl az asztaltömb mögül. Sápadtabb volt, mint szokott, s bal orrlyukából vékony
csíkban vér szivárgott; nem rossz ahhoz képest, hogy most kásává roncsolt koponyával kellene a földön
hevernie.
Az elülső messor sebes iramodással szökkent felé, mara-sequorja halálos ívet harapott a
félhomályba. Az elf éles, dallamos hangot hallatott, Vyergasnak csengve sajdult meg tőle a dobhártyája.
A rohamozó vadász lendülete megtört, csuklyás feje természetellenes szögben hátranyaklott; néma
sikolyra nyíló szájából keskeny vérsugár lövellt magasba, ahogy lábai kiszaladtak alóla, s teste puffanva
elterült a hatszögletű köveken.
Társainak arcizmuk sem rándult a sorsa láttán. Elhúzódtak egymástól, hogy kétfelől kapják közre az
ellenfelet; rövidebb pengéjük rézsút a mellkasuk előtt, a hosszabbik lefelé fordulva az elf felé mutat,
hegye majdhogynem a padlatot súrolja. Vyergas kiugrott közülük, fenn termett az asztallap közepén; a
lángok visszfénye visszaverődött fegyvereiről, sárga lobot vetett kegyetlen cápavigyorán.
Aurri ráemelte jégkéken szikrázó tekintetét.
- Quiasse amaren si ullo l'imenel - szólott ősei nyelvén. Örvend a szívem véred látásának.
Rátette kezét a hatszöglétű asztalkőre. A fekete bazalt beroppant az ujjai alatt, tükrösre csiszolt
színén finom szálú repedések pókhálója futott szét. Úgy markolta meg a hatalmas sziklatömböt, mintha
tollpihével tömött vászonzsák lenne csak. Fél kézzel megemelte a felé eső oldalát, előbb mellmagasságba,
majd a feje fölé; aztán nekiveselkedett, és lökött rajta egyet.
Vyergas megcsúszott a sima kövön, egyensúlyát vesztette. A sequort eldobta, fogódzó után kapott,
de hiába; a következő pillanatban az ülepén szánkázott lefelé a lejtős felületen, s tompa csattanással
vágódott a padlónak. A roppant asztallap az élén imbolyogva magasodott fölébe, sötéten és fenyegetően,
kioltva a riadtan cikázó fényszikrák világát.
A két messor kétfelől rontott Aurrira, ugyanabban a pillanatban, amikor a hosszú, nyúlánk ujjak
eleresztették a bazalttömb szélét. Egyszerre mozdultak, egyszerre lebbent meg köpenyük szárnya,
egyszerre villant előre pengéjük, mintha csak egymás tükörképei lennének. A szívük is egyszerre dobbant
utolsót, amikorra kecses hajlású hiequar kiröppent hüvelyéből, s széles ívben körbeszisszent, forró-vörös
cseppeket fröccsentve szerteszét. Átvágott torokkal roskadtak térdre, ernyedő kezükből kifordulta
verítékáztatta kardmarkolat.
Vyergas a hátára hemperedett, még épp idejében, hogy lássa, amint a roppant kőtömeg átbillen a
holtponton, és zuhanni kezd felé. Késő volt már kigördülni alóla; az irtózatos súly úgy fogja szétlapítani,
akár héjatlan bogarat a rátipró csizmatalp.
Mély, öblös hangokat öklendezett fel a gyomra legmélyéről; sós vér kísérte őket, és szúró fájdalom.
A hatszögletű bazaltlap legyezőszerűen nyíló porfátylakká robbant szét fölötte, szárazon csikorgó nesz
kíséretében, mint amikor kő súrlódik kövön. Finom szemcsés, fekete eső szitálta körül a primortel alakját,
amint villámsebesen felegyenesedett, s mara-sequorját támadóállásba emelte:
Aurri Ly'Shematenel szembetáncolt vele; j égkék tekintetében halál mosolygott, a vízfalevél-forma
hiequart könnyed csuklómozdulattal a vadász szívének szegezte.
- Ketten, ahogy illik - suttogta lágyan, már-már érzékien.
- Ahogy illik - bólintott rá Vyergas.
A bazaltbástya oldalfala beroppant a lőrés körül, a tarjagosra törő kváderkövek húspéppé
morzsoltak újabb két saggitort. Fölöttük a mellvéden egy harmadik egyensúlyát vesztette, amikor a
támpillér megrogyott alatta; íját eldobva kapott a pártázat után, későn. Kurta sikolya tompa puffanásban
végződött az udvar kövezetén.
Az Aurrit kísérő tizenkét elf körkörös alakzatba rendeződött a koponyadíszes kút körül. Összefaroló
lovaik szilajul fújtattak, a szemüket forgatták; megvadította őket a méregbűz, amely az előttük ágaskodó
bannarák cseppfolyósan vonagló testéből áradt. Nyílvesszők sziszegtek a kis csoport felé minden
irányból, hogy a közelükbe érve elakadjanak a levegőben, majd ártalmatlanul a földre hulljanak. Nem
közönséges harcosok voltak ők: Mallior tizenkét apostola, a kiválasztott kevesek, akikkel az úmahtar
elsőként osztotta meg az elveszett tudást. Az ajkukon zengő hatalomigék bántó dallamú kánonba
mosódtak össze, vibrálásba hozták a rendház alapköveit, párává gőzölték a fekete égből szemerkélő esőt.
Az egyik bannara hínárzöld iszaptócsává folyt szét, s felszívódott a hatszögletű bazaltlapok
illesztékeiben. Néhány szívdobbanásba telt csupán, míg a föld alatt átszivárgott a tizenketteket övező
láthatatlan védőaurán; aztán nedvesen cuppogva a felszínre tört, s képlékeny állábaival óriás ázalagként
tapasztotta körül egy riadtan felnyihogó ló hófehér nyakát. Az egyik elf metsző hangon felvijjogott. A
méreglény teste kocsonyás cseppekké fröccsent szét a belécsapó hatalomigétől; ám a büszke állat ekkor
már habzó pofával vergődött a földön, s ha lovasa nem rántja ki elég fürgén lábát a kengyelből, az
elzuhanó csatamén maga alá temeti.
Az elfek közül hárman rövid, éneklő kiáltásokkal söpörték körbe a várudvart; a dallam végét
furcsán felcsapták, cifrázás nélkül, idegen hangsúllyal. Néhány bannara lucskos zajjal magába roskadt,
állábaik szegélye kiszáradt és feltöredezett, mintha tűz perzselte volna meg őket. A megmaradtak közül
azonban egyre többen láttak neki, hogy átszivárogjanak a kövezeten, s a nyirkos-puha talajban
tapogatózva elinduljanak az ellenség felé. A túlélő saggitorok megkettőzték erőfeszítéseiket, hátha sikerül
túlterhelniük lövéseikkel a védőaurát, amit immár hárommal kevesebb torok bűvigéi tartottak fönn. Sebes
léptekkel cikáztak a félhomályos gyilokjárón, futtukban bocsátva útra horgas nyílvesszeiket; rájöttek már,
hogy meglapulni, leshelyre húzódni ebben a csatában biztos halált jelent.
A hátasát vesztett apostol kirántotta ívesen hajló pengéjét, s kiszökkent társai gyűrűjéből az
esőáztatta kövekre. Testét azonmód három nyíl járta át; a negyediket sikerült a hiequarral félreütnie.
Megingott, féltérdre esett, de nem zuhant el. Ekkor csaptak le rá a bannarák.
Mohón fröcsköltek elő a föld alól, a bazaltlapok repedéseiből; némelyikük előbb teljes
magasságában fölágaskodott, akár valami cseppfolyóssá bűvölt lantvitorla, s csak utána roskadt
áldozatára förtelmes cuppogással. Az elf összerogyott a súlyuk alatt, a miazmásan gőzölgő massza tetőtől
talpig elborította. Kocsonyás állábak türemkedtek be orrán, száján; maró váladék szivárgott a bőre
pórusaiba, a nyílvesszők ütötte sebekbe. Elméje azonban nyugodt maradt, miközben kitapintotta a
bannarákban gyökerező szellemhorgonyokat, megkereste azt a pontot, ahol összefutnak, majd követte
őket egészen az eredőjükig.
Még pislákolt benne az élet halvány lángja, amikor megtalálta, amire számított. Ajka már nem volt,
de a nyelvéből még maradt valami; felhasználta hát a méregtől szörcsögő tüdejében tartalékolt levegőt, s
a láthatatlan mentálfonál mentén útjára bocsátotta utolsó hatalomigéjét.
A boltozatos bazaltcsarnok mélyen a föld alatt húzódott, titkos bejáratát félelmetes strázsák
vigyázták mind az anyag, mind a szellem síkjain: Nem tárgyalóterem volt ez - kívülálló ide sohasem
juthatott be -, s nem is kincstár vagy áldozati szentély, bár a kosfejes oltár innen sem hiányozhatott. A
Khat'ul'Naathum két rangos beavatottjának szolgált otthonául, akiknek szolgálatait a rend nem
nélkülözhette; ám ahhoz túl sebezhetők és értékesek voltak, hogy kitegyék őket a fegyveres harc
kockázatának.
Az egyikük karószikár, kecskeszakállas öregember volt, sötétzöld sujtásos kaftánban, arcán
savmarás nyomaival. Most keresztbevetett lábbal ült néhány selyemmel húzott vánkoson, egy félkupolás
falifülkében, melyet Káosz-Sraddhu kőbe vésett domborműve díszített. Ranagol angyala úgy ölelte körül
csápokat sarjadó bazaltkarjaival, mintha védelmezőn a keblére akarná vonni; aszott kezét tenyérrel lefelé
a térdén nyugtatta, hólyagos hegektől elrútított arcára mély ráncokat árkolt az erős összpontosítás. A fülke
előtt jókora, vaskos munkaasztal állt, rajta kémcsövek, retorták, üvegnyakú lombikok. Kétoldalt a fekete
falakat hosszú fapolcok borították, sűrűn telezsúfolva mindenféle tégellyel, szelencével, ládikóval és viaszosvászon tasakkal. A levegőben kránkő és marólúg bűze terjengett, olajos növényi esszenciákkal és
más, nehezen meghatározható illatokkal elegyesen.
A másik beavatott á csarnok túlsó végén tette a dolgát, a lehető legmesszebb a vörhenyes fénnyel
izzó kohótól, ahová a társa szokott időnként elvonulni, öntöttvas üstökkel és szelepes lepárlóedényekkel
felszerelkezve. Ő is kaftánt viselt, de bíborsujtásosat; fejét kopaszra borotválta, ferde vágású szeme köré
indaszerűen egymásba fonódó mintákat festett. Azért nem a tetoválótűhöz folyamodott, mert minden feladata más és más ábrákat követelt még; a mostani például a sötétség, a harag és a testből tovaszálló lélek
szimbólumát, valamint bizonyos tiltott .neveket. Azonnal munkához látott, amint megkapta a comtur
szellemparancsát; ám az ilyesfajta dolgot nem szabad elsietni, mert beláthatatlan következményekkel
járhat. Akármi történjen kint a rendház udvarán, neki még legalább egy fertályórára lesz szüksége, ha
legalább az alapvető biztonsági előírásokat be akarja tartani.
A kopasz férfi egy kénnel és foszforral felvázolt pentagrammában állt, amelynek csúcsain fekete
gyertyák égtek, metszéspontjain pedig alacsony bronzserpenyők ontották az asa foetida orrfacsaró bűzét.
A baloldalt magasodó kosfejes oltáron törékeny kis test feküdt némán és mozdulatlanul, a széles pengéjű
áldozati tőr mellett. A hatszögletű kőtömb oldalán csordogáló vérnek még nem volt ideje megalvadni;
alig néhány perc telt el azóta, hogy a beavatott az ősi törvények értelmében felnyitotta az újszülött kisded
mellkasát, és elfogyasztotta a zsenge bordák közül kitépett szívet. Most a rituális idézőlitániát mormolta
monoton hangon, újra meg újra elismételve az előírt formulákat és névtagadásokat.
Halk, nedves pukkanás hallatszott a csarnok túlsó vége felől, mint amikor mérges pöfetegre lép az
ember, vagy tűvel kiszúrnak egy gennytől feszülő tüszőhólyagot. A bűvigéket kántáló beavatott
szemöldöke ráncba szaladt: Elgondolhatatlan ugyan, hogy az ellenség utat találjon erre a félelmetes
erőkkel védett helyre, de ha mégis... Szörnyűséges dolgok történhetnek, ha a szertartás menetébe valami
hiba csúszna.
A folyamatos zsolozsmázást szívdobbanásnyi időre sem hagyta abba, annyit azonban
megkockáztatott, hogy megemelje tar fejét, s egy futó pillantást vessen az iménti hang irányába. Amit
látott, attól még jobban elmélyültek homlokán a gondterhelt barázdák.
A zöldsujtásos kaftánt viselő beavatott alteste továbbra is mozdulatlanul ült a selyemvánkosokon,
még a két keze is ugyanolyan nyugodtan pihent a térdén deréktól felfelé azonban egyszerűen nem létezett
többé. Illetve ami kevés megmaradt belőle, az véres mocsokká kenődött szét a fülke dombormíves falán.
Káosz-Sraddhu agyaras pofája lucskos-rőten vigyorgott az elárvult lombikokra, tüskés csápkötegei végén
meghatározhatatlan húscafatok lógtak.
A kopaszra borotvált férfinak szeme sem rebbent, ajka tovább mormolta az egyhangú litánia szavait.
Szóval á méregmestert, a rettegett bannarák parancsolóját utolérte a sorsa. Most, hogy elvesztették az irányító akaratot, cseppfolyós teremtményei odafönt az udvaron ernyedten szétolvadnak majd, egybefolynak
a nyúlós sárral és az esővíz tócsáival.
Nem baj. Annál fontosabb feladat hárul őrá, a démonlovasra.
A boncmester tisztelettudó főhajtással lépett be a toronyszobába, az imbolygó árnyak és a szüntelen
háborújukat vívó szagok közé. A sárkánykarmos falikarban füstölögve lobbant utolsót a csonkjára égett
szövétnek, amit még Vyergas hagyott itt, nemrégiben tett látogatásakor. A baldachinos ágy selyemfüggönyei mögött ott reszketett a comtur undok váladékokban ázó, iromba hústömege.
Légy üdvöz, Fra Thuzdag. Elhoztad mesterséged szerszámait?
A skarlátruhás jövevény bólintott, s baljával öntudatosan végigsimított mellig lógó harcsabajszán.
Tagbaszakadt, öles termetű férfi volt, medvényi vállával csak oldalazva fért be az-ajtónyíláson; hivatása
roppant testi erőt igényelt, hisz egy személyben látta el a rendház sebészének, hóhérának és
kínzótudorának feladatait. Darabos vonású arcán minden lélegzetvételre megvonaglottak a szertekígyózó
varrathegek; tanoncidejének emlékét őrizték, amikor mestere rajta mutatta be növendéktársainak a
különféle vágásokat és metszéseket.
Jobb kezében vaskos byzonbőr táskát tartott, mely foltosszürkére kopott a hosszú évek során;
alaposan lehúzta a karját, látszott rajta, hogy még az ő bivalyerejével sem lehet könnyű cipelni. Amikor
megemel te, a kifakult bőr alatt fém koccant fémnek bántó csendüléssel.
Az ágyhoz lépett, félrehúzta a finom szövésű függönylepleket. A táskát a comtur mellé tette az
összemocskolt selyemlepedőre, s bütykös hüvelykujjával felkattintotta a zárját. Aztán nekilátott, hogy
előszedje a műszereit; a tenyérnyi széles bonckéseket, a hosszú, horgas végű tűket, a szakállas
acélkampókat, a borotvamosolyú szikéket, a csíptetős húsfogókat, a gyémántfejű fúrókat, a hegyesre
köszörült nyársakat, a savval maratott csontfűrészeket:
Igyekezned kell, intette a higgadt szellemhang. Most minden perc drága!
- Nem lesz okod csalódni a tudományomban, comtur - felelte a skarlátruhás boncmester. Azt
fölöslegesnek vélte hozzáfűzni, hogy a sietség jóval gyötrelmesebbé teszi majd a műveletet.
Nyugodt, magabiztos mozdulatokkal látott munkához. Vastag, durva ujjai megdöbbentő
könnyedséggel és szakértelemmel forgatták a szerszámokat. Először azt a pontot kereste meg a comtur
testén, ahol valaha a nyakának kellett lennie; a petyhüdt redőkbe gyűrődő; nyirkos hájrétegeket a válltájék
csontjaiba csavarozott tartópofákkal fogatta hátra. Aztán kiválasztott a kései közül egyet, amelynek az
alakja ökörnyelvre emlékeztetett: kurta volt, kétélű, s a tövénél csaknem fél arasz széles, ám a hegye felé
gyorsan elkeskenyedett. Összehúzott szemmel felmérte az irányt és a mélységet- két szívdobbanásnyinál
több időt nemigen fecsérelt rá -, majd megejtette az első hosszanti bemetszést.
A fakórózsaszín hústömeg görcsös vonaglással összerándult, mikor a borotvaéles penge
beléhasított. A pikkelylebernyeges bőr szisszenve szétnyílt, habos vér bugybórékolt fel alóla. A
boncmester mélyebbre vágott a késsel, s szabad kezével a vöröslő résbe nyúlt, hogy kitágítsa; a sebszélek
rögzítésére szolgáló csíptetőt jobb híján a fogai közt tartotta készenlétben. Újabb rángás futott végig a
comtur formátlan testén; üvölteni nem üvöltött, hisz nem tudott mivel.
A szikék, a fűrészek, a nyársak éppen ezt voltak hivatva megváltoztatni.
Fra Thuzdag módszeresen dolgozott tovább, sietősen, ám fölösleges kapkodás nélkül. Vaskos,
szőrös karja csakhamar hasonult a hátratűrt köntösujj skarlátszínéhez; harcsabajszának lelógó szárai
átnedvesedtek, csatakossá váltak. Az inakba metsző, csontokba harapó szerszámok mégsem csúsztak meg
a kezében egyetlenegyszer sem; úgy értette a munkáját, ahogy rajta kívül kevesen.
Hogy a hangszálakhoz férjen, előbb el kellett távolítania egy lilán lüktető verejtékmirigyet, amely
öklömnyi daganattá rákosodott, s torzan vonagló nyúlványok sarjadtak belőle. Megtette, s a végén kurta
csuklómozdulattal a szoba sarkába csapta, ami az ujjai közt maradt. A hangszálak befűződtek és
összecsomósodtak az irdatlan test mélyére temetve; lószőrből kötött ecsetekkel és leheletfinom
rézhuzalokkal tisztította meg őket.
Ezután az arc alsó fele következett, ami már keményebb diónak bizonyult. A kráteres közepű
húskinövések levagdosásával hamar végzett, s az sem esett nehezére, hogy felmetssze a hosszanti
ráncokban egybenőtt ajkakat; a garat és a gégefő között az összeköttetést egy kéngőzben preparált
darunyelőcsővel teremtette meg. Az viszont már komolyabb gondot jelentett, hogy a comtur állkapcsa az
évek folyamán vad burjánzásnak indult, csontömlenyek és szerteágazó tövistenyészetek alakultak ki rajta,
a fogak pedig ujjnyi hosszú gyökércsápokat eresztettek: Végül kénytelen volt lenyúzni az egész alsó
arcot, majd szögletes dörzsvasat vett elő, és tövig reszelte a feleslegesnek ítélt részeket.
A nyelv maradékát még neki is elég sokáig kellett keresgélnie; tán három percébe is beletelt, míg
megtalálta a feketére sorvadt izomköteget, amely baloldalt csomósan ránőtt az ínyhús belső ívére.
Vékony tűket szúrt alá, előbb kettőt, aztán négyet, végül tizenhatot, és addig mozgatta fel-alá kiálló
végüket, míg a nyelvet rögzítő rostok sorra elszakadtak, a legszívósabbakat kivéve. Ezeket a legélesebb
szikéjével vágta át, gondosan ügyelve közben, nehogy elmetélje a hátsó mozgatógyökeret is. Utána
óvatosan, egyenként kihúzta a tűket, és puha keszkenővel kitörölte a szájüreget.
Már csak egyvalami volt hátra, afféle utolsó simítás, a kész mű megkoronázása. A boncmester
bütykös ujjai finom mozdulattal kicsippentették a comtur orrnyílásából a tápvezetéket, és könnyedén
félrepöckölték a fal mellé. A birkabél csőből sűrű, sötét folyadék ömlött, s csakhamar cukorkristályos
tócsába gyűlt a toronyszoba padlatán.
A tagbaszakadt férfi, akinek immár nemcsak a köntöse ragyogott skarlátvörösen, hátralépett az ágy
mellől, s letörölte homlokáról a vérrel elegyes verítéket. A füstölőserpenyőkben izzó parázs fényében
büszkén mérte végig mesterét és parancsolóját, a csatakos selymek között vonagló comturt. Megtette
kötelességét, ahogyan megkövetelték tőle; nem vallott szégyent nehezen szerzett tudományával.
- Hívd a szolgákat! - gurgulázta a rendház ura vérhabot fröcsögve. - Vigyenek az alsó balkonra!
Nem a szellem igéivel szólott, hanem a saját hangján, a saját feketére aszott nyelvével - hosszúhosszú évek óta először.
Haragos sziszegés kélt a leshely sötétjében; a magatehetetlen düh hangja volt ez, a zsigerekben
rekedt ölnivágyásé, amely csak gyűl-gyülemlik az ólomlábakon vánszorgó percek során, csillámló
verítékgyöngyöket fakaszt a lüktető halántékokon, s vörös leplet borít az ádázul izzó szempárok elé. A
Khat'ul'Naathum vadászait veszedelmes dolog volt megváratni ütközet előtt, ha már beszedték a
gondosan kiadagolt harci ajzószereket, s ereikben szerteömlött az izmokat-inakat feszítő méregparázs.
Hiába edzették őket a szellem tudományára, hiába ismerték a vak ösztönöket megzabolázó meditációs
technikákat; az akarat acélbilincse csak bizonyos ideig tudta féken tartani a testükben keringő folyékony
lángokat, a bestiális lázat, amelynek tüzében alaktalan salakká olvadt össze élet és halál. Most már
minden pillanatban félő volt, hogy valamelyikük elvéti a gondolatban ismételgetett mantra következő
szavát, s őrjöngő tombolásba tör ki, mit sem törődve véle, hogy baráti vagy ellenséges vért ontanak-e
kardcsapásai.
Az alacsony, izmos vállú nő tudta jól, hogy vissza kellene valahogy fognia a keze alá rendelteket, de
nem tehetett semmit, hisz maga is fogcsikorgatva küzdött a bensejét szaggató tűzvésszel. Ráadásul az ő
szervezetének eggyel több ajzószer hatásával kellett birokra kelnie; a többiekkel ellentétben ő a fekete
henna porrá tört magvaiból is felszippantott egy keveset, hogy kiélesítse rejtett érzékeit; s tisztábbá tegye
látását a szellem síkjain. Most veszett kutya módjára morgott és kaffogott; habos nyál csorrant ki szája
sarkán, ahogy vadul hányta-vetette borotvált fejét, a rendház udvaráról feléje szálló képek után kapkodva.
A saggitorok benyomásai zűrzavarosak és elmosódottak voltak: arcokba csapó esőpermet, jégrianásként
végigfutó repedések a bazaltfalakon, lovasok csoportja odalent a kút körül, a hátravont íjhúrban feszülő
erő, rőt lobbanás, szétnyíló bordák között kivirágzó fájdalom...
A nő hátravetette tar koponyáját, vicsorogva felvonított; a nyújtottan szűkölő hanghoz sorra
csatlakoztak a többiek, a sűrű félhomályban szemek parázslottak, fogak villogtak, ráncokba gyűrődő
ajkak reszkettek vérre szomjazón. Hozzájuk csupán a töredéke jutott el annak, amit a vezetőjük érzett és
látott: színevesztett minták, elbomló formák, értelem nélkül való illatok. A testvéreik között arató szapora
halált éppen csak megérintették, nem ürítették fenékig a keserű bürökkel habzó poharat; ahhoz azonban
ez is elég volt, hogy felkorbácsolja agyukban a láz vörös hullámait, s egyetlen lendülettel a tajtékos őrület
peremére sodorja őket.
A nő izmos testét vasszögekkel kivert bőrpántok fonták körül szerteágazó hurkokban, a legtitkosabb
hajlatokra is védelmezőn rásimulva; apró, feszes melleit azonban szabadon hagyták. Most két kézzel
megmarkolta az egyiket, s mind a tíz ujjával a saját eleven húsába vájt. Feketére lakkozott körmei
félarasznyi hosszúak voltak, és ugyanolyan élesek, mint a derekán lógó vadászkés. A kibuggyanó vér sós
szaga még jobban megvadította, ám a tízfelől belényilalló fájdalom erőt adott neki, hogy megszakítsa a
kapcsolatot.
Sokat amúgy sem ért volna már vele; a tudatában felvillanó képek egyre kaotikusabbá és
átláthatatlanabbá váltak. A közvetítőt, a toronyszobája magányában haldokló comturt; aki idomtalanra
puffadt pókként gubbasztott az egész rendházat beszövő mentális háló legközepén, iszonyatos kínok
gyötörték. A fájdalomérzethez a skarlátruhás boncmester látványa társult, szőrös kezében pengék és
horgok villogtak. A comtur elméje volt a legtágabb s a legcsiszoltabb valamennyiüké közül, ám jelen
helyzetében még neki is mindinkább nehezére esett megszűrni és továbbítani az ezerfelől áradó
benyomásokat. Ha képes a tagolt gondolatokra; a nő most bizonyára keserű elégtételt érez. Amikor
engedélyezték neki a szólást a vadásztanácsban, mindig rámutatott erre a gyönge pontra: a
Khat'ul'Naathumnak nem voltak cascadisai, mentális kapcsolattartásra szakosodott specialistái, mint a
régi rendjének.
Igen, sura'shtak volt, becsületgyermek: növendékévei első felét a Holdralépők egyik
erődkavernájában szolgálta le, s ott esett át a vadászok alapkiképzésén is. Jónéhány emléket őrzött
azokból az időkből, fájókat s örömtelieket egyaránt, melyek mind kitörölhetetlenül belevésődtek agyába s
idegeibe. Így például ő nem páros kardokkal harcolt, a Birodalom ősi hagyományai szerint, hanem
csatabárddal és nagy ritkán késsel; ez utóbbit általában a kegyelemdöfésre s a trófea megnyúzására
tartogatta. De a Holdralépőktől kapta örökül a spirálisan kígyózó hegtetoválásokat is, a bonyolult
kacskaringókba rendeződő mintázatot, amely az egész testét beborította, tar feje búbjától a talpa
homorulatáig. Egynémely ábrának bűvös hatalma volt; a kettőshurok a bal mellén, amit most friss vér
áztatott, ellenállóbbá tette a mérgekkel szemben; a köldöke alá hasított hullámvonal pedig meddővé
szárította a méhét, viszont egyszer s mindenkorra felmentette a havi tisztulás nyűge alól. Asszonyból
enélkül nem lehet teljes értékű vadászt nevelni, magyarázta neki annak idején a rend rituálisan
megcsonkított tűmestere.
A tűmester kettéhasított fejjel végezte az erődkaverna romjai között, akárcsak a Holdralépők
pricomtura, válogatott testőreivel együtt; a Fekete Özvegyek gyilkos és váratlan rajtaütése még annyi időt
sem hagyott nekik, hogy - vereségüket elismervén - végrehajtsák magukon a torokmetszés szent
szertartását. Halálba küldték a közönséges növendékeket is, a fiatal kamaszleánynak és két fiútársának
azonban megkegyelmeztek; az Ősök vére túl ritka portéka, semhogy oktalan elfolyassák. Sura'shtaknak
nyilvánították hát mindhármukat, s befogadták őket a saját rendjükbe. Az egyik fiú túl makacsnak
bizonyult, ezért meghalt; a másikról kiderült, hogy a tűmester bosszúcsírát metszett a bőrébe, s a
felismerés a Khat'ul'Naathum oktató mentorának az életébe került. A lány azonban nem viselt ilyen jelet
magán, s idővel asszonnyá, vadásszá serdült. A harcokban tanúsított állatias vadsága tekintélyt szerzett
neki; a férfiak, akiket a comtur szava az ágyába parancsolt, engedelmeskedtek ugyan, ám nem mindig
örömmel. Huszonéves korára elismert mortel vált belőle; noha az Ősök nyelvét barbárul kerékbe törte,
hatalomigéi mégsem vesztettek erejükből, a velük járó kínokat pedig gyűlölködő vicsorral fogadta. Talán
ezért nem nyomorodott bele még a tiltott mágiába; meglehet persze, hogy a bőrén varasodó sebhelyek
nyújtottak neki valami rejtett védelmet, amelynek titka örökre sírba szállt a Holdralépők vén tűmesterével.
Halk, elkínzott vinnyogás hallatszott a sötétből. Egy fiatal sequator húzódott közelebb a borotvált
fejű nőhöz. Teljesen magánkívül volt: a szeme kifordult, a szája nyáladzott, alsó ajkát háromfelé harapta.
- Mortel... - nyöszörögte elcsukló hangon. - Mortel! Sor Udunn...
Az asszony viperatekintete rávillant; mélyzölden parázslott, akár a téboly üszke, vagy a mocsári láz.
- Mikor támadunk, Sor Udunn? - hörgött az ifjú fegyveres. - Vér szálljon a szádra, mikor?...
Ha eszénél van, ha gondolkodni tud, a vad szemű mortel talán válaszolt volna neki. Hogy a
támadásnak semmi értelme, amíg az elfeket védő láthatatlan aura fennáll. Hogy a közelébe sem tudnának
férkőzni az ellenségnek, az viszont véres rendet vágna közöttük hatalomigéivel. Hogy a comtur szigorú
utasítást adott: csak az ő személyes parancsára ronthatnak elő a leshelyről, ha beleőrülnek is.
Így viszont csupán annyit fogott fel az egészből, hogy a sequator megszólította, noha nem kapott rá
engedélyt. Hogy a nevén nevezte, pedig rangban messze alatta állt. Hogy kihívást intézett hozzá a többiek
előtt: kétségbe vonta véren szerzett tekintélyét, vitatta a falkavezér jogát, hogy döntést hozzon az ölés
mikorja és mikéntje felől.
Csatabárdja a lába mellett állt, a falnak támasztva, de a fiatal harcosból nem veszett még ki minden
alázat: addig nem merészkedett, hogy kivont fegyverrel közelítsen hozzá, páros pengéi a hüvelyükben
maradtak. Így hát Udunn is a pusztakezével kapott a nyakához; élesre fent körmei összezárultak az ádámcsutka körül. Más talán megelégedett volna egy egyszerű metszéssel, vagy a gégefő bezúzásával; a mortel
azonban alapos asszony volt: ő hosszában kitépte az ifjú egész torkát. Fojtott sziszegése alig hangzott emberinek, ahogy byzonbőr csizmája a magasba lendült, s teli talppal nekizúdult a fuldokló sequator
mellkasának.
A többi vadász egyszerre csaholt föl, amikor arcátlan társuk hanyatt zuhant a hatszögletű kövekre.
Fogak és pengék villantak hidegen; a sűrű homályban nem mindig lehetett egymástól megkülönböztetni
őket. A következő pillanatban az őrjöngő falka összecsapott az elesett ifjú fölött.
A mortel elhajította az ujjain lógó rojtos húscafatot, s hosszan, megigézetten meredt fekete
körmeire. Aztán sebhelyes ajka hátborzongató mosolyra húzódott, és lassan nekilátott lenyalogatni róluk
a vért. A sebesen föl-le járó kardokat, a posztóköpenyek sötétjét elmélyítő nedves foltokat, a tágra nyílt
pupillákban vibráló elragadtatást pillantásra sem érdemesítette.
Ettől majd megnyugszik a falka. Egy kis időre még.
Vyergas két kézre fogta a mara-sequort, függőleges tartásban az arca mellé kapta, és támadott.
Harántirányú vágást mért az elf halántékára, de csak a megsebzett levegő sírt fel panaszosan a pengeél
nyomán; Aurri kígyószerű fürgeséggel siklott félre a csapás útjából, s ,ívesen hajló kardja gonoszul
megvillant válaszul. Alattomos döfés volt, csekélyebb ellenféllel ott helyben végzett volna; a primortel a
baljára szíjazott alkarvédővel hárította, ám közben kibillent az egyensúlyából, s fél kézzel el kellett
engednie fegyvere markolatát. Az úmahtar habozás nélkül kihasználta előnyét, benyomult a résbe, újra
színt másodszor, harmadszor is. Vyergas védekezésbe szorult, hátrálni kezdett; előbb jobbra, majd balra
kapta szakállas fejét, hogy elkerülje a sötétségben szisszenő ezüstíveket. A rendben nemigen akadt hozzá
mérhető kardforgató, mesternek számított a mesterek között; csakhogy most olyan ellenféllel támadt
dolga, aki nem tizenöt éve gyakorolta a vívás művészetét, hanem több mint fél évszázada.
A halandó énje, legalábbis; mert hogy mi mindent tudhatott a harcról az Éjben Kacagó, aki az Ősök
legnagyobbjaival csatázott az óidőkben, abba belegondolni is szédítő volt.
Vyergas a bal ökle köré csavarta a köpenye szélét, és széles ívben az elf arca felé suhintott vele.
Hollószárny lebbent a fénypettyes éjszakában; a fekete selyemszövet aljába varrott ólomnehezékek a
jégkék szemeket keresték, hogy örökre kioltsák hideg világukat. A primortel arra számított, hogy Aurri
kitér vagy hátraszökken; mindkét esetben távolabb kerül tőle, s újra érvényre juthat a mara-sequor
nagyobb hossza. Az úmahtar azonban valósággal belelépett a csapásba, s kardja egyetlen villanásával
csonkára hasította a feléje szálló köpenyszegélyt. A selyemburokba zárt ólomgolyók suhogva tűntek el a
levegőben cikázó gyertyalángok között; gyors koppanások sorozata riasztott kongó ekhókat a láthatatlan
bazaltboltozat alatt.
Vyergas oldalra táncolt, s ezzel fél szívdobbanásnyi haladékot nyert. Gyakorlott mozdulattal fogást
váltott a mara-sequoron, alulról felfelé haladó ívben megpörgette, s zömök testének minden erejét
beleadva lesújtott vele. Durva, mesterkéletlen támadás volt, mellőzött minden rátarti finomkodást; a
Könnyűléptű Nép törékeny csontú, keskeny vállú gyermekei ellen mégis gyakorta hatásosnak bizonyult.
A hiequarok lávagőzben edzett pengéje kibírta ugyan a háromölnyi magasból rázúduló csapást, a
markolatot tartó kar azonban a legritkább esetben.
Acél csendült acélon, kéken izzó szikrazápor szaggatta a sötétség takaróleplét. Vyergas vágása
akárha sziklakövet ért volna; a keze könyékig zsibbadt belé, a visszarúgó markolatra tekert bőrszíjak
véresre horzsolták a tenyerét. Aurri a Könnyűléptű Nép hagyományos védőpózában állt, jobb térdét
megrogyasztva, bal lábát egyenesen kinyújtva hátrafelé; a levélforma kardot haránttartásban emelte
magasra, a penge hátulja az alkarjához simult. A primortel mintegy kábulatban könyvelte el magában,
milyen művészi tökéllyel igazodik a hiequar felépítése az elftest arányaihoz: a borotvára köszörült fokél
éppen a könyökénél vette kezdetét, még csak fel sem karcolta bőrét a hárításkor.
Hűs mosoly fodrozta az úmahtar ajkát. Emberbőr zekéjén gúnyosan zizegtek a hosszú gyöngyfonatok.
- A szívedet akarom - mondta tisztán érthetően. Aztán kurta, fülsértően magas hangot hallatott, akár
a vércserikoltás vagy az orkák vérre hívó füttyszava. Vyergas mellét pokoli görcs rántotta össze; mintha
valamennyi izma rácsomózódott volna a bordacsontjaira. Annyi ideje sem maradt, hogy felhördüljön,
mielőtt elzáródtak volna a légutai.
Védekezése teljesen ösztönös volt, nem éber tudata irányította; hanem a csupasz élnivágyás, az
emberfaj legmélyebben fészkelő és legellentmondásosabb szenvedélye. Ez vezérli a fuldokló reszketeg
ujjait az útjába sodródó uszadékfa felé; ez riasztja föl álmából az alvót, ha orgyilkos lépte neszez az
éjszakában; ez munkál a kínpadon vonagló rab zsigereiben, amikor törötten-csonkán is megtagadja
hóhéraitól a halálát jelentő vallomást. Józan fővel nem tartotta volna képesnek rá magát, hogy ilyen erős
védpajzsokat vonjon teste és lelke köré; érezni vélte, ahogy az ereiben lüktető vér belesápad a kíméletlen
szipolyozásba.
Az egymásnak feszülő energiák hangtalan robbanása szétvetette a két farkasszemet néző küzdőfelet;
az elf az árnyak között megbúvó bazaltfalnak repült, a vadász teste öles fellegfátylakat kavart a vastag
porrétegben, a hatszögletű asztaltömb hűlt helyén. Csattanva ért földet, s egy pillanatra elfeketedett előtte
a világ; hörögve nyeldekelte a szállongó bazaltport, s a bal arcába ékelt ezüstpók gyötrőbben nyilallott,
mint eddig bármikor. Csak a vakszerencse óvta meg attól, hogy lefejezze magát a jobbjában szorongatott
mara-sequorral, amit görcsbe merevedett ujjai elfelejtettek elengedni. Orrából, szájából bőven ömlött a
forró-piros vér, az ősi örökség hordozója.
Tántorogva vergődött talpra, s a kezében tartott karddal vadul belekaszált a sötétségbe. Az évtizedes
kiképzés talmi mázként hámlott le róla; majomlény volt ismét, bunkóját forgató barlanglakó, aki
ellensége halálát kívánja. Vagy tán rosszabb is annál; hiszen az ő ősatyái nem mind születtek
emberalakban...
Szétharapta bal hátsó zápfogát, és folyékony tüzet köpködött a körülötte kavargó homályba, mit sem
törődve azzal, hogy elpocsékolja egyik titkos fegyverét. A szentjánosbogárként röpködő gyertyasziporkák
riadtan menekültek a közeléből:
- Úmahtar! - üvöltötte rekedten. Ajkán apró lángnyelvek ugráltak, feketére égették, ráperzselték
cápafogaira. - Megöllek; úmahtar!
Valahonnan a táncoló porfátylakon túlról kísérteties, bomlott kacaj válaszolt neki.
Most, hogy a mérget gőzölgő bannarák nyúlós, formátlan posvánnyá omlottak össze; a csata
mérlege a tizenegy megmaradt apostol javára billent. A makacsul záporozó nyílvesszők távol tartása már
nem igényelt akkora összpontosítást; elegendő volt hozzá egyetlen elf is, egy büszke tartású, szálas
harcos, aki fél arcát lombzöldre festette, selymes-barna hajába pedig emberi koponyákról lemetszett
trófeafürtöket font. Ő a gyűrű közepére húzódott vissza, a száradó fejekkel ékes kútkáva mellé, szabaddá
vált társai pedig sorra vadászták le sújtó igéikkel a gyilokjárón cikázó saggitorokat. Prédaleső héjaként
vijjogtak a bástyafalak felé; amerre hangjuk szállt, ott erek nyíltak, csontok hasadtak, ferdén vágott
szemekben lobbant utolsót az élet sárga lángja. A rendház bazaltkövekből rakott védfala valóságos
romhalmazzá vált már, helyenként fekete salakká őrölte az ősi szózatok varázsereje.
Az egyik kőrakás tetején ekkor megtermett férfialak magasodott fel. Körvonalai beleolvadtak az
égboltozat sötétjébe, ám az ibolyaszín elf-szemek így is felfigyeltek rá. Valóságos óriás volt, széles vállú,
szikár, csontvázsovány. Haja tüskebozótként ágazott szerteszét roppant koponyájáról; kurta varkocsokba
kötötte, amiket aztán sárral és mésszel tapasztott kemény-merevre. Tekintetét árnyékba borította a vaskos,
előreugró homlokeresz. Meztelen volt, s távolról nézve úgy tűnt, mintha rühös vagy ótvaros lenne; bőre -
vagy irhája - száraz pikkelyeket vetett, s tenyérnyi foltokban hámlott róla a karján, a combján, izmokkal
kötegelt nyakán. Hatalmas termetéhez képest megdöbbentő fürgeséggel mozgott; ahogy fölállt,
körbefordult, célra emelte irdatlan íját, egyetlen pillanat műve volt csupán.
Az apostolok azonnal megérezték az új ellenfélből sugárzó fenyegetést; szívdobbanásnyi időbe sem
telt, máris négy hatalomige süvített rikoltva a kőrakás felé. Az óriás megrendült, mint a páncélos lovagok,
ha taglócsapás sújt le rájuk; de nem rogyott össze vért okádva, nem fordultak ki a tagjai, nem nyíltak
fekete kráterek a szeme helyén. Párjanincs ereklyét viselt, a rendház egyik féltve őrzött kincsét: egy
eleven Ősről lenyúzott pikkelyirhát, amely ezernyi éhes-mohó kaccsal gyökerezett a húsában, s minden
lélegzetvétellel szomjasan habzsolta a benne lángoló életerőt. Kevés vadásznak sikerült levetnie, ha
egyszer magára öltötte; éles pengék szükségeltettek hozzá, s a boncmester minden tudománya. Ám az
ereklye csaknem tökéletes védelmet nyújtott a hatalomigékkel szemben; és a tagbaszakadt saggitor,
kasztja legszívósabbja és legerősebbje, kész volt az életével megváltani a rend diadalát.
A negyedik apostol fürgébben fűzte a gondolatait három társánál, vagy egyszerűen csak a szeme
volt élesebb, és idejében rádöbbent, mit lát. Mindenesetre ő nem a csontos vállú emberóriásra irányozta
hatalomigéjét, hanem a magába roskadt kőrakásra a talpa alatt. A saggitor azonban jól választotta meg,
hová álljon; a mállatag törmelékhalmot, egy hajdan-büszke torony szomorú maradványát, már nem
lehetett tovább rombolni, kavicsokká omlott percekkel azelőtt. A vijjogó kiáltásra mindössze annyi
történt, hogy a bazaltsalak kissé megcsuszamlott alatta; ám nem azért tanult vadásznak hosszú
esztendőkön át, hogy ezt a zavaró tényezőt ne tudja kiegyenlíteni néhány gyakorlott térdmozdulattal,
súlypontja könnyed áthelyezésével. És a következő pillanatban rajta volt a visszavágás sora.
Az íj, amit hatalmas markában tartott, semmiben nem maradt el a testét borító pikkelyirha mögött.
Gyöngébb férfi megemelni sem bírta volna; roppant ívét emberi csigolyacsontokból enyvezték össze
valamikor rég, elfeledett hajtóvadászatok trófeáiból. A fegyver ősibb múltra tekinthetett vissza, mint a
Khat'ul'Naathum maga. Ezerkétszáz évvel ezelőtt került a rend kincstárába, azokban az időkben, amikor a
Fekete Özvegyek - ifjabbak és balgábbak lévén - még vállaltak ,kontraktusokat az Ősök csekélyebbjeitől,
akik leereszkedtek az utódfajokkal folytatott tárgyalásokig. Megbízójuk számára minden bizonnyal afféle
bosszantó kacat volt, haszontalan csecsebecse, amiből tizenkettő egy tucat; a Khat'ul'Naathum vadászai
azonban áhítatos tisztelettel kezelték a fegyvert, amely nem egy háborújukban a mérleg nyelvének
szerepét játszotta, egymagában tett különbséget győzelem és vereség között.
Bíborszín energia sistergett végig a csigolyaíven, amint útjára bocsátotta a szárnyaló halált. A fekete
nyílvessző dalolva szállt a levegőben, vérvörös csóvát húzva maga után; s amikor elérte az elfek
védőfalát, úgy hasított belé, mint izzó acéltű az eleven húsba. Hat, nyolc vagy kilenc akarattal talán nem
birkózott volna meg; de eggyel bizonyosan. A lombzöld arcú apostol hang nélkül fordult ki a nyeregből, a
gyilkos mogyorófaszár a torkát ütötte át. Odafönt a kőrakáson az óriás saggitor kezében újabb nyílvessző
termett, s már ajzotta is az íját, halálnál biztosabban, villámnál sebesebben.
Az egyik elf - egy feketén lobogó hajú asszony, homlokán az átdöfött tenyér s az aranyforrás jelével
két lábra állt a kengyelben, s metsző hangon elsikoltotta magát. Éles kiáltása velőkig vágott, szúrós
könnyeket csalt a lesben álló vadászok szemébe, összerántotta tarkójukon a bőrt. Az öles termetű íjász
mozdulata félúton megakadt; egy pillanatra szobor-. merevvé dermedt, ahogy á pikkelyirhában
szunnyadó erők birokra keltek a rettenetes hatalomigével. Két szívdobbanásra rá hordómellkasa
foszlányokra robbant, a rühes fekélyként rátapadó ereklyével együtt; sűrű vérzuhatagban hanyatlott hátra
az alaktalan törmelékdorübról. Csigolyaíja koppanva hullott mellette á bazaltkavicsokra: Egyetlen kar
sem nyúlt utána: a Fekete Özvegyek harcosok módjára vállalták a halált, de nem esztelenül. Márpedig az
ősi fegyvert a pikkelyirha védelme nélkül az egész rendházban csak a comtur, Vyergas és talán Udunn
érinthette volna meg; a többi vadász keserves kínok között lehelné ki a lelkét, mindjárt az első percben.
Ám a megerőltetés soknak bizonyult a hollóhajú elf számára is. Amikor visszazökkent a nyeregbe,
minden szín kiszaladt az arcából; mintha még a tetovált ábrák is megfakultak volna a homlokán. Egyetlen
élénkpiros vércsepp buggyant ki a szája sarkán; aztán á szeme tágra nyílt; és lassan lecsúszott a lova
hátáról, hogy mozdulatlanul terüljön el a fekete kövezeten.
Nyílzápor csapott a túlélő apostolokra, foghíjasan bár, de minden korábbinál ádázabb haraggal: a
megmaradt saggitorok mindenfelé előugráltak búvóhelyeikről, hogy bosszút álljanak bajnokuk haláláért.
Az elfek talán rendezhették volna soraikat, talán lett volna idejük rá, hogy megújítsák maguk körül a
védőaurát; ám ebben a pillanatban körös-körül felcsapódtak a rejtekaknák álcázott fedőlapjai, és özönleni
kezdtek az udvarra a csatamámorban őrjöngő vadászok, élükön egy üvöltő fúriával, aki míves harci
bárdot lengetett jobbjában, s ezekben a percekben inkább tetszett túlvilági lénynek; semmint halandó
asszonynak.
Egy.
Udunn szívdobbanásai hosszan visszhangzó ólom kondulásokká lassultak, ahogy az ellenség felé
rohant a hatszögletű bazaltlapokon. Elméje valamely eldugott zugában tisztában volt vele, hogy
szélvészként viharzik a koponyakávás kúthoz, ahol a tetovált képű lovasok várakoznak rá, acélhidegen
villogó halállal a kezükben s a szemükben; mégis olybá tűnt neki, mintha a levegő nyúlós mézharmattá
sűrűsödött volna körülötte, s ő álmatag lomhasággal úszna benne, akár a krákok és a méltóságteljes
narválcetek a Földalatti Óceán sötét mélységeiben.
Bőrcsizmás lába megérintette a talajt, térdben behajlott, elrugaszkodott: csupa vontatottan lebegő
mozdulat, esőáztatta lidércbalett az álmok semmibe vesző színpadán.
Kettő.
A rúnákkal maratott lapú csatabárd könnyűnek és légiesnek tetszett a markában, mintha testének
szerves tartozéka lenne, végtag-nyúlvány, alkarja folytatása. És ez így is volt jól: máskülönben messzire
hajította volna, hisz most önkezével vágyott vért ontani, otromba segédeszközök nélkül, a fogaival és a
körmeivel, született vadász módjára. Fújtatott; vicsorgott; kurrogó morgás szakadt föl a torkából.
Egész valóját vadállati kéj öntötte el a tudatában megfogamzó gondolattól, édesebb és bizsergetőbb,
mint amit férfival - férfiakkal - valaha átélt.
Ölni fog!
Három.
Két újabb nyereg ürült meg; két trófeától fosztották meg a saggitorok dühödt darazsakként
zümmögő nyilai. Később majd megbünteti őket az orcátlanságukért; egyelőre a préda a fontos, az élettől
zamatos, vérforró hús, amelybe belemélyesztheti fűrészes fogait, s mohón nyeldekelheti az átharapott
erekből szerteáradó; fűszerízű nedveket. Nem menekülhetnek előle.
Ő a végzet. A beteljesedő sors. A Kosfejes Úr sárga torkú angyala.
Négy.
Elpattanó csontok recsegtek körülötte, falkatársak rikoltottak élesen. Nem a fájdalom csalta ajkukra
a kiáltást, hanem a düh, a tehetetlen harag, hogy lám, a szárnyas szavakkal rájuk csapó halál méltatlanul
bánik velük, megtagadja tőlük a hőn áhított mámort, az utolsó ölés örömét.
Feketeruhás alak hemperedett Udunn elé, szilánkokra tört koponyája véres csíkot hagyott a
bazaltköveken. Oda sem nézve ugrotta át; ami nem élt, nem harcolt, nem lélegzett, az most nem tarthatott
számot a figyelmére.
Öt.
Nem pazarolta a levegőjét az Ősök Tudományára. Ami energiája csak volt, mind láthatatlanul
lüktető pajzsokba csomózta maga körül. Vijjogó hatalomige süvöltött felé, s porladt értelmük-veszve
zengő hangzatokká a védművein. Falkatársai zömét ott helyben kizsigerelte volna; a legerősebbek bénán,
vakon vagy törött tagokkal hanyatlanának el. Neki azonban - az lévén, aki - nem árthattak a csekélyebb
szózatok.
Hat.
Aki a sújtó igét az imént útjára küldte, keskeny csípejű, ezüsthajú elf volt. Zöld-arany tunikája elöl
csupaszon hagyta szőrtelen mellkasát; az izmain átfűzött három szarvasín büszkén hirdette, hogy háromszor állta ki ép ésszel a Révedések Ünnepén a rituális fájdalompróbát. Ibolyaszín szeme most Udunnra
lobbant, s felismerés villant benne. Tudta, kivel áll szemben; tudta, miféle vér folyik a borotvált fejű
asszony ereiben. Ajka máris formálni kezdte egy másik, egy hatalmasabb ige első szótagjait; ha az előző
nem volt elegendő, ez már bizonyosan az lesz.
Túl messze volt Udunntól. Legalább két szívdobbanásnyira.
Hét.
Árnyék borult a mortelre, s vitorlázott tova méltóságteljes lassúsággal. Egy vadásztestvér szárnyalt
a levegőben, kiterjesztett karjai között úgy lebegett a köpeny fekete selyme, akár a denevérlebernyeg.
Embertől nem telhetett ki ekkora ívű ugrás; ám az evezőhossznyi láb, a hátrafelé ízesülő térd, a négy
irányban szétágazó talpon kifeszített vércsekarmok másfajta származásra vallottak. A vadász káoszfattyú
volt, tisztátalan örökség hordozója; ha anyja ezen a síkon született is, az apja egy másikon, egy
sötétebbiken.
A borotvaéles vércsekarmok az ezüsthajú elf állkapcsába vájtak, összerándultak a halánték felől,
kifordították gödrükből az ibolyaszín szemeket. Az apostolnak torkán rekedt a hatalomige; hátrabukott a
lova farán keresztül, s a selyemből szőtt denevérszárnyak összecsaptak karcsú teste fölött.
Nyolc.
Hófehér csődör ágaskodott Udunn előtt, acéllal vasalt patái a levegőben kapáltak. A mortel lebukott,
előre és jobbfelés csatabárdja vicsorgó pofáját az állat szegycsontjába vágta, s egyetlen mozdulattal
végighasította a horpaszáig. A ló fájdalomnyerítése már-már emberinek tetszett, a hasa alól előugró
Udunn azonban -ügyet sem vetett rá. Sem vele, sem lovasával nem kellett többé foglalkoznia; fegyvere
átmetszette az alsó _ nyereghevedert is, s az elf most egyensúlyát vesztve zuhant a nyomában törtető
vadászok közé.
Kilenc.
Valami villant, valami szisszent, s Udunn vállán hosszan vöröslő seb nyílt egy lesújtó hiequar
nyomán. Az örvénylő forgatagban csak egy ló reszkető oldalát látta maga előtt; egy tegzet, egy nyerget,
egy zöldarany posztóba bújtatott lábat. Meglendítette véres csatabárdját, s az ütésbe inas testének minden
erejét beleadta. A rúnákkal vésett acélpofa átharapta a hengerforma bőrtokot, a benne zörgő nyílvesszőköteggel együtt, s csikordulva akadt meg a combcsontban. Meleg folyadék fröcskölt a mortel arcába. Sikoly
harsant.
Tíz.
Udunn tenyerén szegecselt bőrszíjak feszültek keresztben. Ha akarta, sem vethette volna le őket; a
szegecsek bele voltak csavarozva a kézcsontjaiba. A szeme sarkából vette észre a másodjára is lecsapni
készülő hiequart; magasra kapta hát szabad karját, s nyitott tenyérrel fogta fel a vágást. Fém csendült fémen, szikrák pattogtak. A mortel kirekesztette tudatából az idegein végigparázsló fájdalmat, s egy kurta
csuklómozdulatot tett; az ívesen hajló pengeél megakadt a szegecsfejek kereszthornyai között.
Másikkezével a csatabárdnak feszült neki. A csontba ékelődött vágólapot nem tudta kiszabadítani,
de nem is ez volt "a szándéka. A fegyver nyele felül háromujjnyi acéltüskében folytatódott; és ahogy csavarintott rajta egyet, ez a tüske átdöfte a nyerget, s teljes hosszában beleszaladt a ló oldalába.
Tizenegy.
Az elf nem eresztette el a kardját, az élete árán sem, és ez lett a veszte. Amikor a halálra sebzett
csatamén kidőlt alóla, Udunn a hiequarnál és a combcsontjába akadt harci bárdnál fogva emelte ki a
nyeregből; a zömök kis asszonytestben irtózatos erő lappangott, s a bőrét behálózó hegtetoválások ezt
csak megsokszorozták. Rekedt nyögés szakadt fel a mortel sebhelyes ajkáról, amint nagy ívben
körbelendítette ellenfelét, s csontrepesztő erővel a fekete bazaltlapokhoz vágta. Az apostol gerince száraz
reccsenéssel tört ketté, mint a korhadt ág, ha csizmatalp tipor rá. .
Tizenkettő.
Héjaként rikoltó hatalomige sújtotta hátba Udunnt, mielőtt ideje lett volna kitépni fegyverét a
végvonaglásban rángó ellenfél testéből: Ahhoz nem volt elég erős, hogy összemorzsolja; ahhoz viszont
igen, hogy a levegőbe emelje, negyven lépésnyi távolságra repítse, s üres dióhéjként csapja az étkezőház
komoran magasodó homlokzatához, a torz pózokban rothadó trófeák közé. A mortel ázott szalmabáb
gyanánt bucskázott a fal tövébe; sötét, alaktalan folt maradt utána a hatszögletű bazaltlapokon.
Tizenhárom.
Udunn szeme lassan résnyire nyílt, törött bordavégektől átfúrt tüdeje hörögve küzdött minden korty
levegőért. Sebeiből bőven ömlött a forró-piros vér, az ölés vágya azonban mit sem csillapult benne; ha
tehette volna, újra megindul a koponyakávás kút felé, torkokat tépni, csontokat zúzni, eleven húst
marcangolni. Alig maradt ép porcikája; de tudta, hogy nem fog meghalni. A bűvös erejű hegtetoválások
már megkezdték rajta munkálkodásukat; gyógyító bizsergés járta át egész testét, ahogy sorra összeforrtak
az elfeslett erek, helyükre ugrottak a kifordult ízületek, eredeti alakjukba rendeződtek a szétszóródott
csontszilánkok.
Az apostolok száma négyre fogyatkozott, lovaikat valamennyien elvesztették. Egyiküknek sikerült
újra felállítania a védőaurát; egy másik - alig több felismerhetetlenre zúzott roncsnál - hatalomigékkel
gyógyította magát a kútkáva fedezékébe húzódva. A harmadik tucatnyi sebből vérzett, ám tetovált arcán
fagyos nyugalom ült, miközben karddal és szavakkal sújtotta halálra a körülötte csaholó vadászokat.
Az utolsó apostol levedlette magáról halandó alakját. Lángvörösen izzó lávakolosszusként
magasodott az udvar közepén: roppant öklei csóvákat hasítottak a sűrű homályba, az elgőzölgő
esőcseppek szürke párafátyolba öltöztették. A testét érő pengék sisteregve fémcsonkká olvadtak,
semmiféle kárt nem téve benne; ám az ő csapásai nyomán forrón fröccsent szét edzett acél, sötét selyem
és eleven hús egyaránt.
Vissza, vadászok! A comtur kísértethangja parancsolóbb volt, mint valaha. A ti órátok letelt.
Az életben maradt sequatorok elszakadtak ellenfeleiktől, s az udvar sötétjében szétszóródva
szaladtak a rejtekaknák hívogatón ásító torka felé. Kevesen voltak - jóval kevesebben, mint ahányan
rohamra indultak nemrég a kút védői ellen -, újabb veszteségekkel azonban már nem kellett számolniuk.
Visszavonulásukat azok a falkatársaik fedezték; akik a comtur szellemparancsára sem bírták
legyűrni magukban az ajzószerek hozta csatamámort.
A koponyadíszes kút szélesre nyitotta tátongó száját, és folyékony sötétséget okádott magából. Nem
közönséges sötétség volt ez, mint a csillagtalan éjszaka Sramsass-Daqkínban, vagy a földmély örök
homálya; az anyag síkján akármerre téved a vándor, mindenütt megtalálja valahol a fénynek egy eldugott
szikráját, ha másutt nem, hát a saját kebelében: Ez a sötétség viszont valami teljesen idegen és
felfoghatatlan dolog volt, nem is annyira a világosság hiánya, hanem inkább szöges ellentéte; szavakat
találni nem lehetett rá, hiszen nem erről a világról származott. Cseppfolyós fodrokban bugyogott elő a
kútkáva mögül, meggyűlt és megsűrűsödött a díszéül szolgáló koponyákban, majd tapogatózó
nyúlványokat fecskendezett szét az udvaron mindenfelé. A sebesült apostol, amikor megpillantotta maga
fölött az alvadtan vonagló csápokat, némán behunyta ibolyaszín szemét, és felkészült a halálra.
Igyekezete azonban korai volt még, ha helyzetmegítélése hosszú távon nem is csalta meg. A
sziromszerű formákba bomló, majd újfent magába roskadó sötétség nem őt kereste. Az indázva
egybefonódó nyúlványok hosszúkás rojtokra szakadoztak, meg-megremegtek a hűvösen szemerkélő
esőben; aztán türelmes polipkarokként kezdtek vonaglani a negyedik apostol, a lávává lényegült
szörnyalak felé.
Az elf-lény megérezte a fenyegető veszedelmet, bár háttal állt neki. Megfordult, szembenézett a
formátlan sötétséggel. Két mozogni tudó társa oldalazva, lassú léptekkel megindult felé, ő azonban egy
parázsívű kézmozdulattal megállította őket. Mindenki ösztönösen megérzi, ha olyan viadal előtt áll,
melyet segítők nélkül kell megvívnia.
A sötétség szapora hullámokat vetett, és körülfolyta ellenfelét. Mozgásában volt valami rettenetes
magabiztosság, a sziklát kivájó vízér önbizalma, az a fajta győzelemtudat, ami az emberi képzelőerőt
meghaladó türelemből táplálkozik. Közönséges halandó bizonyára a puszta látványt sem lett volna képes
elviselni, a gyűrűző homálycsápokból sugárzó néma fenyegetést; ámde az Éjben Kacagó apostolai nem
voltak közönséges halandók.
Az elf-lény első szavára sugaras lángbarázdák száguldottak végig a lüktető sötétségen; fakó füst
szállt föl a nyomukban, ahogy sziszegve enyésztek semmivé a fodrosra szakadozott peremeken, vagy
tűntek el a kútkáva torkában. A túlvilági szörny összerándult, hangtalan sikolyt hallatott. A következő
pillanatban tomboló örvényben csapott össze az öles tűzalak körül, vadul tépve-szaggatva róla a lángokat,
egyre csak azon igyekezvén, hogy magába fullassza vörhenysárga fényét.
Az apostol bátran fölvette a harcot. Ökölcsapásai tátongó árkokat hasítottak a sötétségbe, a szájából
fuvalló lángok csíkokra szabdalták; rőten izzó ereket szőttek belé. Magányos sziklaszálként magasodott a
fekete hullámverésben, mely már-már összecsapott tűzkoronás feje fölött, majd meghátrált, visszahúzódott, hogy erőt gyűjtsön az újabb rohamhoz. A félelmetes homály hideg nyelvekkel nyaldosta körül, ostoros nyúlványokkal cserdített felé, cseppekre váló zuhatagokban ömlött rá felülről. Egyelőre még elhárította a támadásokat; ám a visszavágáshoz nem maradt ereje, s mozdulatai mind lankadtabbá váltak, fénye
egyre halványabban parázslott.
Ekkor a sötétség elszánta magát a végső rohamra. Tajtékos förgetegként rontott a lángoló
lávalényre, homályhabot fröcsögve, fekete nyálpermetet okádva, mintha az egész rendházat magával
akarná söpörni valami túlvilági, fagyos-rideg bugyorba. Az apostol egy kurta pillanatra állta az ostromot;
aztán megingott, féltérdre hullott, vakon sarabolva öles tűzkarjaival. Égő hasadékok nyíltak a sötétség
cseppfolyós szövedékében, s forrottak össze mindjárt nyomtalan; a rettenetes ár átcsapott az elf-lény
felett, kavargó felszínű homálygubóba zárta, amely alól még mindig dacosan világolt a vörhenyes izzás.
Szívdobbanásnyi időre úgy tűnt, mintha az apostol még egyszer, utoljára összeszedné magát:
fölegyenesedne, szétvetné roppant karjait, s lerázná magáról a nyúlós csápokkal rátapadó halált. Ám
azzal, ami a kút mélyéről előtört, még az ő hatalma sem vetekedhetett: a sötétség foszlányokat vetve
felfortyant, visszaörvénylett önmagába, s a sárgásvörös fény pislogva kilobbant, mint elkoppantott kanóc
végén a gyertyaláng.
A három megmaradt elf komoran figyelte, amint a túlvilági homályszörny lomha, elégedett
hullámzással megindul vissza, a koponyákkal ékes kút felé. Mozdulataiban, ahogy lustán elterpeszkedett
a hatszögletű köveken, ahogy húsos rozettákra bomolva végignyaldosta a fekete bazaltot, volt valami
önelégült, valami jóllakott. Ölebként tartott gyíkok vonulhatnak haza így langymeleg vackukra, ha vége
az etetési időnek, s degeszre tömték nyálkás hasukat a kövérre hizlalt mocsári pondrókkal.
Egyik apostol sem mozdult, amíg a cseppfolyós sötétség vissza nem szivárgott a kút mélyére, maga
után húzogatva utolsó nyúlványvégeit is. Tudták, mi történt itt: teljesedésbe ment egy szigorú kötés, a
szerződő fél elvégezte feladatát, megkapta járandóságát: Ha megzavarnák, ha bosszúvágytól hajtva
fegyvert vagy igéket emelnének rá, kontraktust sértenének, s népükre idéznék a Túlsó Síkok haragját.
Valahol mélyen a föld alatt, egy boltozatos terem kongó félhomályában, hanyatt feküdt pentagrammájában a bíborsujtásos kaftánt viselő beavatott. Mindkét szemére megvakult, s füléből, orrlyukából
vékony patakban szivárgott a vér. A sietségért csaknem az életével kellett fizetnie: a Túlsó Síkok lakói
nehezen zabolázhatóak, s ő a leghatalmasabbat szólította fel közülük, akit csak néven nevezni mert. Hajszálon múlt csupán, hogy az erők párharcában ő kerekedett fölül, s az apostolé helyett nem az ő lelke
szállt sikoltva kárhozatra.
A démonlovas opálossá homályosult szeme körül a festett minták zavaros színegyveleggé mosódtak
össze: eláztatta őket a homlokáról szakadó veríték. Az ajka viszont... az ajka, ha ráncosan; cserepesre
repedten is; de mosolygott...
Vyergas bal arca hosszában kettéhasadt. Ha nincs a rúnapók, ott helyben halálát leli; ám az ereklye
törhetetlen ezüstje felfogta á fejének irányzott kardcsapást, s bár nyolcágú kínnal nyilallt a húsába, az
életét megmentette.
A zömök férfi hátraszökkent, s felköhögött a torkából egy igét, amely eltünteti a lepleket, s messzire
riasztja az elmével játszó fantomokat. Ejthette volna hatalmasabban is; ám az imént veszedelmesen megcsapolta a vérében szunnyadó energiákat, s tudta jól, hogy takarékoskodnia kell a tartalékaival. Csak
remélni merte, hogy nincs ezzel másképp az úmahtar sem, s a bűvige, amelynek oltalma alá húzódott, a
csekélyebbek közül való.
Igaza volt. Gyűlölten ismerős körvonalak bontakoztak ki a porfátylas homályból, ahogy az elfről
lemállott a láthatatlanság védőmáza: táncosan szökellő lábak, karcsú derék, keskeny vállak, jégkék
szempár az aranyló hajfürtök alatt. És persze a kard, a fűzfalevélként hajló hiequar, melynek ezüsttel
futtatott pengéjén most friss vér gyöngyözött.
- Ölj meg, kicsiny ember! - susogta Aurri; mosolyra húzódó szája szögletében gúny és őrület
bujkált. - Ölj meg, itt vagyok!
És támadott; mozdulatai kecsesen egymásba folytak, olajozott átmenetekkel, könnyedén és tetszetősen, akár a hulló falevelek tánca az őszi szélben, ha Káosz-Raddaq dérharmattal borítja a tarka lombokat.
Minden lépésében, minden fordulatában a halk halál dalolt.
Vyergasnak nem volt érkezése méltányolni az elf vívóstílus eleganciáját. Összeszorított fogakkal
hárította a záporozó csapásokat, egyiket a másik után. Érezte, hogy sikerült átvennie az úmahtar ritmusát,
s ez javára szolgált, bár egyszersmind másodrangúságának elismerése volt; máskor ő szokta diktálni az
ellenfélnek a párbaj ütemét. Most azonban örült, hogy ennyire jutott, s a gyomra mélyén jégdarabbá fagyó
gyűlöletet egyetlen végső kitörésre tartogatta; tudta jól, hogy ha akkor nem ragadja magához a kezdeményezést, soha többé nem lesz rá esélye. Magabiztossá kell tennie az elfet; elhitetni vele, hogy erejevesztett
báb ő, akivel kedvére eljátszadozhat. Ha végérvényesen meggyőződik róla, előbb-utóbb hibázni fog; a
gőg mindig rossz tanácsadó.
És ennek az ellenfélnek nem is igen van más gyönge pontja.
Félrelépett egy csapás elől, oldalra kapta a fejét, karddal hárította a következőt. Kisebesedett
tenyerében érezni kezdte a mara-sequor súlyát; a párviadal hosszúra nyúlt, a fáradtság alattomban
nyújtogatta felé lankasztó csápjait. Még le tudta rázni őket, hiszen primortel volt, kérges szívű veterán,
megszámlálhatatlan csata győztese; de sokáig nem bírja már, végesek az ő erői is.
Ha csak a pengék ezüstösen csengő játékára figyel, nem veszi észre a döntő pillanatot; Aurri túl jó
harcos volt, semhogy a vívótechnikájával elárulja magát. Ám a rúnadíszes ezüstpók, amely oly sokszor
mentette már meg az életét, ezúttal is a segítségére sietett. Az elf aurája mindeddig szikrázó azúrkék volt,
fekete-vörös erekkel átszőve; most azonban hirtelen lüktetés reszketett rajta végig, s amerre a körkörös
hullámtaréj elhaladt; bíborlila ragyogás terjedt szét a nyomában, magába olvasztva mind a többi
árnyalatot.
A gőg színe. A dölyfös önbizalomé, a diadal feltétlen tudatáé.
Erre a pillanatra várt Vyergas; tüdejéből rekedt vartyogás bugyogott fel, artikulálatlan hangok
zavaros egyvelege, melyből a saját füle is alig hallotta ki az Ősök Nyelvének hörgő salakká torzult
szavait. Minden maradék energiáját ebbe a hatalomigébe sűrítette, ügyet sem vetve kizsigerelt teste
kétségbeesett tiltakozására. A fájdalom émelyítő volt, az egész bazalttermet vöröslő ködbe vonta
körülötte; forró lángbarázda hasította végig a torkát, a hangszálait, hátsó zápfogai szilánkokra törtek. Vér
és epe fröcskölt leperzselt ajka mögül, ahogy a tiltott szózatot a világra okádta.
Érzékelte, hogy Aurri azonnal felvonj a védpajzsait; talán áttörhetett volna rajtuk ezzel a végső
erőfeszítéssel, de nem vállalta a kockázatot. A hatalomige nem az ellenfelére, hanem őrá magára fejtette
ki hatását; mintha folyékony láva ömlött volna szét az ereiben, mintha emésztő hevű máglya lobbant
volna föl véres homloka mögött. A semmiből támadó energia szétáradt egész testében, végigbizsergette
minden tagját, minden porcikáját. Úgy érezte, elevenen fog elhamvadni; szíve majd kiugrott a bordái
közül.
Puszta kézzel ütötte félre a hiequart; a míves elf penge keltébe hajlott, középen megtörött,
álomszerű renyheséggel vált két darabra. A pusztulását kísérő éles csendülést Vyergas mély, vontatott
dübörgésnek hallotta. Az egész világ lelassult körülötte; az előbb még oly fürgén cikázó fényparányok
mézbe ragadt legyek módjára vonszolták magukat a sötétségben.
Látta, hogy Aurri ajka megmozdul, hangokat formál. Egyetlen szavába kerülne csupán, hogy
lefoszlassa ellenfeléről az Ősök bűbáját; és ezt a szót egyetlen szívverés alatt ki tudja mondani. Csakhogy
a primortelszíve most tízet dobban, míg az övé egyetlenegyet.
Az első kardvágás a vállán érte az elfet, széthasította a kulcscsontját és a nyaki ütőerét. Furcsán
megrogyott oldalra; a seb körül sötét vércseppek jelentek meg, és sugarasan szétágaztak a levegőben,
folyékony csíkokat húzva maguk után: Lomhán nyiladozó halálvirág, hiú remények és ősi sérelmek
feledtetője:
A mara-sequor ugyanarra a sorsra jutott, mint az úmahtar kardja; nemcsak tízszerte gyorsabban, tízszerte erősebben is sújtottak le vele, s ezt a megterhelést a földmélyi kohókban edzett acél sem bírta ki.
Borotvaéles, körömnyi fémszilánkok forogtak a félhomályban méltóságteljes lassúsággal. Vyergas kirántotta a sebből a fűrészesre tört végű csonkot, kurta mozdulattal az elf gyomrába szúrta, majd elengedte
a markolatot.
Aurri lebegve ereszkedett a bazaltköves padló felé. Válla és hasa körül álmos vérkoszorúk
bontogatták cseppfolyós szirmaikat, az elmúlás indás-kacsos mintáit szőve a levegőbe. Volt valami
lélegzetelállítóan gyönyörű a látványban; a hanyatlófélben lévő testen rőtvörös orchideák nyíltak, bíbor
lótuszkelyhek szökkentek szárba, nedves-eleven rózsaporzók bólogattak. A kép hátterét az asztrálaura
magasztos ragyogása szolgáltatta: egymásba olvadó színek és alakzatok, cinóberrel hártyázott azúrkék,
opálosan csillogó szűzfehér, s az a különös, megfoghatatlan árnyalat, amely a hamuba fulladó
lángnyelvek emlékét fodrozza körül olykor, ha értő szem figyeli.
A tűnékeny idomok és formák reszketeg harmóniája minden közönséges szemlélő számára rejtve
maradt volna; Vyergast azonban lelke mélyéig megrendítette, véresre marjult torka furcsán összeszorult.
Ez az igazi, hamisítatlan szépség, gondolta könnyes szemmel, miközben közelebb lépett az elfhez, s
mutatóujja könnyed nyomásával beroppantotta a homlokát. A halál esztétikája.
Különös érzés fogta el, részben költői elragadtatás, részben misztikus révület, részben egyfajta
szellemi orgazmus. Azt kívánta, bár örökké tartana ez a pillanat; ám az idő múlását még az Ősök
Tudománya sem tartóztathatta fel, legfeljebb féket vethetett rá. Aurri egyre közelebb került a hatszögletű
bazaltlapokhoz, a levélforma hiequar kicsúszott ernyedő ujjai közül; szabadon úszott a levegőben. Az
asztrálaurával egybemosódó vérvirágok mind bonyolultabb alakzatokba rendeződtek; nemsokára
tartásukat vesztik, és magukba roskadnak. Vyergas elhátrált kissé, hogy ha a gátjait szétszaggató idő
hullámverése újra rázúdul majd, ne sérthessék fel a szerteröpködő fémszilánkok. Tekintetét azonban egy
pillanatra sem vette le a legyőzött úmahtarról; hosszúra nyújtott haldoklása remekbe szabott műalkotás
volt, az ő keze műve, amit a legvégsőkig ki akart élvezni.
Távoli, halk nesz ütötte meg a fülét; acélszürke szemöldöke ráncba futott. Amíg a hatalomige hatása
alatt állt, csak a legélesebb és legmagasabb hangokat hallotta, azokat is lomha-mély robajlásként csupán.
Többet nem érzékelne Aurri halálsikolyából sem. Ez azonban valami más volt: szaggatott, rikoltó
nevetés, a téboly mákonyos ízével teljes, mely messzire cseng a fullasztó sötétben, és nem szab neki
korlátokat az Ősök Tudománya.
Pillantása az elf bezúzott homlokára tévedt. Tűzvörös kövirózsa virágzott ki rajta; szertekígyózó
levélfonatai beszőtték és magukba nyelték mind a büszke krónikásjeleket, egy kivételével.
A lángoló szív továbbra is dacosan izzott a vasbéklyó börtönében, konokul őrizte fényét, bár az
úmahtar élete vérszirmokban bimbózott el körülötte. És Vyergas ekkor végre rádöbbent, mit hall.
Mallior kacaját.
A három megmaradt apostol egyike összeesett a rendház udvarán; az ujjai közül kiforduló hiequar
csengve hullott a hatszögletű kőlapokra. Iszonyú rángógörcsök szaggatták az elf törékeny testét; ajkáról
bomlott, vonító nevetés fakadt, titkos visszhangokat riasztva a szellemsíkokon.
Két társa összenézett fölötte. Szólni nem szólhattak egymáshoz, hangszálaikat lefoglalta a védőaura
hatalomigéinek folyamatos intonációja, ám egybevillanó tekintetük önmagáért beszélt. A harmadik
apostol Ly'Shematenel volt, örökösödésből kizárt ágyasgyermek, de az ősi vér hordozója. Arca mélyvörös
pírban égett, mintha lázlob gyötörné vagy gyulladás fészkelne benne. Ahogy figyelték, ráncokba gyűrődő
homlokán bonyolult körvonalak bontakoztak ki; teltek meg színnel, tartalommal: béklyótagok,
lángnyelvek, egy izzón lüktető szív kontúrjai.
Kőszikla vagy, fiam; és én erre a kősziklára építem házamat...
A két elf nem habozott. Biztosan tudták már, hogy Aurri halott; mint ahogy azt is, hogy Mallior
hagyatéka nem maradt örökös nélkül. Nem volt okuk tovább időzni ezen a vigasztalan helyen, elesett
társaik tetemei között.
Kétfelől ragadták meg a magatehetetlen kacagót a hóna alatt; szabad kezük meztelen kardpengét
markolt, az acél hideg villanása ezüstös félköríveket metszett a halálbűzös homályba. Kánonban zengő
hangjuk megerősödött, magasba szárnyalt, fülsértő crescendóba csapott át; távozni készülődtek,
hatalomigéik meg-megszaggatták a tér szövedékét:
Az idegen szózat úgy zúdult rájuk a hatszögletű öregtorony felől, mint valami mennydörgő
sziklaomlás. Hörgő-rekedt hangok robajlottak végig a rendház udvarán, puszta súlyukkal letaglózva az
elfeket, tüdejükbe fullasztva a lélegzetet, szemükbe dermesztve a fényt. Elterültek mindhárman, akárha
pusztító erejű szélvihar süvített volna el fölöttük; csak a kiválasztott nevetett tovább megállíthatatlanul, a
másik kettőben bennszakadt a szó, zihálva kapkodtak levegő után. Ibolyaszín tekintetük elfelhősödött egy
pillanatra; ám amint kitisztult, nyomban körbevillant, az új fenyegetés forrását kereste.
A torony balkonján, mindenfelől szolgáktól megtámogatva, formátlan torzalak magasodott. Véres
ajkak vigyorogtak a valaha-volt arc rákos kísértetében. A torok, a garat, a száj megannyi nyílt seb; a
hangszálakon áttetsző hártyalüktetett, a kénben gőzölt darunyelőcsőben habot vetett a nedvesen bugyogó
nyál. Ragacsos veríték verte ki az utolsó csatájára készülő comtur otromba testét.
Az egyik apostol talpon termett, karját fölfelé lendítette, ajka szólásra nyílt. Színpadias, széles ívű
mozdulat volt; épp megfelelő egy többszázados életút lezárásához. A rendház urának következő
hatalomigéje úgy zúzta be az elf meggyengült védpajzsait, mint tollas buzogány csapása a bordásan
merevített páncél lemezeket. Az egyik pillanatban még ott állt a romba dőlt udvaron; a következőben már
csak körömnyi cafatkák maradtak belőle, szerterepülő húsfoszlányok, forró vérpermet, törötten pörgő
fogak. Körkörös koszorúrepedések futottak végig a bazaltlapokon; a szitáló esőcseppek félreriadtak a
levegőben, hogy elkerüljék a találkozást az ártó mágia sistergő, fortyogó gócával.
A második apostol jobban takarékoskodott a hatalmával; vagy talán csak az a tudat acélozta meg
elszántságát, hogy utolsónak maradt. Vijjogva rikoltott a messzi balkon felé; vonásai a gyűlölet
maszkjává torzultak. Hangjára a comtur rekedt robajlása válaszolt, súlyosan és mélyen, akár a darabos
ólom vagy a hegyormok álmai.
A két hatalomige egymásnak feszült az udvar fölött. A szennyes esőpermet sziszegve, gőzfodrokat
eregetve örvénylette körül a pontot, ahol találkoztak. Rianó jég sikoltott, mennydörgés dübörgött tompán;
egyik sem bírt a másikával. A disszonáns hangok száz karommal vájtak a rejtőző vadászok
dobhártyájába, rezgésbe hozták a fekete salakhalmokat, végigborzongatták a bástyafal vaskos
támpilléreit. Az egész udvar vibrálni, majd rázkódni kezdett; az étkezőház szögletes homlokzatán
groteszk táncra perdültek a régi vadászatok penészhúsú trófeái, s ahogy egyre szilajabbul, egyre
féktelenebbül ropták, mind többen potyogtak le közülük száraz zörgéssel a bejárat lépcsőire. Valahol bal
kéz felé az udvaron kipattant a kövezetből egy malomkőnyi bazaltlap, olyan hangot hallatott, mint a
késéllel megpöccintett üvegharang, aztán sugarasan hat darabra hullott.
Az elf mintásra tetovált arcán keskeny, élénkpirosan csillogó patakocskák csordogáltak lefelé; az
orrlyukából, a szeme sarkából, a szája szögletéből eredtek: Izomgörcsök rángottak végig a karján; a
hiequar kihullott zsibbadó ujjai közül, s le kellett eresztenie a földre az átalakulófélben lévő úmahtart is,
aki még mindig eszeveszetten kacagott. Finoman ívelt nyaka most nem tűnt sem karcsúnak, sem
előkelőnek; az ínkötegek majd' kiszakadtak belőle, úgy megfeszültek az erőlködéstől.
A hájredők és húsdaganatok közé börtönzött comtur részegen dülöngélt fenn a balkonon, a szolgák
alig bírták megtartani. Az egyiket egy hirtelen mozdulata át is billentette a korláton; szélesre tátott szájjal,
mégis némán zuhant a mélybe, halálordítását elnyelte a zúgó-zengő mágiaorkán, a sivító füttyök, a
hullámverésmoraj. Valahányszor a láthatatlan hullámok újabb dörgő rohamra indultak az éles
sirályrikoltozás ellen, a comtur fölmetszett torkából sötét folyadéksugár fröcskölt elő férfikarnyi
hosszúságban. Tályogos orrnyílása körül vérhártyás buborékok tolongtak egymás hegyén-hátán; a
legkülsők sorra pukkantak el, ám az elrákosodott tüdő ugyanolyan iramban öklendte fel az utánpótlást.
A hangskála legvégső határait ostromló kakofónia a tetőfokára hágott; a fül már feladta vele a
harcot, most a velőt bizsergette, az idegeket reszelte, a csontokat sajdította meg. Az elf arcán hirtelen
megereszkedtek az izmok, szája széle furcsán lefittyedt, testének egész baloldala megbicsaklott: A comtur
minden egyes lélegzetvétellel újabb és újabb darabkákat köhögött fel önnön belsejéből; a verítékező
szolgák lába meg-megcsúszott a gyorsan terjedő tócsában a balkon padlatán.
Makacs harcosok voltak ők ketten, az apostol meg a rendház ura; inkább vállalták a sorvadást, a
megnyomorodást, az évekig húzódó, lassú haldoklást, semmint a vereség szégyenét.
Talán egyiküknek sem tűnt fel, hogy az öregtorony kapuzatáról töredezni kezdenek a szobordíszek,
hogy a támoszlopokon cikcakkos repedések indáznak fölfelé, hogy a gazdagon bélletezett boltívek
beroppannak, majd hosszanti irányban szétmállanak, akár a rosszul tapasztott sárkunyhók fala. Hiszen
mindketten a hatalomigére összpontosítottak, hogy belésűrítsék utolsó csepp erőtartalékukat is, ügyet sem
vetve a szétfeslő hangszálakra, az agytekervényeiket elöntő vérre, a sorra elpattanó erekre a szívük körül.
Vélhetőleg egymást sem látták már; a külvilág megszűnt létezni számukra. Csoda-e hát, hogy egyikük
sem .vette észre, amint a zömök bazalttorony megroskad a körülötte kavargó energiaörvény szorításában,
majd oldalt roggyan, ferde síkban megcsuszamlik, és lassan dőlni kezd, egyenesen a koponyakávás kút
felé? Csoda, hogy a kivérzett szemek nem láttak, hogy a tönkrezúzott fülek nem hallottak,- hogy a
ronggyá szakadó idegpályák nem továbbították a beérkező ingereket?
Nem. A csoda az volt, hogy az utolsó pillanatban mégis felocsúdtak, mind a ketten.
Az elf apostol félvak tekintetében a tehetetlen düh előbb keserű csalódásnak, majd a halál
igazságával megbékélő harcosok belenyugvásának adta át a helyét. Bátor férfi volt, s még fél oldalára
bénán is méltósággal tudta fogadni a véget, amikor a magasból alázúduló bazalttömbök péppé morzsolták
a hagymázasan hahotázó majdnem-úmahtarral együtt.
A comtur roppant testének azon a pontján, ahol valaha az arca lehetett, nem sok érzelmek kimutatására alkalmas vonás maradt. Egyenetlen sík volt csupán, sebekkel, varokkal, burjánzó fekélyekkel
szabdalva; mielőtt azonban darabokra szakadt volna, megmagyarázhatatlan módon mégis kifejezővé vált
egy kurta pillanatra. Elégedettség sugárzott róla, és mélységes nyugalom; a teljes sorsot élt bölcseké.
Ranagol megadta a comturnak az utolsó kegyet, amiért hosszú esztendők-óta minden éjjel fohászkodott.
Syros Iamaranth, a Suttogó Pengék Ura harcban esett el, magával rántva a halálba ellenfelét.
Az Ősök Tudománya által kavart hangvihar elülte után hosszú percekig néma csend honolt a kusza
rommezőn, mely nem is olyan rég még a Kath'ul'Naathum rendháza volt. Semmi sem mozdult az ólomszín félhomályban, csak a konokul kitartó eső szemerkélt tovább a dúlt salakhalmokra és a megtépett
tetemekre, gyászról és halálról susogva halk méltósággal.
Aztán a sötétség hullámokat vetett az öregtorony maradványain, és súrlódó nesz kíséretében
szertefoszlott egy zömök alak körül. Lehajtott fővel állt, vércsatakos szakálla a mellét verdeste; arcát
nedves árnyékok vonták homályba, mélyükön felemás zsarátnokpár világolt. A baloldali parázsdarab
hideg ezüstben izzott; a jobboldali forró, kénsárga fénnyel égett, akár a sárkányok haragja.
Háború lesz; Vyergas tudta. A Ly'Shematenel ház nem fogja bosszulatlanul hagyni az elsőszülött
pusztulását. Az Ötödik Dombon most hamarosan kiélezik a levélforma pengéket, harcra szerszámozzák a
siqquiseket, tiltott nevek segítségét kérik a rönkszentélyekben, a feketetölgyek lombjai alatt. A Quirrta
Khinn velük fog lovagolni, hiszen a ház hercege rangbéli vitézük, az ellenfél pedig az ifjabb népek közül
való.
Ilyen vészterhes időkben a rendnek tapasztalt vezetőkre van szüksége.
Acélvillanás hasított a gyülemlő éjszakába. Vyergas megforgatta a törött mara-sequort, kettőt
suhintott vele a levegőbe, majd maga elé döfte a kavicsos bazaltomladékba, Syros Iamaranth roppant
sírhalmába.
- Comtur! - kiáltotta el magát rekedten. Nem törődött a kimarjult torkában lüktető fájdalommal;
dacosan hátravetette fejét, s körülhordozta égő tekintetét a néptelen udvaron. Látni akarta, hogy van-e
valaki, aki felvállalja kihívását; aki elvitatja tőle a rangot, amelyre igényt emelt.
Valami megmozdult az étkezőház mély árnyékában. Félig eltemették a szögletes homlokzatról ráhulló trófeák roncsai; dühös sziszegéssel lökte félre a szikkadt karokat, zörgő fogakkal vigyorgó koponyákat, ahogy lassan kibontakozott alóluk. Apró volt, izmos és csaknem meztelen testét spirálisan
kígyózó hegek borították; szegecsekkel ékes bőrszíjak fonták körül. Amikor felállt, egy pillanatra megingott, mintha megszédült volna; ám aztán szilárd s határozott léptekkel indult el a szakállas férfi felé,
járása nem árulkodott kétségekről, rejtett bizonytalankodásról.
Vyergas vastag szemöldöke ráncba szaladt: Valamennyi túlélő vadász közül Udunn volt az
egyetlen, aki veszélyt jelenthetett volna címigényére. Udunn, a sura'shtak, az asszonyördög, a
csatabárdboszorkány. Igen; ő méltó ellenfél lenne páros viadalban.
Legyen meg hát Ranagol akarata...
A nő odaért hozzá; és ráemelte tekintetét. Fekete szeme emésztő hévvel tüzelt az arcán
kacskaringózó sebhelyek közül, akár az eleven szén. Az apostolokkal vívott csata megviselte, de nem
jobban, mint Vyergast a párbaj Aurrival. Ha összecsapásra kerülne sor közöttük, csak Káosz-Huvarhg
lenne a megmondhatója, melyikük emelkedik ki győztesen.
Udunn szeme résnyire szűkült. Hirtelen mozdulattal, kígyósebesen rántotta ki az övébe tűzött
vadásztőrt; tekintete meg sem rebbent közben, szívdobbanásnyi időre sem tágított a férfi félbehasított
arcáról. Megpörgette a fegyvert, a magasba kapta, döfésre készen; a megsebzett levegő panaszosan felsírt
a pengeél nyomán.
Vyergas nem moccant.
Hosszú percekig néztek farkasszemet, mint két márványba mintázott kőszobor. Esőpermet verte
megtépett testüket; tétova fuvallatok terítettek hideg hamut hajukra. A levegőben nyirkos tufa szaga
terjengett, rég halott lángok emlékét idézve.
Udunn figyelmeztetés nélkül sújtott le, villámgyors mozdulattal, akár a haragvó vipera. A vadásztőr
a csonka mara-sequor mellé került, remegő markolattal állt a salakos bazaltban.
- Primortel! - vijjantotta el magát az asszony éles vércsehangon.
Vyergas ellazította izmait; feketére perzselt ajkára széles, elégedett mosoly ült ki, a vadászó
cápáéhoz hasonlatos.
Ha a Kosfejes Úris úgy akarja, ők ketten még nagy dolgokat fognak véghezvinni együtt.
